packages/client/src/coordinator/connection/types.ts
packages/client/src/rtc/Call.ts

- Implement `call.off` for coordinator WS events
- Simplify WS event type definitions
- `call.sendEvent` now only accepts valid call event type names

Ws events upgrade

---

packages/react-sdk/src/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/components/StreamCall/ParticipantBox.tsx
sample-apps/react/egress-composite/src/hooks/useAppConfig.ts
sample-apps/react/egress-composite/src/layouts/dominant-speaker/DominantSpeaker.tsx
sample-apps/react/egress-composite/src/layouts/grid/GridView.scss
sample-apps/react/egress-composite/src/layouts/grid/GridView.tsx

Drops the custom grid implementation in Composite in favor of the paginated grid implementation coming from the SDK.
In the SDK, the PaginatedGrid has been extended with some extra props for showing/hiding certain UI elements in Composite mode.
Also, this PR fixes an issue in PaginatedGrid where a single audio track might be played twice.

feat: switch to the SDK provided Grid implementation

---

packages/client/src/rtc/flows/join.ts
packages/react-dogfood/pages/api/call/create.ts

Also, support `/pronto --cid=123 -> pronto.app/join/123`

feat: provide cascading params to get_edge_server

---

packages/react-dogfood/style/chat.scss

Move `UnreadCountBadge` to the left corner of the chat button, size it slightly down, prevents scrollbar from showing up when the badge is rendered.

fix(react-dogfood): adjust UnreadCountBadge styling

---

packages/react-sdk/src/components/CallControls/ReactionsButton.tsx
packages/react-sdk/src/components/CallControls/RecordCallButton.tsx
packages/react-sdk/src/components/CallControls/ScreenShareButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleCameraButton.tsx
packages/react-sdk/src/components/CallParticipantsList/BlockedUserListing.tsx
packages/react-sdk/src/components/CallParticipantsList/CallParticipantListing.tsx
packages/react-sdk/src/components/CallParticipantsList/CallParticipantListingItem.tsx
packages/react-sdk/src/components/Moderation/Restricted.tsx

Checks whether the current user has the appropriate permissions before rendering the default call control buttons.

fix: permission-based rendering of call control buttons

---

packages/client/tsconfig.json
packages/react-dogfood/next.config.mjs
packages/react-dogfood/package.json
yarn.lock

Enables source maps in Pronto in dev mode.
Until now, we were looking at the transpiled JS whenever we had to debug our code. Hopefully, this change would drastically improve our DX.

fix: enable source-maps in dev mode

---

packages/react-sdk/src/core/components/Video/Video.tsx

Fixes: https://getstream.slack.com/archives/C022N8JNQGZ/p1682690286970129
- remove subscription update hook calls for local user
- make sure "fast" subscriptions get called last
- switch to uknown state should trigger subscriptions update too

fix(react-sdk): remove unknown state check, switch hook call order

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts

These are causing invalid links in the docs. Although they won't cause problems (we don't need Angular links in React and RN docs) but they cause [invalid link warnings](https://github.com/GetStream/stream-video-js/actions/runs/4861406970/jobs/8666412964#step:8:77) making it harder to detect real invalid links. Once the Angular SDK is active again we can see if we still need them in the docs.

docs: Remove Angular-specific links from client

---

packages/react-dogfood/components/ActiveCallHeader.tsx
packages/react-sdk/package.json
packages/react-sdk/src/components/Button/CompositeButton.tsx
packages/react-sdk/src/components/Button/CopyToClipboardButton.tsx
packages/react-sdk/src/components/CallControls/CallStatsButton.tsx
packages/react-sdk/src/components/Debug/DebugStatsView.tsx
packages/react-sdk/src/components/Menu/MenuToggle.tsx
packages/react-sdk/src/components/Notification/Notification.tsx
packages/react-sdk/src/components/Permissions/PermissionRequests.tsx
packages/react-sdk/src/components/StreamCall/CallStats.tsx
packages/react-sdk/src/components/Tooltip/Tooltip.tsx
packages/react-sdk/src/hooks/index.ts
packages/react-sdk/src/hooks/useFloatingUIPreset.ts
packages/styling/src/CallStats.scss
yarn.lock

Part of this PR is a simplification of the `CallStats` component:

refactor(react-sdk): replace PopperJS with Floating UI

---

packages/client/src/rtc/flows/__tests__/latency.test.ts
packages/client/src/rtc/flows/join.ts
packages/client/src/rtc/flows/latency.ts

An attempt to make the "measure latencies" step more predictable and reliable.
This new flow will run all latency measurements in parallel, for all provided edges. Every measurement attempt is time-boxed to 1s and the whole measuring process can't take longer than 1.2 seconds.
The coordinator might receive none, or incomplete measurements as a side-effect of this new flow.

feat(latency): breadth-first time-boxed latency measurement

---

packages/client/src/rtc/__tests__/mocks/webrtc.mocks.ts
packages/client/src/rtc/__tests__/publisher.test.ts
packages/client/src/rtc/helpers/tracks.ts
packages/client/src/rtc/publisher.ts

https://github.com/GetStream/stream-video-js/pull/441 introduced a regression in the area of persisting the last used `deviceId` of any media track.
This PR restores the missing functionality and adds a test that verifies the behavior is correct.
On the testing side, I had to mock many of the WebRTC APIs as they aren't natively available in Node nor in the "fake" DOM testing environments like `jsdom` and `happy-dom`. I'd appreciate if you can have a look at this and let me know if you have some better idea how to approach WebRTC unit testing.

fix: preserve last used deviceId when muting

---

packages/client/docusaurus/docs/client/05-advanced/03-permissions-and-capabilities.mdx
packages/client/src/Call.ts
packages/react-sdk/src/components/Permissions/PermissionRequests.tsx

Alignment with other SDKs. Provides two new shortcut methods on the `Call` instance:
- `grantPermissions(userId, permissions[])`
- `revokePermissions(userId, permissions[])`

fix(permissions): add shortcut APIs

---

packages/client/src/Call.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/utils.ts
packages/react-dogfood/components/Lobby.tsx
packages/react-dogfood/components/MeetingUI.tsx
packages/react-dogfood/hooks/useWatchChannel.ts
packages/react-dogfood/pages/guest/join/[guestCallId].tsx
packages/react-dogfood/pages/join/[callId].tsx
packages/react-sample-app/src/App.tsx
packages/react-sdk/src/components/StreamMeeting/StreamMeeting.tsx
sample-apps/react/cookbook-participant-list/src/App.tsx
sample-apps/react/zoom-clone/src/components/Call.tsx

1. Preserve event listeners through user re-connects as these events aren't user-specific
2. When a user is blocked, the Call engine incorrectly triggered the rejoin flow
3. `<StreamMeeting />` now eagerly creates a new `Call` instance (before: the call was created after the initial render phase has finished)
4. Watch for `CallingState.LEFT` and navigate to the homepage whenever the user leaves the call (by pressing the end call button or after being kicked out of the call).
I'd recommend checking the commits individually :)

fix: bugfixes in event handling and blocking users

---

packages/client/src/Call.ts
packages/client/src/events/__tests__/recording.test.ts
packages/client/src/events/callEventHandlers.ts
packages/client/src/events/recording.ts
packages/client/src/store/CallState.ts
packages/react-bindings/src/hooks/call.ts

Adds the missing APIs and event handlers for call broadcasting.
As part of this PR, the redundant `recording` state removed and now it is derived from the call's metadata.

feat: call broadcasting events and apis

---

packages/react-dogfood/pages/api/auth/create-token.ts

Special handling of `call_cids` parameter:
- repeated: `?call_cids=default:123&call_cids=default:456`
- comma separarated: `?call_cids=default:123,default:456`
- JSON encoded: `?call_cids=["default:123", "default:456"]`
This enables generating anon user tokens correctly.

fix: support for call_cids in user tokens

---

packages/client/src/events/callEventHandlers.ts
packages/client/src/events/internal.ts
packages/client/src/rtc/Dispatcher.ts
packages/client/src/store/CallState.ts
packages/react-bindings/src/hooks/participants.ts

The SFU reports the total number of connected participants to the call through regular health-check messages.
This information is now stored on the CallState and exposed via a React Hook to the SDKs.
A typical use-case for this feature is live streams with a lot of anonymous users who can't be counted on the client side as they would be excluded from the client-side participant list.

feat: server-side participant counting

---

packages/react-bindings/src/contexts/StreamCallContext.tsx
packages/react-sdk/docusaurus/docs/React/02-guides/02-joining-creating-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx
packages/react-sdk/docusaurus/docs/React/04-call-engine/01-overview.mdx

- Remove TODOs from state store docs
- Update code examples to use `StreamMeeting` instead of `StreamCallProvider`

docs: Update state store code examples

---

.github/workflows/version-and-release.yml
.github/workflows/workflow.yml
package.json

- Create a separate workflow for release -> only allow one concurrent run from this workflow
- Previously, we only ran versioning for the packages that were affected by the last commit to `main`, this is now changed to run versioning to all packages -> in prerelease mode (which is what we are in currently), this will make a release from each package. In release mode this will work as expected, only changed packages will get a new release. Open GH issue about the prerelease porblem: https://github.com/jscutlery/semver/discussions/385

chore: Fix concurrent release problem

---

packages/client/src/Call.ts
packages/client/src/events/internal.ts
packages/client/src/gen/video/sfu/event/events.ts
packages/client/src/gen/video/sfu/models/models.ts
packages/client/src/rtc/signal.ts
packages/client/src/store/CallState.ts
packages/react-bindings/src/hooks/call.ts
packages/react-bindings/src/hooks/participants.ts

Initialize the server-side participant count right after joining a call. Support for `call.startedAt`.

feat: Participant Count and Call StartedAt

---

packages/styling/src/CallParticipantsView.scss

fix(styling): set min-height to ParticipantView in the legacy grid

---

sample-apps/react/react-video-demo/src/components/ControlMenu/ControlMenu.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx

The demo app used two stateful hooks, `useVideoPublisher` and `useAudioPublisher`.
These hooks were instantiated three times:
- in the root <MediaDevicesProvider /> by the React SDK
- in the <MeetingView /> another <MediaDevicesProvider /> has been instantiated
- <ControlMenu /> used these two internal hooks directly.
Because of recent changes in the SDKs, these hooks were trying to publish a video stream, whenever the current user joins a call, hence, creating a race condition that was causing an error on the SFU side (announced tracks weren't matching with the published tracks).
This PR removes the extra <MediaDevicesProvider /> and updates the <ControlMenu /> component to use the Public API of the SDK.

fix: prevent duplicate video publishing

---

packages/client/src/devices/devices.ts
packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/publisher.ts
packages/client/src/rtc/videoLayers.ts
packages/react-sdk/src/components/Notification/SpeakingWhileMutedNotification.tsx
packages/react-sdk/src/components/Video/VideoPreview.tsx
packages/react-sdk/src/core/contexts/MediaDevicesContext.tsx
packages/react-sdk/src/core/hooks/useAudioPublisher.ts
packages/react-sdk/src/core/hooks/useVideoPublisher.ts
sample-apps/react/zoom-clone/src/components/Preview.tsx

Enables server-side-driven video stream resolution.
- The DevicesAPI now accepts a broader set of MediaTrackConstraints
- The `useVideoPublisherHook` gives precedence to the call's provided target resolution, otherwise it uses a default one

feat: Support for server-side driven stream resolution

---

packages/client/src/events/__tests__/participant.test.ts
packages/client/src/events/participant.ts
packages/client/src/store/CallState.ts

This is an optimization for large calls. After a certain threshold, the SFU would stop emitting `participantJoined` events, and instead, it would only provide the participant's information once they start publishing a certain track.

feat: Participant information from track events

---

packages/client/src/Call.ts
packages/client/src/events/__tests__/backstage.test.ts
packages/client/src/events/__tests__/call.test.ts
packages/client/src/events/__tests__/members.test.ts
packages/client/src/events/backstage.ts
packages/client/src/events/call.ts
packages/client/src/events/callEventHandlers.ts
packages/client/src/events/members.ts
packages/react-bindings/src/hooks/call.ts
packages/react-sdk/docusaurus/docs/React/02-guides/02-call-lifecycle.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/08-permissions-and-moderation.mdx

- Watch for `member_added`, `member_removed`, `member_updated_permission` and `call.member_updated` events
- Watch for `live_started` event, `useIsCallLive` hook added
- `call.ended` event handler fix: watch this for all calls, not just for ring calls
- Send client details in SFU join
- Implement `queryMembers` function -> it doesn't store the result in the state, as I don't know how that data can be merged with the members from join/create response
- Small docs updates

feat: missing WS events and endpoints

---

packages/react-dogfood/components/DisabledVideoPreview.tsx
packages/react-sdk/docusaurus/docs/React/01-basics/04-core-components.mdx
packages/react-sdk/src/components/StreamCall/index.ts
packages/react-sdk/src/components/Video/index.ts
packages/react-sdk/src/core/components/StreamCall/StreamCall.tsx
packages/react-sdk/src/core/components/StreamCall/index.ts
packages/react-sdk/src/core/components/Video/DefaultVideoPlaceholder.tsx
packages/react-sdk/src/core/components/Video/Video.tsx
packages/react-sdk/src/core/components/index.ts

Adds an introductory chapter in the docs which covers the core components of the React SDK that are used almost through every other chapter.
As part of this PR:
- the SDK's `StreamCall` component has been promoted to the `/core/components` package.
- `VideoPlaceholder` got renamed to `DefaultVideoPlaceholder` in order to match with `DefaultParticipantViewUI`

docs: Core components overview

---

packages/react-sdk/docusaurus/docs/React/03-ui-components/01-overview.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/_category_.json
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/call-controls.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/call-recording-list.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/pending-call-panel.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/_category_.json
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/call-layout.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/participant-view.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/stream-call.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/_category_.json
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/call-participants-list.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/device-settings.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/video-preview.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/_category_.json
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/avatar.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/call-stats.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/permission-notification.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/permission-requests.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/reaction.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/speaking-while-muted-notification.mdx

Empty doc pages for UI Components
1. Not all components have a page
- The logic mainly follows the component folder structure in the source code, for example, in the source code, we have the `CallParticipantsList` folder, and we have a doc page called `Participants list`, but there is no separate page for example for the `CallParticipantsList/EmptyParticipantSearchList` component
- Some component folders are not included in the docs, for example the `Icon`. My logic was this: I've excluded all components that don't contain stream-video specific logic. While I can imagine a use-case where someone wants to use the `Icon` component to create their own UI, but it seems rather rare, and I think the component list would be rather long if we were to include all small components.
2. The ToC …

docs: create UI component pages

---

packages/client/src/Call.ts

Adds an optional `callSessionId` argument to the `call.queryRecordings` API.
If provided, the server will return a list of recordings for that one particular call session. Otherwise, a list of all recordings (across many sessions) will be returned, if available.
Also, as part of this PR, a few more methods got their generic types assigned, as they were recently made available.

feat: optional callSessionId in queryRecordings

---

packages/react-dogfood/components/Lobby.tsx
packages/react-dogfood/components/ParticipantsPreview.tsx
packages/react-dogfood/pages/join/[callId].tsx
packages/react-sdk/docusaurus/docs/React/02-guides/02-joining-creating-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/06-lobby-preview.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/09-audio-volume-indicator.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/06-events.mdx
packages/react-sdk/src/components/Video/VideoPreview.tsx

- Add documentation
- Add ParticipantsPreview component to React dogfood app
**Note**
The participants preview is not shown on initial Lobby page load, because we are not getting participants in call query response.
<details><summary>Participants preview in dogfood lobby</summary>
<p>
</p>
</details>

docs(react-sdk): add lobby preview UI cookbook documentation

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/events/__tests__/call-permissions.test.ts
packages/client/src/events/__tests__/sessions.test.ts
packages/client/src/events/call-permissions.ts
packages/client/src/events/sessions.ts
packages/client/src/gen/coordinator/index.ts
packages/client/src/rtc/flows/join.ts
packages/client/src/store/CallState.ts
packages/client/src/types.ts
packages/react-bindings/src/hooks/permissions.ts
sample-apps/react/react-video-demo/src/utils/useMeasureLatencyReponse.ts

Adjusts the React SDK to the latest changes around `own_capabilities` handling: https://github.com/GetStream/chat/pull/5075
`ownCapabilities` are now part of the client call state and they update independently from the rest of the call metadata.
As part of this, the deprecated `getEdgeServer` API method is also removed.

feat: Adjust OwnCapabilities handling

---

packages/client/src/Call.ts
packages/client/src/gen/coordinator/index.ts

Whenever a call is updated, we store the response values within the call's state.

feat: reflect updateCall response data into call's state

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/rtc/__tests__/publisher.test.ts
packages/client/src/rtc/videoLayers.ts

`sessionId` of the current participant will be preserved across reconnects.
Additionally, fallback to the "target resolution" of the video track in case when the browser fails to report the correct track dimensions.

fix: preserve last used session-id when reconnecting

---

packages/client/src/helpers/sdp-munging.ts
packages/client/src/rtc/publisher.ts

- Use and save toggled DTX (prior to this PR, the munged SDP was ignored).
- Remove empty lines after removing a codec (Since a BE change that enabled RED we couldn't publish video/audio on RN)

fix: use and save toggled dtx to sdp and remove empty lines when munging

---

packages/react-dogfood/helpers/jwt.ts
packages/react-dogfood/pages/api/auth/create-token.ts
packages/react-dogfood/pages/join/[callId].tsx

By default, all tokens issued by our service will have an expiry date set 7 days from now.
The expiration can be explicitly specified through the `?exp=<numberOfSecondsFromNow>` query parameter.
Example: `?exp=3600` - will create a token that expires in 1 hour.
**Note**: explicit expiration requests that span longer than 7 days, will be capped to 7 days.
For test purposes, you can issue an "expired" token by providing a negative value in the `?exp=` parameter. 
Example: `?exp=-60` - will create a token that expired 1 minute ago.

chore: adjust default token expiration

---

packages/client/src/Call.ts
packages/client/src/rtc/publisher.ts

Bail out from invoking `stopPublish(trackType)` unless the current user already publishes a track.
This change eliminates the misleading `Stop publishing <KIND>` messages upon call instantiation or load.

fix: prevent misleading "stop publish" log messages upon call instantiation

---

packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/token_manager.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/events/__tests__/call.test.ts
packages/client/src/store/stateStore.ts
packages/react-dogfood/hooks/useGleap.ts
packages/react-dogfood/pages/guest/join/[guestCallId].tsx
packages/react-dogfood/pages/join/[callId].tsx
packages/react-native-call-starter-kit/src/components/ChatWrapper.tsx
packages/react-native-dogfood/src/screens/Meeting/GuestMeetingScreen.tsx
packages/react-native-dogfood/src/screens/Meeting/GuestModeScreen.tsx
packages/react-native-dogfood/types.ts
packages/react-native-sdk/src/hooks/useCreateStreamVideoClient.tsx
sample-apps/react/livestream-app/src/viewers/WebRTCLivestream.tsx
sample-apps/react/messenger-clone/src/types/chat.ts
sample-apps/react/react-video-demo/src/App.tsx

- `User` type is used for `connectUser`
- `OwnUserResponse` is used for `useConnectedUser`
- Regular/guest/anon authentication all done using `connectUser`, `type` param is used to tell if we want to connect a regular, guest or anonymous user
- Guest users are now created by `connectUser`, no need to create them beforehand
Docs update will be in separate PR

feat: User connect and types

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts

Without this fix, while ringing the BE keeps on sending call.ring events, it causes an infinite loop until joined/rejected as below 
```
call.ring -> send ring to BE -> call.ring -> send ring to BE call.ring -> send ring to BE  ......... until call is joined or rejected
```
Now if ring param is set.. only the ringing rx subject is set to true and we don't send to BE. This ensures that we have a local state of ringing.

fix: do not send ring to backend if call was not created by the user

---

packages/client/src/Call.ts

Rejoining of a left call with the same Call instance does not reinstantiate the event handlers and so until we figure out, how to properly clean up the state, we should not allow to re-join a call with the same Call instance.
Applications that keep Call instances in the app state would not react to events arriving over the WS.
A new instance should be added to the app state as follows:
```ts
await call.leave();
const newCall = client.call(call.type, call.id);
await newCall.get();
setCalls((prevCalls) => [
...prevCalls.map((c) => {
return c.cid === call.cid ? newCall : c;
}),
]);
```

fix(client): do not allow to re-join left call

---

packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx

- Match structure with Android SDK (ours is still a bit more verbose)
- Provide more code examples and less explanatory text
While writing the docs I noticed a few things:
- The API calls/data is scattered around a lot of places: we have the `useMediaDevices` for switching, we have the `useToggle...MuteState` for start/stop, and we have the `useLocalParticipant` for getting the device state.
- There is duplication between the `useMediaDevices` hook and between the `useToggle...MuteState` hooks - both can be used for starting/stopping camera/mic, it's confusing.
- We have totally separate API for device management for the lobby screen and after we joined a call. This basically means that our API is 2x the size it could be. I think we should hide that complexity.

docs: Restructure device management guide

---

packages/client/src/devices/devices.ts
packages/react-native-sdk/src/hooks/useLocalVideoStream.ts

Got from https://github.com/react-native-webrtc/react-native-webrtc/issues/1364
without this we get `android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:601: Camera 1: Error clearing streaming request: Function not implemented (-38)` randomly on Android

fix: proper media stream disposal for rn webrtc

---

packages/react-bindings/src/hooks/call.ts
packages/react-bindings/src/hooks/permissions.ts
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx

Based on: https://staging.getstream.io/video/docs/android/guides/call-and-participant-state/
From now on we should make sure to update these tables when something in the code changes.
cc @vanGalilea

docs: Add reference tables to state docs

---

packages/react-sdk/src/core/hooks/useAudioPublisher.ts
packages/react-sdk/src/core/hooks/useVideoPublisher.ts

Audio and Video mute states used to restore to their initial values set in the Lobby when a reconnect event occurs although the participant might muted self throughout the call.
This PR ensures that automatic audio/video publishing happens only when:
- joining the call from the Lobby screen with audio or video enabled
- reconnecting to a call while audio or video streams are still in "publish" state

fix: prevent unmute after reconnect

---

sample-apps/react-native/dogfood/src/components/NavigationHeader.tsx
sample-apps/react-native/dogfood/src/screens/Call/JoinCallScreen.tsx

This PR has 2 fixes:
* The header had extra bottom padding in iOS due to safearea, fixed now
*  The Join call text input was hidden by keyboard, fixed now

fix(react-native): dogfood app keyboard issues and unintentional large header

---

packages/react-dogfood/sentry.server.config.js

If a React Dogfood request has the header `x-react-dogfood-no-trace` we won't sent the request data to Sentry.

feat: Make it possible to opt-out from Sentry tracking

---

packages/react-bindings/src/wrappers/Restricted.tsx
packages/react-sdk/src/components/CallParticipantsList/CallParticipantsList.tsx

The prop was used in a single place and relied on the same source of data. According to todo note, the plan was to remove it.

refactor(react-bindings): remove availableGrants from RestrictedProps

---

packages/react-native-sdk/__tests__/components/CallParticipantsView.test.tsx
packages/react-native-sdk/src/components/CallParticipantsList.tsx
packages/react-native-sdk/src/components/CallParticipantsSpotlightView.tsx
sample-apps/react-native/dogfood/src/components/ActiveCall.tsx
sample-apps/react-native/dogfood/src/components/MeetingUI.tsx

The changes: https://www.loom.com/share/b1065f4762bd4bf88ebdb790fc21ad75?sid=9fd5f403-958a-4368-913d-c0d25ed53858
In figma, on 1:1 calls the video stream takes the full space. This pattern can be seen in 2:1 calls too. 4:1 and then 6:1. 
When its more than 6 participants we start to scroll.
This PR implements the above behavior.

feat(react-native): align call participants list with figma

---

packages/client/src/events/__tests__/participant.test.ts
packages/client/src/events/callEventHandlers.ts
packages/client/src/events/participant.ts

Although the SFU should not send duplicate events, we have seen some race conditions in the past during the `join-flow` where the SFU would send participant info as part of the `join` response and then follow up with a `participantJoined` event for already announced participants.
As part of this PR, I also took the time to decouple the event listener subscription from the actual event handler.

fix: safeguard against potential race conditions during join-flow

---

packages/client/src/events/__tests__/call-permissions.test.ts
packages/client/src/events/call-permissions.ts
packages/client/src/events/callEventHandlers.ts
packages/client/src/store/CallState.ts
packages/react-bindings/src/hooks/permissions.ts
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/08-permission-requests.mdx
packages/react-sdk/src/components/Permissions/PermissionRequests.tsx

We stop tracking `call.permission_request` events in `Call` state to avoid the `useCallPermissionRequest` hook emitting repeatedly the same event on each re-render. That would lead to duplication of the same event in the component's local state of requests list.

feat: stop tracking permission requests in Call state

---

packages/react-sdk/docusaurus/docs/React/03-ui-components/call/call-controls.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/call-recording-list.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/call/pending-call-panel.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/call-layout.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/stream-video.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/call-participants-list.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/device-settings.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/video-preview.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/avatar.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/call-stats.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/permission-notification.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/reaction.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/speaking-while-muted-notification.mdx

- [Unify the structure of UI components pages](https://github.com/GetStream/stream-video-js/pull/571#issue-1732498263)
- `Customization` section is moved to end of page (it makes more sense to write about that after `Props`)
- `StreamVideo` page is added

docs: Unify UI components structure

---

packages/client/src/Call.ts
packages/react-sdk/src/core/contexts/MediaDevicesContext.tsx
packages/react-sdk/src/core/hooks/useAudioPublisher.ts
packages/react-sdk/src/core/hooks/useVideoPublisher.ts

Upon reconnection, the effect ran twice and led to race conditions that may mess up the state of the local participant.
Under some circumstances, the local participant would point to an ended video/audio stream while the other one would be normally published to the SFU.

fix: prevent double publishStream invocation

---

packages/client/src/rtc/Publisher.ts

There is a conflict between video and screen share tracks as both of them have `video` set as a kind. As a consequence, sometimes we were picking up the `mid` identifier of the "other" track. Now, we take the `msid` parameter into consideration when doing the media selection.

fix: Reliable mid detection

---

packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/rtc/flows/join.ts

If the fix works, I'll rename the `connectionIdPromise` to a better name

fix: wait for connection ok for all API requests

---

packages/react-sdk/src/core/hooks/useAudioPublisher.ts
packages/react-sdk/src/core/hooks/useVideoPublisher.ts

We recently regressed (#749) and broke the on-the-fly device switching. This PR restores the previous behavior.

fix: restore device switching functionality

---

packages/client/src/StreamVideoClient.ts
packages/react-native-sdk/src/utils/push/utils.ts

- Having the `ringing` flag in `client.call` can be misleading to integrators, for example they could do: `client.call('default', '123', true),join({ring: false})`
- The flag also creates API mismatch with iOS and Android
`client.onRingingCall` will create a ringing call from a push notification. The naming is based on: https://github.com/GetStream/stream-video-android/blob/develop/stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/notifications/internal/VideoPushDelegate.kt#L82
@santhoshvai can you please help with the testing?

feat: Remove ringing flag from call client

---

packages/client/src/gen/coordinator/index.ts

https://github.com/GetStream/stream-video-js/commit/739602e6ddb9e56502c1dfb228b44760c88e4cdb accidentally removes the `CallUserMuted` event which causes compilation errors.
This PR restores it back.

fix: restore CallUserMuted event

---

packages/client/src/events/__tests__/sessions.test.ts
packages/client/src/events/sessions.ts
packages/client/src/gen/coordinator/index.ts
packages/react-dogfood/components/Lobby.tsx
packages/react-dogfood/components/ParticipantsPreview.tsx

Updates to the newest OpenAPI schema and now we respect the `user_session_id` parameter.
Without this field, we were filtering out participants based on their `user_id` which is problematic in scenarios where the same user enters the same call multiple times.

feat: respect user_session_id in call.session events

---

packages/client/src/rtc/Publisher.ts

without this,
when pc.close is done, negotiate is called immediately on RN and maybe also non chromium browsers?! and results in the following error 
```
Possible Unhandled Promise Rejection (id: 1):
Error: CreateOffer called when PeerConnection is closed.
```

fix: promise rejection on call leave

---

.github/workflows/react-native-workflow.yml

Usually, it takes 4-7 minutes for bootstrap to complete. If it takes longer, it will be stuck and fail by timeout. For now, reducing the timeout to get the failed job faster.

fix: [RN] Reduce bootstrap timeout

---

packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/location.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/rtc/flows/join.ts

In order to speed up the join flow, the location hint parameter is now determined and cached at SDK initialization (i.e. at the time when the `StreamVideoClient` instance is constructed). This should save us ~0.5 seconds during the join phase.

feat: take the location-hint on SDK init

---

packages/angular-sdk/package.json
packages/client/package.json
packages/react-bindings/package.json
packages/react-native-sdk/package.json
packages/react-sdk/package.json
yarn.lock

Fixes an error in React SDK as `prop-types` is an implicit dependency used by `@nivo/core` and `@nivo/line`.
As part of this PR, some leftover dependencies related to the past automated documentation generation are removed as well.

fix: promote prop-types to a 'dependency' in react-sdk

---

sample-apps/react-native/dogfood/.gitignore
sample-apps/react-native/dogfood/Gemfile.lock
sample-apps/react-native/dogfood/README.md
sample-apps/react-native/dogfood/fastlane/Fastfile
sample-apps/react-native/dogfood/package.json

The guide for the sentry token is added because of the failing tests on my local environment even though I have the token on my ~/.zshrc. It seems like it needs to be in the `.env` of the project to run the tests.

refactor(react-native): e2e tests local commands and improved guide to run the e2e tests

---

packages/i18n/src/translations/de.json
packages/i18n/src/translations/en.json
packages/i18n/src/translations/es.json
packages/i18n/src/types.ts
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/08-permission-requests.mdx
packages/react-sdk/src/components/CallControls/ReactionsButton.tsx
packages/react-sdk/src/components/CallControls/RecordCallButton.tsx
packages/react-sdk/src/components/CallControls/ScreenShareButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx
packages/react-sdk/src/components/Permissions/PermissionRequests.tsx
packages/react-sdk/src/hooks/index.ts
packages/react-sdk/src/hooks/useRequestPermission.ts
packages/react-sdk/src/hooks/useToggleAudioMuteState.ts
packages/react-sdk/src/hooks/useToggleCallRecording.ts
packages/react-sdk/src/hooks/useToggleScreenShare.ts
packages/react-sdk/src/hooks/useToggleVideoMuteState.ts

1. permission states not persisted/properly propagated
- disable audio and video by clicking the context buttons - whatever comes first (in this case audio) is overriden and can be published by the user
- after reload (user which had their audio/video disabled) can seemingly publish tracks but other users won't see/hear anything - works only after explicitly allowing it (sometimes)
2. missing dismiss events (do nothing)
- currently "dismissing" permission requests leads to revoking (user A and user B receive request from user C, user A allows, user B "dismisses", user C still cannot publish)
- dismissing permission request from the requestor side won't remove dismissed requests from the list of the target users
TODO:

feat(react-sdk): extract toggle functions to hooks + permissions

---

sample-apps/react/react-dogfood/components/MeetingUI.tsx
sample-apps/react/react-dogfood/hooks/index.ts
sample-apps/react/react-dogfood/hooks/useWakeLock.ts

This hook prevents your screen from dimming while in a long noninteractive call.
[Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) has not been yet implemented to the FF so this feature only works on other major browsers (apparently on Safari too 🤯).

feat(react-dogfood): add useWakeLock hook

---

packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/Subscriber.ts

This is a follow-up to #814. We are reducing the delay to 2.5 seconds until we perform an ICE restart.

fix: shorter thresholds for ICE restarts

---

packages/react-sdk/docusaurus/docs/React/02-tutorials/01-video-calling.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/02-audio-room.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

Adds backlinks to the main marketing pages in all of our tutorials.
Context: https://getstream.slack.com/archives/C022N8JNQGZ/p1689185200690119

docs: add backlinks to the main marketing pages

---

sample-apps/react/react-dogfood/components/ParticipantsPreview.tsx

Provide fallback `name` to participant lobby avatar to make sure avatar is displayed even though `participant.user.name` is undefined.

fix(react-dogfood): provide fallback to participant Avatar in lobby

---

packages/client/src/Call.ts
packages/client/src/__tests__/server-side/call-types.test.ts
packages/client/src/__tests__/server-side/call.test.ts

- `call.create` added: https://getstream.slack.com/archives/C05FT65AVT8/p1690189296241139
- the delete call type test fails from time to time, I checked it a number of times, [it has to be a backend issue](https://getstream.slack.com/archives/C040262MY9K/p1690198559995009), but I don't think it's being fixed. I added a retry logic for the test to hopefully avoid flakiness.

feat: Add call.create

---

packages/client/src/devices/devices.ts
packages/react-sdk/src/core/contexts/MediaDevicesContext.tsx

The initial device state shall be set regardless of the call state as this is primarily driven by the backend.
Together with this change, I've improved the logging and the disposal of temporary media streams created while enumerating the media devices.
Also, the `stopPublishingAudio/Video` methods can be awaited now.

fix: set initial device state regardless of call state

---

sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/Layout/LobbyLayout/LobbyLayout.module.css
sample-apps/react/react-video-demo/src/components/Layout/LobbyLayout/LobbyLayout.tsx

Enables scrolling in the lobby when the "native apps banner" is shown. See: #832 
Also, fixes the duplicated `GET /edges` request.

fix: scrolling when mobile banner is visible

---

packages/client/src/Call.ts

Eagerly update track subscriptions when restoring the connection to the call.

fix: update subscriptions when restoring connection

---

packages/client/src/events/call.ts
packages/client/src/gen/coordinator/index.ts

`CallSession` now includes information about when a certain call went "live" and when "live" ended.
- `live_started_at` is set to the current time when the session starts if the call is not in backstage mode
- `live_started_at` is set to the current time by goLive
- `live_ended_at` is set to the current time when the session has ended and `live_started_at` is not NULL
- `live_ended_at` is set to current time by `stopLive` or by `endCall` if backstage is configured for this call
- `goLive` resets `call.ended_at` to NULL
Reference: https://github.com/GetStream/chat/pull/5254

feat: enhanced call session

---

sample-apps/react/react-video-demo/index.html
sample-apps/react/react-video-demo/src/components/Header/MobileAppBanner.tsx
sample-apps/react/react-video-demo/src/components/Layout/LobbyLayout/LobbyLayout.tsx
sample-apps/react/react-video-demo/src/components/Views/LobbyView/LobbyView.tsx

Disables the App-Clips integration for iOS. Show a custom banner when opening the demo app from an iOS device and a non-Safari browser.
Related: #832

fix: disable app-clips, show banner for iOS as well

---

packages/react-sdk/src/core/components/ParticipantView/ParticipantView.tsx

The `audio` element essentially does nothing when muted so to reduce amount of rendered elements we can safely remove it.

fix(ParticipantView): remove audio element while muted

---

packages/client/src/Call.ts
packages/client/src/gen/coordinator/index.ts
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

Add additional configuration parameters for the `call.goLive()` endpoint.

feat: extra config params in goLive() API

---

packages/react-bindings/src/hooks/callStateHooks.ts

Fixes a regression introduced with #931

fix: correctly report `live` state of the call

---

packages/react-bindings/src/contexts/StreamI18nContext.tsx
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx

If you check the logic for `changeLanguage`, the first condition in it says https://github.com/GetStream/stream-video-js/blob/main/packages/i18n/src/StreamI18n.ts#L88 which internally throws the warning:
```
I18n instance is not initialized. Call yourStreamI18nInstance.init().
```
This is a yellow box warning for RN SDK.
-----
Now in StreamI18nContext, we have a redundant condition that seems to `changeLanguage` if there is no `language` passed. But that condition is used when the `i18n.isInitialized` is false/undefined, which will, in turn, call the `this._checkIsInitialized()` from the `changeLanguage` and return the warning.
This PR tries to solve this issue and remove the redundant condition.

refactor(react-bindings): remove redundant language check

---

packages/react-native-sdk/src/components/Participant/ParticipantView/ParticipantLabel.tsx

currently it checks for local camera's mute

fix(react-native): participant label should check for sfu mute state

---

sample-apps/react/react-video-demo/index.html

Provides a `meta` tag pointing to the corresponding app in App Store.

fix: provide apple-itunes-app meta tag for the demo app

---

packages/client/src/StreamVideoClient.ts
packages/client/src/__tests__/StreamVideoClient.test.ts
packages/client/src/coordinator/connection/client.ts

I ran into this problem while creating the livestream viewer sample app, where I'll use guest users

fix: guest auth didn't wait for some API calls

---

sample-apps/react/react-video-demo/src/App.tsx

Provides the current URL that includes the call ID as an argument to iOS Safari smart app banner.

fix: provide app-argument for iOS smart banners

---

packages/client/src/Call.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/devices/__tests__/mocks.ts

- Backend sends us the target resolution for the video stream -> the new device API now applies these settings
- Additional safeguards to make sure we don't accidentally start two media streams / publish twice when we init the camera/mic in the join method
@khushal87, @vishalnarkhede  can you please test that everything works with RN as expected?

feat: apply target resolution to video feed, sync camera/mic init

---

.github/workflows/deploy-react-sample-apps.yml

Run specific steps only if it passes through path filters.
See `Test Step` and `Filters for "messenger-clone"` and `Filters for "egress-composite"` (click through matrixed jobs, see outcome of the Filters steps) in [this CI run](https://github.com/GetStream/stream-video-js/actions/runs/5964839414/job/16180956750?pr=989).
Changed files for testing purposes: `egress-composite/env.example` and `messenger-clone/env.example`, every other outcome should be `false`.

chore(sample-apps): sample-apps workflow update

---

packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/participants/floating-participant-view.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/participants/participant-view.mdx
packages/react-native-sdk/jest-setup.ts
packages/react-native-sdk/jest.config.ts
packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx
packages/react-native-sdk/src/components/Participant/FloatingParticipantView/index.tsx

This will be useful when we want to change the participant on tap of FloatingParticipantView in 1:1 calls.
Moreover removing localParticipant from FloatingParticipantView makes sense, since its a generic view.

feat(react-native): pass participant as prop in FloatingParticipantView

---

sample-apps/react/egress-composite/src/CompositeApp.tsx
sample-apps/react/egress-composite/src/hooks/index.ts
sample-apps/react/egress-composite/src/hooks/useExternalCSS.ts
sample-apps/react/egress-composite/src/main.tsx

Load external CSS through `ext_css` configuration attribute.

feat(egress-composite): add support for external CSS

---

packages/client/src/Call.ts
packages/client/src/rtc/codecs.ts

While talking to suchith I realised that we should not do any codec changes to sdp when sending the dummy sdp.

fix: do not do any codec preferences when sending dummy sdp

---

packages/react-native-sdk/docusaurus/docs/reactnative/02-tutorials/03-livestream.mdx

docs(react-native): fix live streaming docs headings

---

packages/react-native-sdk/src/providers/MediaStreamManagement.tsx

If we pass:
```
mediaDeviceInitialState={{
initialAudioEnabled: true,
initialVideoEnabled: true,
}}
```
to `StreamCall` it is expected that the initial states in the lobby/call will be unmute for the camera and microphone.
However, the mic and camera still remain muted in the Lobby. Which I don't think should happen. The culprit here is `call?.microphone.state.status` which is `undefined` and `initialAudioEnabled` if `true`, `initialAudioEnabled && call?.microphone.state.status === 'disabled'` will always result in `false`, no matter what.
The PR tends to fix this issue.

fix(react-native-sdk): handle media device initial state when media status is undefined

---

packages/react-native-sdk/src/components/Call/CallControls/ToggleCameraFaceButton.tsx

To keep the behaviour of onPressHandler consistent with other control buttons.

fix: override default handler with onPressHandler prop for ToggleCameraButton

---

packages/react-native-sdk/expo-config-plugin/__tests__/withAppDelegate.test.tsx
packages/react-native-sdk/expo-config-plugin/__tests__/withMainApplication.test.tsx
packages/react-native-sdk/expo-config-plugin/fixtures/MainApplication.java
packages/react-native-sdk/expo-config-plugin/fixtures/index.ts
packages/react-native-sdk/expo-config-plugin/src/index.ts
packages/react-native-sdk/expo-config-plugin/src/withAppDelegate.ts
packages/react-native-sdk/expo-config-plugin/src/withMainApplication.ts
packages/react-native-sdk/package.json
sample-apps/react-native/expo-video-sample/android/gradle.properties
sample-apps/react-native/expo-video-sample/ios/expovideosample.xcodeproj/project.pbxproj
sample-apps/react-native/expo-video-sample/ios/expovideosample/AppDelegate.mm

Changes - 
- Add MainApplication.java setup methods using the plugin
- Improve the import method for AppDelegate.mm
- Improve test coverage to:
```
-------------------------|---------|----------|---------|---------|-------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------------|---------|----------|---------|---------|-------------------
All files                |   96.29 |    83.33 |     100 |   96.29 |
fixtures                |     100 |      100 |     100 |     100 |
index.ts               |     100 |      100 |     100 |     100 |
src                     |      96 |    83.33 |     100 |      96 |
withAppDelegate.ts     |   93.75 |       75 |     100 |   93.75 | 44
withMainApplication.ts |     100 |      100 |     100 …
```

feat(react-native): add plugin to update the setup method to MainApplication.java

---

sample-apps/react/react-dogfood/pages/join/[callId].tsx
sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/utils/getURLCredentials.ts

Adds support for `log_level` query param for the Video Demo app. Also the current `call` and `client` instances are exposed via the `window` object for easier debugging.

fix: enable log level overriding, expose call and client on window

---

packages/react-sdk/src/core/components/Video/Video.tsx
sample-apps/react/react-video-demo/src/components/ControlButton/ControlButton.tsx
sample-apps/react/react-video-demo/src/components/ControlMenu/ControlMenu.tsx
sample-apps/react/react-video-demo/src/components/Participant/Participant.tsx

- Sorts out effect dependencies in CallControl components.
- Tall videos now render without cropping
- Fixes an issue where track dimensions can't be determined early by adding a new event listener that recomputes everything after the bound track unmutes.

fix: hook dependency issues, re-compute video aspect ratio after track unmute

---

.github/workflows/deploy-react-sample-apps.yml

Reverts #989 
Sample Apps need to get new production deployments whenever the SDKs get an update. That's how we ensure they run well with the latest SDK version.

fix: deploy sample apps whenever there are changes within the SDKs

---

packages/react-native-sdk/.gitignore
packages/react-native-sdk/__tests__/components/CallParticipantsGrid.test.tsx
packages/react-native-sdk/__tests__/components/CallParticipantsSpotlight.test.tsx
packages/react-native-sdk/__tests__/components/ParticipantView.test.tsx
packages/react-native-sdk/__tests__/mocks/participant.ts
packages/react-native-sdk/expo-config-plugin/tsconfig.json
packages/react-native-sdk/jest-setup.ts
packages/react-native-sdk/jest.config.ts
packages/react-native-sdk/package.json
packages/react-native-sdk/src/components/Call/Lobby/Lobby.tsx
packages/react-native-sdk/src/components/Call/RingingCallContent/OutgoingCall.tsx
packages/react-native-sdk/src/components/Participant/ParticipantView/VideoRenderer.tsx
packages/react-native-sdk/src/hooks/internal/useCallMediaStreamCleanup.ts
packages/react-native-sdk/src/index.ts
packages/react-native-sdk/src/providers/MediaDevices.tsx
packages/react-native-sdk/src/utils/setClientDetails.ts
packages/react-native-sdk/tsconfig.json
yarn.lock

Our SDK lacks common js support. Also expo config plugin works only with common JS. 
This PR fixes them both.
I tested the build to work by packing it in `yarn pack`
And putting the path to the SDK in package.json of a completely new app 
for example:
```
"@stream-io/video-react-native-sdk": "file:/Users/santhoshvaiyapuri/Projects/stream-video-js/packages/react-native-sdk/package.tgz",
```

fix(react-native): add missing commonjs support

---

packages/client/package.json
packages/client/src/Call.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/SpeakerManager.ts
packages/client/src/events/__tests__/mutes.test.ts
packages/client/src/events/callEventHandlers.ts
packages/client/src/events/index.ts
packages/client/src/events/mutes.ts
packages/client/src/rtc/Publisher.ts
yarn.lock

Restores the disabled Remote Muting functionality. See #1070 and #988.
The determination of whether a user has been soft-muted now happens based on event data. Previously this has been done by comparing participant states, and it had a lot of edge cases that were hard to handle due to the async nature of the state updates.
While here, I took the time to update the test dependencies we use.

feat: restore remote muting functionality

---

packages/react-native-sdk/docusaurus/docs/reactnative/03-core/08-native-permissions.mdx

Think this is a leftover from the native permissions work? 
Used to be this - 
```
In this step, we create two functions called `androidProcessPermissions` and `iOSProcessPermissions`. These functions are responsible for informing the status of the permission grants to the SDK. 
```
but seems to be not needed anymore

docs(react-native): remove unused docs import

---

packages/client/src/StreamSfuClient.ts

In order to make it easier to spot which RPC call resulted in an error, we now include the RPC method's name in the logs.

chore: include RPC method name in error logs

---

packages/client/src/helpers/DynascaleManager.ts
packages/client/src/helpers/__tests__/DynascaleManager.test.ts

- removing registered element from the screen wouldn't update subscriptions
- subscribing to `participant$` within `bindVideoElement` would call `map` operator 3 times on each `call.state.participants$` update per `bindVideoElement` call (per `sessionId`)

fix(DynascaleManager): update subscription upon cleanup

---

packages/react-sdk/README.md
sample-apps/react/react-dogfood/components/Lobby.tsx
sample-apps/react/react-video-demo/src/components/ControlMenu/ControlMenu.tsx

Applies consistent ordering of the call control buttons:
- Mic
- Camera
- Speakers

chore(ux-feedback): re-arrange call control buttons

---

packages/client/docusaurus/docs/javascript/10-advanced/05-join-from-link.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/05-join-from-link.mdx

Adds a guide on how one can build a flow that allows joining a particular call instance via a direct link.

docs: Guide for joining a call from a link

---

sample-apps/react/react-video-demo/src/App.tsx

Switches the deep linking scheme to `streamvideo://`

fix: use custom url scheme for deep-linking

---

packages/client/src/helpers/DynascaleManager.ts

Prevent setting `undefined` as `sinkId` which caused issues.

fix: add type check of deviceId before setting sinkId

---

packages/react-native-sdk/src/components/Call/CallControls/ToggleAudioPreviewButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/ToggleVideoPreviewButton.tsx
packages/react-native-sdk/src/index.ts
packages/react-native-sdk/src/providers/MediaStreamManagement.tsx

Currently, the initial media stream doesn't account for the fact that local SDK settings. That is fixed in the PR. The BE settings are also applied and the final result is accounted for when the call is joined. The priority is Local SDK settings > BE settings > User manual mutes/unmutes.
Note: The PR is tested both on android and iOS and works fine for all the cases.

fix(react-native): initial media stream management according to BE and SDK settings

---

packages/client/project.json

Should fix the misleading `"@stream-io/video-client updated to version 0.1.0"` message in the generated CHANGELOG on dependent packages.
Beforehand, a new tag `@stream-io/video-client-0.3.27` has been manually created.

fix: use `@stream-io/video-client` as a tag prefix

---

packages/react-sdk/src/hooks/useRequestPermission.ts
packages/react-sdk/src/hooks/useToggleAudioMuteState.ts
packages/react-sdk/src/hooks/useToggleScreenShare.ts
packages/react-sdk/src/hooks/useToggleVideoMuteState.ts

The `canRequestPermission` value is irrelevant when requested permission is already granted.
Previously, there was an edge case where, a participant may have `send-video` permission assigned but, the call settings prohibit requesting permission. In that case, `requestPermission` incorrectly returned `false`.

fix: requestPermission should be no-op when permission is already granted

---

packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx

Rendering `<LivestreamLayout />` before participants are initialized may lead to various errors where some of the rendered participants are `undefined` while TS says otherwise. 
Until we sort out the types, we are adding an explicit null check to the `currentParticipant` variable.

fix: check if `currentParticipant` is actually initialized

---

.github/workflows/egress-composite-e2e.yml
sample-apps/react/egress-composite/package.json
sample-apps/react/egress-composite/playwright.config.ts
yarn.lock

Ditches `stream-video-buddy` package from the `egress-composite` application which was previously used for E2E tests but is no longer needed, reinstate once relevant again.

chore: remove unused stream-video-buddy package

---

packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/call/lobby.mdx
packages/react-native-sdk/src/components/Call/Lobby/Lobby.tsx
packages/react-native-sdk/src/components/Call/Lobby/LobbyFooter.tsx
packages/react-native-sdk/src/components/Call/Lobby/index.ts
packages/react-native-sdk/src/translations/en.json
sample-apps/react-native/dogfood/src/translations/en.json

In adding a meeting UI, I found I couldn't customise the text above the button in the Lobby component. As we will be using the channelId for the callId, I didn't like that it said they were joining this seemingly random ID. This would likely be confusing to the user as they have no reference to this. 
Changes - 
- Add a LobbyFooter component to the Lobby and the ability to customise it
- Updated the documentation
Tested - 
- I've tested this causes no changes in behaviour in the DogFood app and that I customise it
Note - I've also updated the translation as there was a random capital "J" in join. I can revert if this was intentional.

feat(react-native):  add lobby footer component

---

packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts

Ensure Stable Sorting by mutating the source participant array.

fix: ensure stable sort

---

packages/react-native-sdk/docusaurus/docs/reactnative/03-core/08-native-permissions.mdx

react native permissions lib has moved to a new setup and our docs had the old setup.. 
to avoid this in future, its better to just link to their setup

docs(react-native): remove the outdated react native permissions lib setup

---

packages/client/src/sorting/__tests__/presets.test.ts
packages/client/src/sorting/presets.ts
packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx

Sort dominant speakers only when their visibility state is unknown or invisible (UNKNOWN in this case).
Note: I'd like to test this properly in our next group call before we merge.

fix: sorting in paginated grid

---

sample-apps/react/react-video-demo/src/components/ControlMenuPanel/ControlMenuPanel.data.ts
sample-apps/react/react-video-demo/src/components/ControlMenuPanel/ControlMenuPanel.tsx
sample-apps/react/react-video-demo/src/components/DeviceList/DeviceList.data.ts
sample-apps/react/react-video-demo/src/components/DeviceList/DeviceList.tsx

Ensure that a default video/audio device is selected.
Sometimes, the browsers may report a new `deviceId` for an already known device. Once that happens, our previously stored device preferences can't be respected, and we fall back on selecting the first device on the list.
This aligns with the behavior implemented in the React SDK-provided call controls.

fix(video-demo): ensure default device is selected

---

packages/client/docusaurus/docs/javascript/10-advanced/06-events.mdx
packages/client/src/gen/coordinator/index.ts
packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/03-events.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/06-events.mdx

Allows remote muting of `screenshare_audio` tracks. Also, updates to the newest OpenAPI schema (GetStream/protocol) that introduces `call.hls_broadcasting_failed` event.

feat: mute screenshare_audio, update to the newest OpenAPI schema

---

packages/react-sdk/src/core/components/Video/Video.tsx

In some cases, a stream may start playing before our `play` and `pause` event handlers are attached to the appropriate `video` element and our state will have incorrect values.
In that case, we may incorrectly render a placeholder instead of the actual video.

fix: sync video "paused" state more accurately

---

sample-apps/react/react-video-demo/src/components/Footer/Footer.tsx
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.module.css
sample-apps/react/react-video-demo/src/components/Participant/Participant.module.css
sample-apps/react/react-video-demo/src/contexts/PanelContext.tsx

- close the border-radius gap when a participant is highlighted (speaking)
- toggle layout switcher panel once the button is clicked

fix(demo): styling and usability improvements

---

packages/react-bindings/src/hooks/callStateHooks.ts
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/03-call-and-participant-state.mdx
packages/react-native-sdk/src/components/Livestream/LivestreamControls/HostStartStreamButton.tsx
packages/react-native-sdk/src/components/Livestream/LivestreamTopView/HostLivestreamTopView.tsx
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx
sample-apps/react/livestream-app/src/hosts/ui/BackstageControls.tsx
sample-apps/react/livestream-app/src/hosts/ui/BackstageHeader.tsx
sample-apps/react/livestream-app/src/viewers/HLSLivestream.tsx
sample-apps/react/react-dogfood/components/DevMenu.tsx

This PR focuses on changing the name of the useIsCallBroadcastingInProgress to useIsCallHLSBroadcastingInProgress. This was done in favor of the discussion - https://getstream.slack.com/archives/C04ATV49DU3/p1698237035492179.
**API change**
-----------------
- refactor the name of useIsCallBroadcastingInProgress to useIsCallHLSBroadcastingInProgress
**Related changes**
------------------
- Updated the sample apps with the new hook.
- Updated the call and participants guide with the new hook.

refactor(react-bindings): change useIsCallBroadcastingInProgress to useIsCallHLSBroadcastingInProgress

---

sample-apps/react-native/dogfood/src/screens/LiveStream/ViewLiveStream.tsx
sample-apps/react-native/dogfood/src/screens/LiveStream/ViewerLobby.tsx

Fix the dog food app livestream flow on the viewer's end, especially around subsequent joins. This involves the removal of the autoJoin flow and joining the call through the button after the waiting period is over. Moreover, on subsequent joins, the call state is checked, and if the state is joined/joining, the lobby is simply removed.

fix(react-native-dogfood): issue in subsequent call join in livestream

---

packages/react-sdk/docusaurus/docs/React/03-ui-components/participants/video-preview.mdx
packages/react-sdk/src/components/VideoPreview/VideoPreview.tsx
packages/react-sdk/src/translations/en.json

Exposes `className` prop on the `VideoPreview` component that allows easier styling with CSS-in-js libraries as `styled-components`.

fix(video-preview): accept `className` prop

---

packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/09-audio-volume-indicator.mdx
sample-apps/react/react-dogfood/components/AudioVolumeIndicator.tsx

`AudioLevelIndicator` shouldn't destroy the MediaStream allocated by the MicrophoneManager.

chore: don't destroy stream on unmount

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/__tests__/StreamVideoClient.test.ts
packages/client/src/devices/InputMediaDeviceManager.ts

This is a small enhancement I wanted to do for the longest time:
Previously device config settings from the backend were only applied when we joined the call. However, sometimes we have this information sooner in the following cases:
- `get` or `getOrCreate` is called
- `Call` is created after `queryCalls` response
This PR applies backend settings in those cases. An important thing to note: the `mic_default_on` and `camera_default_on` are NOT applied in the above cases, because applying those settings could start the camera/mic, these settings are only applied after we joined the call.

feat: Apply device config settings when call state becomes available

---

packages/react-sdk/src/components/VideoPreview/VideoPreview.tsx
sample-apps/react/zoom-clone/src/components/Preview.tsx

Adds marker CSS classes to the default `VideoPreview` components in order to allow easier styling.
As part of this PR, an issue in Zoom Clone is fixed too (reference: https://github.com/GetStream/stream-video-js/pull/1169)

fix: add marker classes for the default `VideoPreview` components

---

sample-apps/react-native/dogfood/src/screens/LiveStream/JoinLiveStream.tsx
sample-apps/react-native/dogfood/src/screens/Meeting/GuestModeScreen.tsx
sample-apps/react-native/dogfood/src/screens/Meeting/JoinMeetingScreen.tsx

Added a simple validation for custom call IDs in meeting and livestream join flow.
The call ID strings with alphabets, numbers, hyphens(-), and underscore(_) in them are only allowed and enabled the button for a call.
Regex Used for validation - `/^[A-Za-z0-9_-]*$/g`

fix(react-native-dogfood): do not allow invalid call ids

---

packages/react-sdk/package.json
yarn.lock

`rxjs` isn't directly used in `react-sdk` anymore (see #1127).
This PR removes the dependency from the list of dependencies.

chore(deps): remove the unused `rxjs` dependency from the `react-sdk`

---

sample-apps/react/react-dogfood/helpers/logger.ts

In large calls `audioLevelChanged` and `dominantSpeakerChanged` events are polluting the logs, and make it hard to spot issues.

chore: reduce logging noise in Pronto

---

packages/react-sdk/src/core/components/Audio/ParticipantsAudio.tsx

Follow up on #1176. Sets the `key` prop on the top-most `Fragment` instead to the wrapped elements.

fix: set `key` prop to the correct element

---

sample-apps/react/react-dogfood/components/CallLayout/SpeakerOneOnOne.tsx
sample-apps/react/react-dogfood/components/Debug/useIsDebugMode.ts
sample-apps/react/react-dogfood/components/Stage.tsx

A follow-up to #1182. Some layouts didn't properly receive the configured layout props. This PR fixes that.

fix: show debug stats in every call layout

---

packages/react-native-sdk/ios/StreamVideoReactNative.h

fix(react-native): Cannot find interface declaration for 'RCTEventEmitter'

---

sample-apps/react/react-video-demo/src/App.tsx

Call settings need to be loaded in order to be able to properly apply local device preferences.
Also fixes an issue that prevented overriding the default log level at runtime.

fix(demo): respect server-side settings when applying device settings

---

packages/client/src/Call.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/SpeakerManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/devices/__tests__/InputMediaDeviceManager.test.ts
packages/client/src/devices/__tests__/MicrophoneManager.test.ts
packages/client/src/devices/__tests__/ScreenShareManager.test.ts
packages/client/src/devices/__tests__/SpeakerManager.test.ts
packages/client/src/devices/__tests__/mocks.ts
packages/client/src/devices/devices.ts

This PRs adds the last missing piece to the new device management API: handling device disconnections.
- If a device is disconnected, we deselect that device (not available in RN)
- If a track ends, we update the device manager status to `disabled`
- If the "default" device is replaced, we restart the device (not available in RN)
- If a track ends, we update the device manager status to `disabled`
- If a device is disconnected, we deselect that device (not available in RN)
The `deviceIds$` Observable notifies the manager about device connections/disconnections. This Observable uses `enumerateDevices`, so it will never ask for permissions (we only need to ask for permissions if we need device labels, but we don't need them for watching disconnected devices).
We add the `ended` event …

feat: handle device disconnection

---

sample-apps/react/react-dogfood/pages/api/auth/create-token.ts

SAMPLE_APP configuration is optional for local development, and we can't expect that everyone will have this configuration applied locally.
Because of that, unless `pronto` environment already exists, we will create it with the default STREAM_API_KEY and STREAM_SECRET_KEY credentials.

fix(pronto): ensure `pronto` environment is always initialized

---

packages/client/src/__tests__/server-side/call-types.test.ts
packages/react-sdk/src/core/components/ParticipantView/ParticipantView.tsx
packages/react-sdk/src/core/components/Video/DefaultVideoPlaceholder.tsx
packages/react-sdk/src/core/components/Video/Video.tsx

Allows integrators to disable the rendering of the `VideoPlaceholder` element.

feat(participant-view): allow opting-out from rendering VideoPlaceholder

---

packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts

Prevents duplication of session participants. Reference: https://getstream.slack.com/archives/C040262MY9K/p1701088341598799

fix(session): prevent duplication of session participants

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/01-introduction.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/03-quickstart.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/02-joining-creating-calls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/08-native-permissions.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/10-reactions-and-custom-events.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/core/stream-call.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/participants/participant-view.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/02-replacing-call-controls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/10-network-quality-indicator.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/14-watching-a-livestream.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/02-chat-with-video.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/06-broadcasting.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/duration-badge.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/follower-count.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/host-livestream/host-livestream-controls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/host-livestream/host-livestream-top-view.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/host-livestream/host-start-stream-button.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/live-indicator.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/livestream-layout.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/livestream-media-controls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/viewer-livestream/viewer-leave-stream-button.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/viewer-livestream/viewer-livestream-controls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/ui-components/livestream/viewer-livestream/viewer-livestream-top-view.mdx

Fixed all the broken links in the SDK docs except for:
```
[WARNING] Docusaurus found broken links!
Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
Exhaustive list of all broken links found:
- On source page path = /chat/docs/sdk/reactnative/core/configuring-call-types/:
-> linking to ../../tutorials/video-calling/ (resolved as: /chat/docs/sdk/reactnative/tutorials/video-calling/)
-> linking to ../../tutorials/audio-room/ (resolved as: /chat/docs/sdk/reactnative/tutorials/audio-room/)
-> linking to ../../tutorials/livestream/ (resolved as: /chat/docs/sdk/reactnative/tutorials/livestream/)
-> linking to …
```

docs(react-native): fix broken links

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/Subscriber.ts
packages/client/src/rtc/flows/join.ts
packages/client/src/rtc/signal.ts

Implements Fast Reconnection flow. This should significantly speed up the call drop recovery caused by a network switch.
In case the WebSocket connection interrupts (due to a network switch WiFi -> 5G, or anything else), we'll attempt to re-establish a connection to the existing SFU by reusing the existing credentials and configuration. When this fails, we will attempt a Full Reconnect, and involve the Coordinator in the picture, as we do it today.
This PR is a rebase of #1212 against `main`.

feat: Fast Reconnection

---

packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/participants/floating-participant-view.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/04-ui-components/participants/participant-view.mdx
packages/react-native-sdk/src/components/Participant/FloatingParticipantView/index.tsx
packages/react-native-sdk/src/components/Participant/ParticipantView/ParticipantView.tsx
packages/react-native-sdk/src/components/Participant/ParticipantView/VideoRenderer.tsx

The `objectFit` within the VideoRenderer was not customizable until now. This PR intoduces ability to customize the same.
Eg:
```
const CustomParticipantView = useCallback((props: ParticipantViewProps) => {
return <ParticipantView objectFit="contain" {...props} />;
}, []);
<CallContent
ParticipantView={CustomParticipantView}
/>
```
```
const CustomParticipantView = useCallback((props: ParticipantViewProps) => {
return <ParticipantView objectFit="cover" {...props} />;
}, []);
<CallContent
ParticipantView={CustomParticipantView}
/>
```

feat(react-native): add ability to customize the objectFit for participant view

---

packages/react-sdk/docusaurus/docs/React/02-guides/05-call-types.mdx

Built on top of https://github.com/GetStream/stream-chat-docusaurus-cli/pull/124
Our tutorial links should point to the main website as they live there now.

docs(react): update tutorial links for React

---

packages/react-sdk/src/components/Button/CompositeButton.tsx
packages/react-sdk/src/components/CallControls/CallStatsButton.tsx
packages/react-sdk/src/components/CallControls/ReactionsButton.tsx
packages/react-sdk/src/components/CallControls/RecordCallButton.tsx
packages/react-sdk/src/components/CallControls/ScreenShareButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioOutputButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx
packages/styling/src/Button/Button-layout.scss
packages/styling/src/Button/Button-theme.scss
sample-apps/react/react-dogfood/components/ActiveCall.tsx
sample-apps/react/react-dogfood/components/CallStatsWrapper.tsx
sample-apps/react/react-dogfood/components/Settings/SettingsTabModal.tsx
sample-apps/react/react-dogfood/components/ToggleDeveloperButton.tsx
sample-apps/react/react-dogfood/components/ToggleDocumentationButton.tsx
sample-apps/react/react-dogfood/components/ToggleDualCameraButton.tsx
sample-apps/react/react-dogfood/components/ToggleDualMicButton.tsx
sample-apps/react/react-dogfood/components/ToggleFeedbackButton.tsx
sample-apps/react/react-dogfood/components/ToggleLayoutButton.tsx
sample-apps/react/react-dogfood/components/ToggleMoreOptionsListButton.tsx
sample-apps/react/react-dogfood/components/ToggleParticipantListButton.tsx
sample-apps/react/react-dogfood/components/ToggleParticipantsPreview.tsx
sample-apps/react/react-dogfood/style/Button/Button.scss

🚂 #1194 
Previously, CompositeButton relied on its `children` to be a button themselves. That led to a mismatch between a hover target (the whole CompositeButton) and a click target (e.g. an IconButton passed as `children`).
With this update, CompositeButton renders a `button` element itself. So, you should no longer pass IconButton or TextButton as `children` - just pass an `Icon` or text.
This is a breaking change, since props for CompositeButton have changed.
As a bonus, most of the styling for react-dogfood's DualButton was removed, since it just re-implemented CompositeButton with a slightly different styling.

feat(react-sdk): update CompositeButton layout

---

packages/react-bindings/src/contexts/StreamI18nContext.tsx
packages/react-bindings/src/i18n/StreamI18n.ts
sample-apps/react/react-dogfood/components/CallRecordingsPage/CallRecordingsPage.tsx
sample-apps/react/react-dogfood/context/SettingsContext.tsx
sample-apps/react/react-dogfood/hooks/useLanguage.ts
sample-apps/react/react-dogfood/pages/index.tsx
sample-apps/react/react-dogfood/pages/join/[callId].tsx
sample-apps/react/react-dogfood/pages/leave/[callId].tsx

Currently, `StreamI18nProvider` always sets i18next option `fallbackLng` to false. Instead, we want to be able to configure fallback language.
That comes in handy for react-dogfood, which automatically sets default language to user's navigator language. That means that i18n breaks in this app if user's locale is not one of our supported ones. This is fixed by setting fallback language set to `en`.

feat(react-bindings): allow configuring fallback language

---

.github/workflows/vale-doc-lint.yml
packages/client/docusaurus/docs/javascript/02-guides/05-call-types.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/05-call-types.mdx

Follow-up to #1229. Updates the tutorial links defined in the shared Call Types page for JavaScript and React Native SDKs.

docs(call-types): update tutorial links

---

sample-apps/react/react-dogfood/hooks/useKeyboardShortcuts.ts

This PR fixes the following issues with push-to-talk:
1. Pressing space for push-to-talk conflicted with default browser behavior when there was a focused element on the page (both the focused element and push-to-talk were activated).
2. Pressing space disabled microphone when it was previously manually enabled.
3. Microphone was not always disabled at the end of push-to-talk if you managed to press and let go of the spacebar quickly enough.

feat(react-dogfood): fix push-to-talk behavior

---

sample-apps/react/react-dogfood/public/.well-known/assetlinks.json
sample-apps/react/react-video-demo/public/.well-known/assetlinks.json

Update production signature and link verification for pronto. Pronto will in theory never be accessed from the prod builds because there the ENV switch is disabled, however since the link is present in the build due to the ENV switcher, google tries to verify the links anyway. Unverified links result in not working deeplinking bellow Android 11, that is why we need also to host the prod signature on pronto in order for the other already verified link to work bellow Android 11.

chore(react): Asset links update

---

packages/client/src/Call.ts

The state of the call was previously updated after call listeners were detached. This will create no impact on the state of the call. This PR tends to fix this issue.

fix(ring calls): cancel auto-drop after rejecting a call

---

packages/client/src/StreamSfuClient.ts

Fixes a regression introduced with #1212 where the status of the underlying SFU WebSocket was incorrectly checked.

fix(sfu): ensure SFU WebSocket is closed

---

packages/react-sdk/src/components/CallParticipantsList/CallParticipantListingItem.tsx

Adds event handlers for the [`fullscreenchange`](https://developer.mozilla.org/en-US/docs/Web/API/Element/fullscreenchange_event) event.
Before this, the internal component state didn't update when fullscreen was toggled with keyboard shortcuts.

fix(react-sdk): handle external full-screen toggling

---

packages/react-native-sdk/expo-config-plugin/__tests__/withMainActivity.ts
packages/react-native-sdk/expo-config-plugin/src/withMainActivity.ts

Partially resolves #1231 
Hello,
according to our conversation in #1231 , I'm contributing a fix to add support for Kotlin inside MainActivity which ensures that this config plugin works with Expo SDK 50 and React Native 0.73. I already tested this change with Expo SDK 50 Beta and it worked fine for me, except for instantiating the `StreamVideoClient`, but that's an unrelated issue. 
Let me know if anything else needs to be adjusted.

feat(react-native): add support for kotlin in expo config plugin

---

packages/react-native-sdk/android/build.gradle
packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/02-expo.mdx
packages/react-native-sdk/src/components/Call/CallControls/AcceptCallButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/RejectCallButton.tsx
packages/react-native-sdk/src/utils/StreamVideoRN/index.ts
packages/react-native-sdk/src/utils/getAndroidDefaultRingtoneUrl.ts
packages/react-native-sdk/src/utils/push/android.ts
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/ios/StreamReactNativeVideoSDKSample.xcodeproj/project.pbxproj
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/dogfood/src/screens/Call/JoinCallScreen.tsx
sample-apps/react-native/dogfood/src/utils/setPushConfig.ts
sample-apps/react-native/expo-video-sample/components/CreateRingingCall.tsx
sample-apps/react-native/expo-video-sample/utils/setPushConfig.ts
yarn.lock

For ringing calls, now if no `sound` property for `incomingCallChannel` was passed in `setPushConfig`. We use the default ringtone. 
⚠️ if user already had `incomingCallChannel` set before. A different channel id is needed to be used. Because sounds cannot be changed for an android channel once created. 
Additionally, any ringtone URL can be set in the push config even after setting the initial push config. For example,
```
import { StreamVideoRN } from '@stream-io/video-react-native-sdk';
import NotificationSounds from 'react-native-notification-sounds';
// Retrieve a list of system ringtone sounds
const ringtones = await NotificationSounds.getNotifications('ringtone');
// set the first ringtone as the ringing call sound
StreamVideoRN.updateAndroidIncomingCallChannel({
id: …
```

feat: add android default ringtone as the default ringing sound

---

sample-apps/react/react-dogfood/components/ActiveCallHeader.tsx
sample-apps/react/react-dogfood/helpers/axiosApiTransformers.ts

Adds a new feature flag that enables General Location randomization.
Once enabled, Pronto will send a randomly selected location to our backend.
On larger calls, we want to ensure that participants are assigned to random SFUs around the globe. Hopefully, this will help us detect some edge cases with Cascading.

feat(pronto): Location randomization

---

packages/client/src/Call.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/__tests__/InputMediaDeviceManager.test.ts
packages/client/src/devices/__tests__/MicrophoneManager.test.ts

Adds a parameter to device manager to enable automatically stopping streams when call is left
fixes #1236

feat(client): add stopOnLeave param to device manager

---

packages/react-sdk/src/components/CallControls/ToggleAudioOutputButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx

#1194 introduced a regression in our `<ToggleAudioOutputButton />` and `<ToggleVideoPreviewButton />` and they rendered without their default menus.

fix(react-sdk): add default menus to ToggleAudio and ToggleVideo buttons

---

sample-apps/react/react-dogfood/public/.well-known/assetlinks.json

The Play Store app has package id as `io.getstream.rnvideosample`. The SHA 256 was wrong for the play store app; this has been updated. Also, the SHA 256 for firebase distribution has been added just in case if we plan to continue using it in the future.

feat(react-dogfood): add asset link for react native demo app and dogfood app

---

packages/client/docusaurus/docs/javascript/02-guides/03-call-and-participant-state.mdx
packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/client/src/Call.ts
packages/client/src/devices/SpeakerManager.ts
packages/client/src/devices/__tests__/SpeakerManager.test.ts
packages/client/src/helpers/DynascaleManager.ts
packages/client/src/helpers/__tests__/DynascaleManager.test.ts
packages/client/src/types.ts
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx

Adds new API that allows control over the individual participant's audio output level.
**Example (Plain-JS):**
```typescript
// will set the volume of the participant to 50%
call.speaker.setParticipantVolume(p.sessionId, 0.5);
```
**Example (React):**
```typescript
const { useSpeakerState } = useCallStateHooks();
const { speaker } = useSpeakerState();
// will set the volume of the participant to 50%
speaker.setParticipantVolume(p.sessionId, 0.5);
```

feat(speakers): Participant audio output levels

---

.github/workflows/react-native-workflow.yml

Currently RN sample app deployment runs on all package changes in main
With this PR it only runs on a dogfood path change..
so if we want a app/play store release, we need to make a version change in the dogfood app's package.json and push to main

chore: do not run rn sample app deployment unnecessarily

---

packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx
sample-apps/react-native/dogfood/src/components/MeetingUI.tsx
sample-apps/react-native/dogfood/src/navigators/Call.tsx
sample-apps/react-native/expo-video-sample/app/ringing.tsx
sample-apps/react-native/expo-video-sample/components/MeetingUI.tsx

Currently callcontent component automatically leaves the call on unmount. This is undesired if an integrator wants to keep the call alive, for example only the audio track.. with a minimised call kinda view.. 
this PR removes that behaviour

fix: remove automatic call leave in call content

---

packages/react-native-sdk/src/components/Participant/FloatingParticipantView/index.tsx

This PR fixes the jumping issue when the participant speaks. 
Video after fixing the issue 
https://github.com/GetStream/stream-video-js/assets/39884168/4f7c1a3f-aeed-4e66-93c8-0b3a31625333

fix(react-native): floating participant speaking border jump issue

---

packages/react-native-sdk/src/utils/push/libs/callkeep.ts

Fixes the issue of not being able to import and use `react-native-callkeep` as an optional dependency in the SDK. This bug was introduced in the previous version of the SDK.

fix(react-native): react-native-callkeep optional dependency import issue in SDK

---

.github/workflows/react-native-workflow.yml
packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/client-details.ts
packages/client/src/gen/coordinator/index.ts
packages/client/src/gen/video/sfu/signal_rpc/signal.client.ts
packages/client/src/gen/video/sfu/signal_rpc/signal.ts
packages/client/src/helpers/RNSpeechDetector.ts
packages/client/src/rtc/flows/join.ts
packages/client/src/stats/SfuStatsReporter.ts
packages/client/src/stats/index.ts
packages/client/src/stats/stateStoreStatsReporter.ts
packages/client/src/stats/utils.ts
packages/client/src/store/CallState.ts
packages/react-native-sdk/src/utils/setClientDetails.ts

Integrates the `SendStats` RPC method.
The SDK will now send WebRTC stats on predefined intervals to the currently connected SFU.
These stats will then be aggregated, processed, and displayed on our Dashboard to provide better observability to our customers about important call timeline events.
Notes: this PR replaces #1276

feat: SFU stats reporting

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/__tests__/InputMediaDeviceManagerState.test.ts
packages/client/src/events/call.ts
packages/client/src/events/internal.ts
packages/client/src/store/CallState.ts
packages/client/src/store/stateStore.ts
packages/client/src/types.ts
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

Adds a few bug fixes and improvements to our SDKs:
1. **client**: SFU WS disconnects and reconnects now provide a more accurate reason. This should help us with the debugging.
2. **devices**: relax the constraints around one-time browser permission grants for every browser
3. **state**: under some rare occasions, `call.broadcast_*` might be delivered before the `egress` state is initialized. This resulted in an error (couldn't read property X from undefined). This is now fixed.
4. **react**: #1266 introduced a side-effect in `usePersistDevicePreferences` where the persisted device state was always reset to "off". This is now fixed too.

fix: various bug fixes and improvements

---

packages/video-filters-web/project.json

Fixes a build/release problem where the bundled package version won't match with the one in `package.json`.
Note: this PR is flagged as "breaking!" as I want to release `v0.1.0` of this package.

fix(filters)!: fixes off-by-one version conflict

---

packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/codecs.ts

Chrome 124 introduces a breaking change in how codec preferences are handled. This led to some compatibility issues in our SDK:
```
DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': 
Invalid codec preferences: invalid codec with name "AV1".
DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver':
Invalid codec preferences: invalid codec with name "H264".
```
This PR adjusts the codec selection according to the recommendations listed here:
- https://issues.chromium.org/issues/328396178
- https://groups.google.com/g/discuss-webrtc/c/QS7y-7zR5ok

fix(codecs): Set codec preferences based on receiving capabilities

---

packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/videoLayers.ts

Fixes an issue where the track's bitrate is announced as 0 but in reality it isn't.
Sometimes, the track settings aren't initialized on time and hence, the track dimensions are reported as 0x0 by the browser.
Naturally, we expect 0 bits for encoding these track dimensions. However, once the browser recovers and real track dimensions can be determined, we have already sent the track announcement.
Now, instead of announcing 0 bitrate, we report some default values for each simulcasted track. The actual value would be adjusted by the SFU once the Publisher peer connection begins sending the video tracks.

fix(publisher): ensure initial bitrate is set

---

packages/audio-filters-web/rollup.config.mjs
packages/client/rollup.config.mjs
packages/react-bindings/rollup.config.mjs
packages/react-sdk/rollup.config.mjs
packages/video-filters-web/rollup.config.mjs

Node v22 removes the deprecated `assert` keyword in favor of `with`:
- https://v8.dev/features/import-attributes#deprecation-and-eventual-removal-of-assert

chore: Node v22 compatibility

---

.styles/Vocab/Base/accept.txt
packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts

**Observables emitting primitive values will emit only when the value changes**
`false` -> `false` - the subscribers won't run for the second update as the value didn't change
**updateOrAddParticipant doesn't iterate the participant array twice before updating or adding a participant**
We were iterating the participant array to figure out whether to add a participant or update an existing one. Then, we create a shallow clone of the array and apply the updates. This isn't optimal.
Now, these two operations are merged into one operation.

fix(state): optimized Call State updates

---

packages/react-sdk/src/components/BackgroundFilters/BackgroundFilters.tsx

Fixes a race condition in `canvas.captureStream()` and `resolveFilter()`.
We were resolving the filter too early and discarding the `<canvas>` element too aggressively whenever the track dimensions changed (`key` prop). Upon discarding, the already captured stream was muted and hence, streaming nothing.
Now, these races are fixed by properly synchronizing the order of operations:
1. Obtain the original video stream
2. Render the stream inside a video element
3. Take the correct stream dimensions once playback starts
4. Render the <canvas> element with correct size
5. Resolve the filter promise and let the SDK publish the filtered video stream

fix: synchronize background filter canvas capturing

---

packages/client/src/devices/ScreenShareManager.ts
packages/client/src/devices/__tests__/ScreenShareManager.test.ts
packages/client/src/devices/__tests__/mocks.ts
packages/client/src/events/__tests__/call.test.ts
packages/client/src/gen/coordinator/index.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/videoLayers.ts

Adds support for a `target_resolution` setting on backend screensharing settings.

feat: support target_resolution backend setting for screensharing

---

packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/ios.ts

Fixes 2 bugs:
- android: expo notifcations should not have been checked for android even in ringing mode
- ios: expo notifications should be registered only when non ringing handlers were registered

fix: do not check for expo notifications lib dependency unnecessarily

---

sample-apps/react/react-dogfood/components/Lobby.tsx

Enables `?skip_query=true` config parameter. Once set, the lobby screen will be dismissed after 0.5 seconds and the participant will immediately join the call.

feat(pronto): add skip_lobby url query flag

---

.github/workflows/deploy-react-sample-apps.yml
.github/workflows/docusaurus-javascript-deploy.yml
.github/workflows/docusaurus-react-deploy.yml
.github/workflows/docusaurus-react-native-deploy.yml
.github/workflows/test.yml

Just a quick fix for our workflows, no need to fetch full git history unless it's used for versioning.

chore: don't fetch full git history for CI

---

packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt
packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/util/RingtoneUtil.java
packages/react-native-sdk/src/utils/getAndroidDefaultRingtoneUrl.ts

**Problem**: Some custom ROMs and some Samsung Android 11 devices have quirks around accessing the default ringtone.
**Solution**: Copy the workaround from Signal app by getting it via reflection. And catch it incase its null due to DRM issues.

fix: workaround for samsung device ringtone quirks

---

sample-apps/react/react-dogfood/components/TourPanel/TourSDKOptions.tsx
sample-apps/react/react-dogfood/style/TourPanel.scss
sample-apps/react/react-dogfood/style/layout.scss

1. Add "video calling" and "audio calling" tags
2. Add drop shadow to the tour popup
3. More visible anchor highlights

fix: tour UI

---

packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/05-incoming-and-outcoming-call.mdx

`useCallMembers` import was wrong in the docs, and this PR fixes this

docs: fix outdated import

---

packages/react-native-sdk/src/components/Livestream/index.ts

Adds the missing component export for the `LivestreamPlayer` component. #1373

fix: export the LivestreamPlayer component

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/devices.ts

Improves the error handling for the input devices. 
In some conditions, our Device Manager APIs could throw an unrecoverable error that couldn't be handled anywhere as we weren't propagating it accordingly. Another problem is async observable subscriptions. Currently, there isn't a way for someone to handle errors in those subscriptions. Until we find a better day, I've wrapped them with a try/catch block.

fix: improved input device error handling

---

packages/client/src/rtc/codecs.ts

@oliverlaz let me know that we can solve this chrome 86 issue reported by Serenis: https://getstream.slack.com/archives/C063KAQAWUS/p1717421617466309

fix: join doesn't work on chrome 86

---

packages/audio-filters-web/package.json
packages/audio-filters-web/src/NoiseCancellation.ts
yarn.lock

BREAKING CHANGE: the return value of the `isSupported` method changed from `boolean` to `boolean | Promise<boolean>`

feat!: extend `isSupported` method

---

sample-apps/react/egress-composite/src/ConfigurationContext.tsx
sample-apps/react/egress-composite/src/hooks/useInitializeClient.ts

Enables `debug` level logs by default to our egress-composite app.
The log level can also be updated through the remote configuration injection mechanism.

fix: enable debug level logs for the composite app

---

packages/client/src/Call.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/Subscriber.ts
packages/client/src/rtc/__tests__/Subscriber.test.ts
sample-apps/react/react-dogfood/components/DevMenu.tsx

When networks change, we perform an ICE restart to re-establish connection to the SFU. 
However, when this process fails, the call stays in limbo mode (no tracks are flowing anymore). This is manifested by black tracks on the client's screens.
This PR updates the behavior of the SDK and now, we will perform full reconnect eagerly.
In the future, once we implement the Reconnect v2, this issue will be solved more elegantly.

fix: perform full reconnect if ice restart fails

---

packages/react-sdk/docusaurus/docs/React/10-advanced/06-apply-video-filters.mdx
packages/react-sdk/src/components/BackgroundFilters/BackgroundFilters.tsx
sample-apps/react/react-dogfood/components/Settings/VideoEffects.tsx
sample-apps/react/react-dogfood/pages/guest/join/[guestCallId].tsx
sample-apps/react/react-dogfood/pages/join/[callId].tsx

This prop was not used and didn't affect the filter state. To have no blurring initially, pass any `backgroundFilter` other than `"blur"` to the `BackgroundFiltersProvider`. To have no filters at all, pass `backgroundFilter={undefined}` (default).

fix: remove `isBlurringEnabled` prop

---

packages/client/src/gen/coordinator/index.ts

Updates the OpenAPI schema and introduces Portrait call recording options.
The typical use case is recording calls that consist of clients publishing video from their mobile devices, in portrait mode.
This feature should solve the problem with the extra black bars around the video when recording in landscape mode.

fix: support for portrait mode recording

---

packages/client/docusaurus/docs/javascript/10-advanced/11-session-timers.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/17-session-timers.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/19-session-timers.mdx

Adds an article about Session Timers to our plain JS docs.
Also fixes a couple of issues in existing session timers docs:
1. Typo in call duration
2. Code formatting for RN article
3. Adds a section explaining overriding call settings from the client

docs: add plain js session timers docs

---

packages/react-native-sdk/.gitignore
packages/react-native-sdk/docusaurus/.env
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/01-introduction.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/05-call-types.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/14-watching-a-livestream.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/02-chat-with-video.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/06-broadcasting.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/07-deeplinking.mdx

Our new website added a hyphen for the React Native SDK section:
- before: `https://getstream.io/video/sdk/reactnative`
- after: `https://getstream.io/video/sdk/react-native`
This PR updates the links found in our documentation accordingly. 
More context: https://stream-io.atlassian.net/browse/PBE-4791

docs(react-native): update tutorial links

---

packages/react-sdk/src/core/components/Audio/Audio.tsx
packages/react-sdk/src/core/components/Audio/ParticipantsAudio.tsx
packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx
packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/components/ParticipantView/ParticipantView.tsx
packages/react-sdk/src/core/components/StreamCall/StreamCall.tsx
packages/react-sdk/src/core/components/StreamVideo/StreamVideo.tsx
packages/react-sdk/src/core/components/Video/Video.tsx

Adds `.displayName` property to our core SDK components.
This should make it easier to debug our SDK in production/minified environments.
Context: https://getstream.slack.com/archives/C06CF5TKRGA/p1719396728909279

fix(react): provide displayName for our core components

---

packages/react-sdk/src/components/CallStats/CallStats.tsx

Allows translating stat card labels in the CallStats component.

fix(CallStats): stat card labels translations

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/02-expo.mdx

* inform that its best to test the app on a device rather than simulators/emulators
* removed the unnecessary section of optional peer dependencies since we have a ringing doc seperately
* Instructions on how to ask for permissions.

docs(react-native): add more clarity in installation docs

---

packages/client/src/client-details.ts
packages/client/src/gen/video/sfu/models/models.ts

Reports the Plain-JS SDK version to the SFU.

fix: report the Plain-JS sdk version to the SFU

---

packages/styling/package.json

Bundles the full SCSS sources within the source map. This prevents warnings where some source map loaders fail to find the linked SCSS files when using the `@stream-io/video-react-sdk` NPM package.
- https://sass-lang.com/documentation/cli/dart-sass/#embed-sources

fix: embed scss sources in the source map

---

packages/react-sdk/src/components/CallControls/ToggleAudioOutputButton.tsx

🚂 https://github.com/GetStream/stream-video-js/pull/1363
We missed the audio output button last time we updated the styling for tooltips and media toggles.

fix: align audio output button tooltip with the rest of media toggles

---

packages/client/src/Call.ts

🚂 #1433 
Removes a guard preventing joining left calls.

fix: allow joining left call instances

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

Since the Call object already [applies](https://github.com/GetStream/stream-video-js/blob/main/packages/client/src/Call.ts#L2127) default call settings for media devices, it's not required to also handle them manually in the hook.

fix: remove applying default settings in usePersistedDevicePreferences

---

packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx

The media filters API has been updated in #1415. However, I missed a part of the docs where this changed API is used. This PR fixes the docs.

docs: update media filters API docs

---

packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts

When `call.recording_failed` event is emitted, we should update the call state and notify that the call isn't recorded anymore.

fix: `call.recording_failed` should update the call state

---

sample-apps/react/react-dogfood/components/ClosedCaptions.tsx

This PR introduces a custom hook useDeduplicatedQueue to improve the management of closed captions in both the ClosedCaptions and ClosedCaptionsSidebar components. The changes enhance caption deduplication and provide a more consistent approach to queue handling across components.
Key changes:
- Add useDeduplicatedQueue custom hook
- Refactor ClosedCaptions and ClosedCaptionsSidebar to use the new hook
- Improve caption deduplication logic

fix: refactor ClosedCaptions components with custom queue hook

---

packages/client/src/coordinator/connection/connection.ts

For this code
```
async () => {
try {
await call?.getOrCreate();
} catch (error) {
console.error('Failed to get or create call', error);
}
};
```
Say if WS connect has failed.
**Current behaviour of the log:**
```
Failed to get or create call undefined
```
**Changed behaviour in this PR:**
```
Failed to get or create call [Error: WS connection failed due to blah blah]
```

chore(client): inform WS connect errors

---

sample-apps/react/stream-video-react-tutorial/src/App.tsx

The sample app code used to have confusing comment from the time when credentials were provided in a separate widget in our tutorials. Now we just point to the tutorial which has demo crendentials.

chore: add a note about credentials to sample video calling app

---

packages/client/src/Call.ts

**Behaviour**: 
we should not schedule timeout based rejects if the call had already ended, as BE will respond with 400
**Background**:
`callState.ended_at` represents the last time the call was ended
`callSession.ended_at` represents if the current call session's ended time
**Fix:**
we should not schedule timeout based rejects if `callSession.ended_at`  is present and not based on `callState.ended_at`

fix: do not use ended_at from call state to check ringing validity

---

packages/client/src/gen/coordinator/index.ts
packages/client/src/store/CallState.ts
packages/client/src/store/__tests__/CallState.test.ts

Handlers for the new `call.session_participant_count_updated` event. 
The Coordinator will occasionally deliver this event to all clients, and it will carry the most recent state of:
- `anonymous_participant_count` and
- `participant_count_by_role`
Specs: https://www.notion.so/stream-wiki/Participant-counts-4411743f0b9345c192b243ccc25099a5
The `CallSession` is extended with one extra property `anonymous_participant_count`.
This value and the aggregated value for the regular participant count will be used for populating the `call.state.anonymousParticipantCount` and `call.state.participantCount` accordingly but only when the `callingState` isn't `JOINED`. Once the call is JOINED, these values will be populated from the SFU heart checks.
This enables our `useParticipantCount()` and …

fix: handle session_participant_count_updated event

---

packages/react-native-sdk/docusaurus/docs/reactnative/03-core/02-joining-creating-calls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/03-calling-state-and-lifecycle.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/17-session-timers.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/01-troubleshooting-guide.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/03-ringing.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/06-broadcasting.mdx

This PR fixes a bunch of broken links within the React Native SDK documentation.
As a follow-up to this, we should consolidate the page structure to be the same as for the other SDKs (the `react` one for example). That will come in a followup PR.

docs(react-native): broken links in documentation

---

sample-apps/react/react-dogfood/pages/join/[callId].tsx

Let's test a bit with Pronto before we make #1437 the default SDK behavior.

chore(pronto): default to h264 in Safari

---

packages/client/src/events/__tests__/call.test.ts
packages/client/src/events/call.ts
packages/client/src/events/internal.ts
packages/client/src/store/CallState.ts

Updates the `endedAt` state property when the `callEnded` event arrives.

fix: update state.endedAt after the SFU terminates the call

---

sample-apps/react/react-dogfood/hooks/useNotificationSounds.ts

Beeping is uncomfortable in large calls when many people are joining/leaving the call.
This PR enables beeping only when the participant count is less than 5.

fix: beep only when participantCount is less than five

---

packages/client/src/rtc/__tests__/codecs.test.ts
packages/client/src/rtc/__tests__/mocks/webrtc.mocks.ts
packages/client/src/rtc/codecs.ts

When using `h264` as the preferred codec, we make sure that the baseline profile `42e01f` and `packetization-mode=0` are used to maximize compatibility between browsers and devices.

fix: prioritize h264 baseline profile

---

packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/01-react-native.mdx
packages/react-native-sdk/expo-config-plugin/README.md
packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidPermissions.test.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidManifest.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidPermissions.ts
sample-apps/react-native/dogfood/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/expo-video-sample/android/app/src/main/AndroidManifest.xml

dataSync requires to add a permission. Which makes play store reject the app for review asking for proof. Using shortService means that there is no permission necessary. so its a win-win

fix: replace dataSync with shortService for android foreground service type

---

packages/client/src/Call.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/codecs.ts
packages/client/src/rtc/videoLayers.ts
packages/client/src/types.ts
sample-apps/react/react-dogfood/components/MeetingUI.tsx
sample-apps/react/react-dogfood/helpers/bitrateLookup.ts
sample-apps/react/react-dogfood/pages/join/[callId].tsx

Introduces a new internal API that allows overriding of the target bitrate used for encoding video tracks.
Also, it enables h264 by default in our internal environments. We need to dogfood this codec more.

fix: allow video target bitrate override

---

packages/client/src/devices/InputMediaDeviceManager.ts
sample-apps/react/react-dogfood/components/MeetingUI.tsx

User case:
1. Have a button to leave a call that navigates to a different page
2. Have filters enabled and `BackgroundFiltersProvider` rendered
3. Pressing the "leave" button invokes `call.leave()` which disables devices; it also causes navigation to happen
4. Navigation unmounts `BackgroundFiltersProvider`, which unregisters the current filter, which calls `camera.applySettingsToStream()`
5. Depending on the conditions, `camera.applySettingsToStream()` may re-enable camera
The user ends up with a camera still in use after leaving the call.
Solution: "synchronize" `applySettingsToStream` with enable/disable methods. This way, either the camera will be disabled first, and `applySettingsToStream` does nothing; or `applySettingsToStream` finishes first, but the camera is then safely …

fix: race condition in `applySettingsToStream`

---

packages/react-bindings/project.json
packages/react-native-sdk/project.json
packages/styling/project.json

Enables proper semver version bumps for packages that are stable.

chore: `preMajor: false` for stable packages

---

sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
yarn.lock

It makes it possible to run our dogfood application from XCode 16.
Ref: https://github.com/ivpusic/react-native-image-crop-picker/pull/2068

fix: XCode 16 compatibility

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/rtc/__tests__/Publisher.test.ts
packages/client/src/rtc/__tests__/Subscriber.test.ts

We don't attempt to recover broken WebSockets when there isn't a network connection. Instead, we wait for connectivity to be restored first.
This behavior created some weird bugs with `call.leave()`. As we were creating new WebSockets, the `signalReady` never resolved (the socket couldn't be opened) and hence, `send()` was blocking forever.
Due to this behavior, when attempting to leave a call while offline, the `callingState` never transitioned from `OFFLINE -> LEFT`.
Ref: https://getstream.slack.com/archives/C06H93HC60Z/p1725636744842199?thread_ts=1724334671.814709&cid=C06H93HC60Z

fix: don't attempt to recover broken WebSockets when there isn't a network connection

---

packages/client/src/devices/CameraManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/videoLayers.ts
packages/client/src/types.ts
sample-apps/react/react-dogfood/components/DevMenu.tsx
sample-apps/react/react-dogfood/components/MeetingUI.tsx

Adds experimental APIs for overriding codec, bitrate, and bitrate downscale factor.
Currently, we keep this API internal and undocumented until we get more feedback and more insights from our testing.
In Pronto, these parameters can be overriden via a query parameter:
`?video_codec=h264&bitrate=1200000&bitrate_factor=3` 
- will use h264, with 1.2mbps bitrate, and every lower layer will use 3 times less bitrate than the previous one.

fix: overridable bitrate and bitrate downscale factor

---

packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/connection.ts
packages/client/src/coordinator/connection/utils.ts

Currently for all axios requests, we wait for `connectionIdPromise`. This promise is rejected or resolved based on the first WS connect attempt. If subsequent reconnects were successful but the first connect was rejected, this promise would still stay rejected. 
To allow for reconnects to resolve, say for example, in 3rd try the connection got open, we can wait for the `connectionOpen` promise to resolve. To allow for 2 or 3 retries, we use `_waitForHealthy` function here. Alternatively we  could await only on `connectionOpen` promise without allowing for timeouts to wait for reconnections also.

fix: do not always error out api calls when web socket initially failed

---

packages/client/docusaurus/docs/javascript/02-guides/07-query-call-members.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/07-query-call-members.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/07-query-call-members.mdx

Backend now allows 100 for `members_limit`

docs: update maximum call members to 100

---

packages/client/docusaurus/docs/javascript/02-guides/06-querying-calls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/06-querying-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/06-querying-calls.mdx

Wording fix based on this request in -> [Docs gaps page](https://www.notion.so/stream-wiki/Docs-gaps-4515af280e024c3ab33eb81828bde019?pvs=4#8805b230d1ff4da8820a5be0ef8febd0) 
Changes the header from `Calls that live` to `Calls that are ongoing`.

docs: ongoing calls header wording update

---

packages/react-sdk/package.json
yarn.lock

Add React v17 to the list of supported peer dependencies.

fix: React v17 compatibility

---

packages/react-sdk/docusaurus/docs/React/03-ui-components/core/call-layout.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/13-participant-view-customizations.mdx
packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx
packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/components/ParticipantView/ParticipantView.tsx
packages/react-sdk/src/core/components/Video/Video.tsx

We get a lot of questions about disabling mirroring of local participant video. It's currently possible to do by overriding the `str-video__video--mirror` CSS class, but it seems that things will be easier if we have a prop to control this behavior.
This PR adds an optional `mirrorLocalParticipantVideo` prop to all built-in layout components. Setting it to `false` disable local participant video mirroring.

feat: add a prop to control mirroring of local participant video

---

packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx

Under special circumstances - `excludeLocalParticipant = true` and the screen sharer is the only participant in the call, the participant bar didn't render, which led to an exclusion of the screen sharer's video track.
Context: https://getstream.slack.com/archives/C07KX5D7MFX/p1727981915684569

fix: edge case with participant bar rendering

---

packages/client/src/events/call.ts
packages/client/src/helpers/RNSpeechDetector.ts

* RNSpeechDetector could create multiple audio streams if started multiple times - fixed
* On call ended when on reconnection we did not leave - fixed

fix: mic not fully released in some cases 

---

packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/devices.ts
packages/client/src/helpers/RNSpeechDetector.ts
packages/client/src/rtc/Publisher.ts

track release does the garbage collection of track natively

fix: add track release for react-native whenever track stop is called

---

packages/react-sdk/src/components/CallControls/CallControls.tsx

Adds OwnCapability checks on the Call Control buttons.
They shouldn't be rendered at all when certain user capabilities are not present.
When browser permissions are not granted, and the user doesn't have `send-video` or `send-audio` permissions, the `CallControls` component is still prompting for browser permissions.
The reason for this prompt is - these buttons use `useMicrophoneState()` and `useCameraState()` hooks that trigger these prompts. Fixing this in the buttons component will require a bit of refactoring, so I'm opting for this less ideal and simple fix.

fix: check for user capabilities before rendering call control buttons

---

packages/client/src/compatibility.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts

Our default call types include a default setting for camera direction (user-facing). Having this setting applied by default is useful for mobile devices, but on desktop devices where camera direction reporting is not reliable it leads to confusion, because it can cause a device other than the system default to be used by default.

fix: ignore camera direction for desktop devices

---

packages/react-native-sdk/src/hooks/push/useProcessPushCallEffect.ts
packages/react-native-sdk/src/utils/StreamVideoRN/types.ts
packages/react-native-sdk/src/utils/push/utils.ts

Follow-up to #1434. Allows specifying publish options for calls accepted through Push Notifications config.

fix: allow specifying publish options in PN config

---

packages/client/src/rtc/videoLayers.ts

Fixes an issue where SVC layers weren't announced correctly to the SFU.
Although this is harmless for customers, our internal dashboards may show incorrect data.
Context: https://getstream.slack.com/archives/C04ATV49DU3/p1729242858098099

fix(svc): announce downscaled layers in setPublisher

---

packages/client/src/Call.ts
packages/client/src/events/__tests__/call.test.ts

Rejecting a call which has already been ended results in 400 error from backend. To prevent this error we should not allow `call.reject()` to be called on `call.ended` event.
This PR updates the `call.leave` method to make sure that `reject()` can be invoked inside `leave()` only if the reject input param is set to `true`.
```ts
leave = async ({
reject = false,  // <-- only if this param is explicitly sent with value true
reason = 'user is leaving the call',
}: CallLeaveOptions = {}) => {
```

fix(client): invoke call.reject only when reject param specified 

---

packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/devices/__tests__/InputMediaDeviceManager.test.ts
packages/client/src/devices/devices.ts

Somewhere around Chrome v126 a new behavior was introduced, and the `deviceId: string` constraint when querying `getUserMedia` was no longer respected. The default device was always returned instead.
Using the `deviceId: { exact: string }` constraint seems to solve the issue. However, it also can cause the `OvercontrainedError` exception when device id is not valid. We handle it by falling back to default device in this case.

fix: make device selection by device id exact

---

packages/client/src/devices/BrowserPermission.ts
packages/client/src/devices/devices.ts
packages/react-sdk/src/components/DeviceSettings/DeviceSelector.tsx
packages/react-sdk/src/translations/en.json

This PR fixes a bunch of device selector issues.
In some of our device selector components, we assumed that the first device in the list was the default. This isn't always true. So now, if we don't know what the default device is, we don't mark any device as selected, which is more "honest" behavior.
This PR also ensures that device selectors always fall back to the "Default" option if the current device is not found in the device list (e.g. because of stale persisted device preferences) or the device list is empty (e.g. if there's no browser permission).
Up until version 131 (incl.) there was no way to query camera and microphone permissions with `navigator.permissions.query`. We now assume that permission status is `prompt` in this case, and just try getting user media. If it works, …

fix: various device selector issues

---

packages/react-bindings/src/hooks/callUtilHooks.ts
packages/react-bindings/src/hooks/index.ts
packages/react-sdk/src/components/CallControls/RecordCallButton.tsx
packages/react-sdk/src/components/Notification/RecordingInProgressNotification.tsx
packages/react-sdk/src/hooks/index.ts

Moves the `useToggleCallRecording` hook to `react-bindings` package so it can be used in react-native as well.

fix: move useToggleCallRecording to react-bindings

---

packages/video-filters-web/src/helpers/webglHelper.ts

Adds a `null` guard for the `fenceSync` GL object.

fix: guard against null fenceSync

---

packages/client/src/rtc/Subscriber.ts
packages/client/src/rtc/__tests__/Subscriber.test.ts

Improves the "incoming stream update" flow by changing the order of operations.
When a new MediaStream arrives for a participant, we now immediately store it in the CallState, and later we dispose of the old MediaStream.
This prevents participant video flickering caused by the aggressive `track.stop()`.
As part of this PR, the handlers for Subscriber ICE restarts are removed, as they don't make sense anymore. ICE restarts of the subscriber peer connection are initiated by the SFU through the `subscriberOffer` event.

fix: prevent flickering of participant's video when migrating

---

packages/react-sdk/src/components/BackgroundFilters/BackgroundFilters.tsx

Disabling background filters had an unexpected side-effect of setting background blur level to `high` (since it was our default anyway). To avoid confusion, we now reset background blur level to `undefined`.

fix: reset background blur level when filter is disabled

---

packages/video-filters-web/src/webgl2/resizingStage.ts
packages/video-filters-web/src/webgl2/webgl2Pipeline.ts

Our background filters pipeline has an async part that runs out of band with the rest of the pipeline. Errors originating in this async part (like #1565) were not properly handled, didn't invoke the `onError` callback, and caused unhandled rejection errors in the console.
This PR fixes these issues.

fix: handle async errors in background filters pipeline

---

packages/client/src/Call.ts
packages/react-native-sdk/src/components/Call/CallControls/IncomingCallControls.tsx
packages/react-native-sdk/src/components/Call/CallControls/OutgoingCallControls.tsx
packages/react-native-sdk/src/components/Call/CallControls/RejectCallButton.tsx
packages/react-native-sdk/src/utils/push/internal/utils.ts

Currently, we don't call reject unless `reject: true` is passed on leave(). This was a recent change, so it caused a bug where reject was not called on timeout, decline, and cancel scenarios.
There are four predefined reasons for rejecting the call: 
- `busy` - when the callee is busy and cannot accept the call.
- `decline` - when the callee intentionally declines the call.
- `cancel` - when the caller cancels the call.
- `timeout` - when the **caller** or **callee** rejects the call after `auto_cancel_timeout_ms` or `incoming_call_timeout_ms` accordingly
- Reject is now called on timeout, decline and cancel scenarios. We dont handle `busy` yet. Will be part of Android telecom/callkit alignment I believe. 
- Added reason to reject API call
- `incoming_call_timeout_ms` support has been …

fix: reject was not called on timeout, decline and cancel scenarios

---

packages/react-sdk/src/components/RingingCall/RingingCallControls.tsx

Note: Ideally `CancelCallButton` should have been named generically as `HangupCallButton`, but would be a breaking change so I did not do it here

chore: add reason for cancel call click button

---

packages/client/src/__tests__/StreamVideoClient.test.ts
packages/client/src/coordinator/connection/token_manager.ts

`TokenManager` state was not fully reset on user disconnect: token provider and token type were not reset. For example:
```ts
await client.connectUser({ id: 'jane' }, tokenProvider);
await client.disconnectUser();
await client.connectUser({ type: 'anonymous' });
```
When connecting an anonymous user, token provider from the first connection was still used.
This PR fixes that by fully resetting `TokenManager` on user disconnect.
Fixes #1573.

fix: fully reset token manager on user disconnect

---

packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidManifest.test.ts
packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidPermissions.test.ts
packages/react-native-sdk/expo-config-plugin/src/common/types.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidManifest.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidPermissions.ts
packages/react-native-sdk/package.json
packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/utils/StreamVideoRN/index.ts
packages/react-native-sdk/src/utils/StreamVideoRN/types.ts
packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/libs/notifee.ts
sample-apps/react-native/dogfood/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/expo-video-sample/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/expo-video-sample/app.json
yarn.lock

In Android PiP mode, even though app is in foreground mode. The websockets die and reconnect. Then 10-15 secs after die and reconnect after. This goes on. Its a weird state with seemingly no workaround. The only way is to keep a foreground service in all android platforms.
docs: https://github.com/GetStream/docs-content/pull/22

fix: use foreground service to keep call alive

---

packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/codecs.ts

Continuation of #1581. Reads the available codec info from the RTCRtpSender.

fix: force single codec preference in the SDP

---

sample-apps/react-native/dogfood/src/theme.ts

Fixes the floating participant view size on tablet:
Before: 
After:

fix(design-v2): Bug fixes for iPad reported issues

---

sample-apps/react-native/dogfood/src/components/ActiveCall.tsx

Fixes the PiP mode on Android.
Before:
After:

fix: do not show callTopControls on PiP mode for android

---

packages/react-native-sdk/src/components/Call/Lobby/JoinCallButton.tsx
packages/react-native-sdk/src/translations/en.json
sample-apps/react-native/dogfood/src/components/AuthenticatingProgress.tsx

The problem:
- multiple call join press events on the button caused this error on call join:
Solution:
- after the initial press, Join button is dissabeld showing `'Joining...'` message and prevent subsequent press events on it. 
*This PR also contains fix for the general loading screen background colour.

fix: disable join call button to prevent multiple call joins

---

packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/devices.ts
packages/react-sdk/src/components/DeviceSettings/DeviceSelectorAudio.tsx
packages/react-sdk/src/components/DeviceSettings/DeviceSelectorVideo.tsx
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
packages/react-sdk/src/utilities/callControlHandler.ts

This PR fixes some edge cases around device selection:
Chrome allows requesting user media with device id `default`. For the purposes of the SDK, we treat this device as if it didn't existed, and filter it out of device lists. However, it was still possible to select it manually.
Now device id `default` is filtered out of media requests, so even if it is selected manually, it is replaced with an actual device id when device is unmuted.
Previously, selecting non-existing device (e.g. `call.camera.select('nonsense')`) resulted in the default device being selected. That could be a nasty surprise for a user.
Now, either `select` method will throw (if device is already unmuted) or enabling the device will throw later.
This takes us to the final change:
`onError` callback added to audio and …

fix: cover some device selection edge cases

---

packages/client/src/Call.ts
packages/client/src/events/call.ts
packages/client/src/events/internal.ts
packages/client/src/types.ts

Currently when a ringing call was ended, the reject API fails and then the call is never left! 
This PR fixes that we dont call reject API if call was already ended

fix: ringing calls not being left when ended

---

packages/react-native-sdk/src/components/Call/CallControls/AcceptCallButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/RejectCallButton.tsx
packages/react-native-sdk/src/components/Call/CallLayout/CallParticipantsGrid.tsx
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/dogfood/src/components/ActiveCall.tsx
sample-apps/react-native/dogfood/src/screens/Call/JoinCallScreen.tsx
sample-apps/react-native/dogfood/src/translations/en.json
yarn.lock

- Disables `AcceptCallButton`, `RejectCallButton` and `StartCallButton` after their initial click to prevent unwanted additional press events generated.  
- dominant speaker is shown in PiP mode in Android
- fixes the spotlight layout for tablet devices
- add new npm dep in the dogfood app for checking if the device is a tablet (`react-native-device-info`)

fix: call joining, dominant speaker for pip android, spotlight layout for tablets

---

packages/client/src/devices/BrowserPermission.ts
packages/client/src/devices/devices.ts

Since the `useObservableValue` doesn't re-subscribe to observables after the stream errors, we should avoid erroring in observables unless the error is fatal.
One example is the observable returned by `listDevices()`. Currently, it errors on denied browser permission, and unless you re-subscribe, you won't get updated device list when the permission is granted.
With this change, observable doesn't error and returns an empty list instead.

fix: prevent device list observable from erroring

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts

As per spec
```
When the event is received, you need to ensure there is a WS connection open. If the connection needs to be opened, you also need to call call.get to fetch the latest state of the call object
```
Avoids confusion on support where users logging callingstate inform that they get left before ringing state

fix: avoid call.get in all call.ring events

---

packages/client/generate-timer-worker.sh
packages/client/package.json
packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/timers/worker.build.ts

Dropping the `experimental_` prefix since this feature was confirmed working.
Since the timer worker (introduced in #1557) is not going to be updated too often, we can skip an additional built step and just check in the prebuilt worker.
The "source" file `worker.ts` and the script to generate worker are still there, but they are not used during build.

fix: pre-built timer worker

---

packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx
packages/react-native-sdk/src/components/Participant/FloatingParticipantView/index.tsx

Fixes the customisation option in the `FloatingParticipantView` for a `ParticipantVideoFallback` component. 
```typescript
const customParticipantVideoFallback = () => {
return (
<View
style={[
{
...
backgroundColor: 'orange',
},
]}
>
<View style={{ height: 30, width: 30 }}>
<VideoSlash color={'green'} size={30} />
</View>
</View>
);
};
<FloatingParticipantView
ParticipantVideoFallback={customParticipantVideoFallback}
/>
```

fix(rn-sdk): allow prop component ParticipantVideoFallback in FloatingParticipantView

---

packages/react-native-sdk/.gitignore
packages/react-native-sdk/src/utils/push/ios.ts
packages/react-native-sdk/src/utils/push/libs/firebaseMessaging/index.ts
packages/react-native-sdk/src/utils/push/libs/firebaseMessaging/lib.ts
packages/react-native-sdk/src/utils/push/libs/index.ts
packages/react-native-sdk/src/utils/push/libs/notifee/index.ts
packages/react-native-sdk/src/utils/push/libs/notifee/lib.ts
packages/react-native-sdk/src/utils/push/utils.ts

on commonjs, metro's module resolution has unpredicatable behaviour in a single file,if one of the module is not installed
Solution: move modules that may not be installed into its own file
fixes #1620

fix: metro commonjs issues with optional libs

---

packages/react-native-sdk/src/components/Participant/ParticipantView/SpeechIndicator.tsx

Fixes the imports in the `SpeechIndicator` to break the cyclic imports.

fix(rn): break cyclic dependencies issue

---

sample-apps/react-native/expo-video-sample/app/meeting.tsx

Fixes the error/warning generated when user is leaving a call in our sample expo app. 
```
ERROR  Warning: Cannot update a component (ForwardRef(BaseNavigationContainer)) while rendering a different component (JoinMeetingScreen). To locate the bad setState() call inside JoinMeetingScreen, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
```
The issue was in our JoinMeetingScreen component - it's trying to update state during render.
**Solution**: Move the navigation logic into an effect:

fix(rn-expo): fixes error/warning when the call is left in expo [skip ci]

---

packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/utils/hooks/usePrevious.ts

Lokal reported this crash from an edgecase — Android
Easily reproducible, steps below
1. Create an Outgoing call
2. Put app to background 
3. Make callee accept the call 
4. Crash on caller: cant create foreground service from background 
solution: create the service as soon as outgoing call state arrives

fix:  foreground service cannot be started in background exception

---

packages/client/src/devices/InputMediaDeviceManager.ts

Fixes a regression introduced with #1527 where aggressive muting of screen share tracks (by browsers, when shared content is still) led to flickering.

fix: update mute state only for video track on mobile

---

packages/client/src/StreamSfuClient.ts
packages/client/src/rtc/signal.ts

Make sure we bubble the potential errors coming out of the initial SFU signal server connection establishment.

fix: improved error handling when connecting to an SFU

---

packages/client/src/Call.ts

It's important to reset calling state back to its pre-join state if joining flow fails. We already do this if join request fails, but we also need to do it if SFU connection fails.

fix: restore calling state if SFU connection fails during join

---

packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt

When activity flag is not enabled

fix: pip android crash on activity not enabled

---

packages/react-sdk/src/wrappers/LivestreamPlayer/LivestreamPlayer.tsx

More context: https://linear.app/stream/issue/MAR-238/running-livestream-react-tutorial-causes-error
Fixes:
```
You are using useCallState() outside a Call context. Please wrap your component in <StreamCall /> and provide a "call" instance. Error Component Stack
at LivestreamLayout (@stream-io_video-react-sdk.js?v=757bf647:35805:16)
at StreamCallProvider (@stream-io_video-react-sdk.js?v=757bf647:26471:11)
at LivestreamPlayer (@stream-io_video-react-sdk.js?v=757bf647:36019:11)
at StreamI18nProvider (@stream-io_video-react-sdk.js?v=757bf647:26552:29)
at StreamVideoProvider (@stream-io_video-react-sdk.js?v=757bf647:26579:30)
at StreamVideo (<anonymous>)
at App (<anonymous>)
at div (<anonymous>)
at StreamTheme (@stream-io_video-react-sdk.js?v=757bf647:35523:26)
```

fix(LivestreamPlayer): don't render any component until `call` is ready

---

packages/client/src/Call.ts

Immediately leave ringing call if it was accepted by the same user elsewhere.

fix: leave ringing call if accepted or rejected elsewhere

---

packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/components/CallLayout/hooks.ts
packages/react-sdk/src/core/components/CallLayout/index.ts
packages/react-sdk/src/core/components/CallLayout/partcipantFilter.test.ts
packages/react-sdk/src/utilities/filter.test.ts
packages/react-sdk/src/utilities/filter.ts
sample-apps/react/egress-composite/src/ConfigurationContext.tsx
sample-apps/react/egress-composite/src/components/layouts/PaginatedGrid/PaginatedGrid.tsx
sample-apps/react/egress-composite/src/components/layouts/Spotlight/Spotlight.tsx

This PR adds support for filtering participants using a filter object instead of a predicate. Filter object looks something like this:
```js
// Render video only from pinned participants
// or participants with the role "presenter"
{
$or: [
{ isPinned: true },
{ roles: { $contains: 'presenter' } },
],
}
```
(For more examples of what kinds of operators we allow, see `filters.test.ts`.)
Filtering is supported for a subset of participant properties:
- userId: string
- isSpeaking: boolean
- isDominantSpeaker: boolean
- name: string
- roles: string[]
- isPinned: boolean
`SpeakerLayout` and `PaginatedGridLayout` now accept filter objects in their `filterParticipants` prop:
```jsx
<SpeakerLayout
filterParticipants={{
$or: [
{ roles: { $contains: 'student' } },
{ isPinned: true },
],
}}
/>
``` …

feat: [VID-315] allow filtering participants using filter object

---

packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/videoLayers.ts

Fixes a regression introduced with #1527. 
We must ensure that the `maxBbitrate` value is an integer as otherwise, floating point numbers fail to be serialized when `sfu.SetPublisher()` RPC is invoked, leading to issues where the other participant couldn't see the affected participant's video.

fix: ensures that maxBitrate is an integer

---

packages/react-native-sdk/expo-config-plugin/__tests__/withAppDelegate.test.ts
packages/react-native-sdk/expo-config-plugin/src/withAppDelegate.ts

added the new callkit integration methods in [webrtc](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#callkit) for expo config plugin

fix: add callkit audio methods for expo

---

packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts

Joining can fail due to permission errors, so open FG service only on successful join

fix: open fg service only on a successful join

---

packages/client/src/rtc/BasePeerConnection.ts
packages/client/src/rtc/Publisher.ts

A peer connection may be disposed but a event maybe still being handled..
for example.. say onNegotationNeeded is going on, but leave is called after that is invoked and onNegotationNeeded is not finished, now unrecoverable error function is invoked, which causes a rejoin
this is primarily caused only in RN I think as the peer condition awaits are executing in native thread and not JS thread 
This PR aims to not invoke unrecoverable error callback in peer connections when it is already disposed
additionally removes error logging when peer connection is disposed
fixes #1649 #1618 
Join and immediately leave call, thank you @kristian-mkd

fix: race condition with unrecoverable error handling 

---

packages/react-native-sdk/src/components/Participant/ParticipantView/ParticipantView.tsx
sample-apps/react-native/dogfood/src/components/BottomControlsDrawer.tsx
sample-apps/react-native/dogfood/src/components/ClosedCaptions.tsx

- adds default transparent border to the speaker, so when speaker is active the blue border does not resize the video of the current speaker which previously led to a lot of unnecessary SFU updateSubscriptions requests 
- fixes the closed captions formatting when there are long messages
- fixes the bottom snap point of the controls drawer in the dogfood app

fix: closed captions and speaker border bugfixes

---

packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx

The `muted` prop wasn't handled at all. This PR fixes that.

fix: handle LivestreamLayout muted prop

---

packages/client/src/rtc/BasePeerConnection.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/Publisher.test.ts
packages/client/src/rtc/__tests__/mocks/webrtc.mocks.ts
sample-apps/client/ts-quickstart/package.json
sample-apps/client/ts-quickstart/src/controls.ts
sample-apps/client/ts-quickstart/src/main.ts
sample-apps/client/ts-quickstart/vite.config.ts
yarn.lock

In some circumstances, we were dangling track clones. No data flowed to the SFU, but the browser kept the camera/mic indicators on as there were MediaStreamTrack instances that weren't stopped properly.
Upon disposing of a `Publisher`, we now iterate through all transceivers and we explicitly stop the assigned track.
This PR also fixes another issue that could lead to dangling, unstopped tracks when replacing a track on an existing transceiver.

fix: ensure tracks are stopped when disposing a Publisher

---

packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/Publisher.test.ts

Continuation on #1676. We were still leaking tracks in iOS Safari.
Aggressively keep track of cloned tracks in Publisher and ensure all of them are stopped when it is disposed of.

fix: ensure all tracks are stopped when disposing a Publisher

---

packages/client/src/devices/devices.ts

Browsers react differently to `getUserMedia` requests with constraints that cannot be satisfied. In some cases, Firefox throws a DOMException called `NotFoundError`. We should handle it in the same way we handle over-constrained requests: fallback to default device.

fix: relax device constraints on NotFoundError DOMException

---

packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts

Consider this scenario where as soon as app is opened. User A logged in and then immediately logged off and then user B logs in.
```
1. user A logs in
2. useEffect registers listeners to listen for push
3. user A logs out immediately - listeners are removed
4. apple sends push token now , but SDK is not listening as no user is logged in
5. user B logs in
6. useEffect registers listeners to listen for push
7. apple DOES NOT SEND push token now because it was sent earlier
```
If we look at the voip notification library, if we call registerVoipToken() method, the library sends the JS event for new push token with the last push token that it received.
Now after this in point 7 we will receive a event in JS saying that it received a push token

fix: voip token not able to be got if user switched

---

packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts
packages/react-native-sdk/src/utils/StreamVideoRN/index.ts

Consider this scenario where user A logs out and then user B logs in
1. User B logs in, new event listeners are attached
2. StreamVideo useEffect for A unmounts listeners are removed
3. Now there is no more event listeners
This is fixed by this PR
Additionally: also added a method for clearing logout callbacks

fix: do not remove voip listeners for wrong user

---

packages/react-native-sdk/src/hooks/push/useIosCallKeepEventsSetupEffect.ts
packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts

rarely didDisplayIncomingCall comes after onNotificationReceived completes, this is problematic as per the voipNotification library. We must complete only at the last after all are processed it seems. 
But I dont know what the problem is though. 
Just ensure that JS calls the completion function in all three scenarios
1. Foregrounded app
2. Backgrounded app
3. Killed off app

fix: early completion call on iOS remote notifications

---

.github/workflows/version-and-release.yml

Disables the automatic release process that run after every push to `main`.
We now switch to a more controlled and manual release process. 
**The original criteria remain, every merged PR is considered releasable at any time!**

chore: disable the automated release process

---

packages/react-native-sdk/src/hooks/push/useProcessPushCallEffect.ts

if same cid is reused, since undefined was before the distinct,
a stream such as [cid, undefined, cid] would be [cid] instead of [cid, cid]
This PR fixes it

fix: ios distinct values

---

packages/react-native-sdk/src/components/Call/RingingCallContent/IncomingCall.tsx

This crash happens only on iPads. Atleast in my test. Almost 50% of the time i receive incoming calls. 
Upon deepdive, It is  because the blur is done on background thread always, and when blur starts at a time when push notification is shown, the app goes into a native crash.  Possibly the iOS doesn't allow background thread opening at that point. 
Just removing the action of blur fixes the issue

fix: ios ipad crash in incoming call component

---

packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx
packages/react-native-sdk/src/components/Call/CallControls/CallControls.tsx

`CallControlls` styling issue for landscape mode where the buttons are not properly positioned. 
Before:
After:

fix: callControls styling issue

---

packages/client/src/Call.ts
packages/client/src/helpers/DynascaleManager.ts
sample-apps/react/messenger-clone/src/components/ChannelPreview/ChannelPreview.tsx
yarn.lock

Fixes an issue where reused ringing `call` instances were implicitly marked as `ringing`.
For example:
```ts
await call.get({ ring: true });
await call.leave();
// This is used to mark the `call` instance as `ringing` 
// and set the `callingState` to `RINGING`
await call.get();
```
We don't consider the (past) internal state of the `call` instance when it is reinitialized. This aligns the behavior with the rest of the SDKs.
- https://getstream.slack.com/archives/C07EV8DFMRN/p1740394903388349
Fixes: https://github.com/GetStream/stream-video-js/issues/1561#issuecomment-2662584543

fix: don't implicitly mark calls as `ringing`

---

packages/react-native-sdk/src/hooks/internal/useCallMediaStreamCleanup.ts
packages/react-native-sdk/src/providers/StreamCall/AppStateListener.tsx

In expo dev builds, app weirdly (albiet rarely not all the time) starts with background state when app opens from push notification and then there is no event listener callback when it moves to active again. 
We rely on the initial app start for initial pip mode. This causes a bug in expo where pip mode did not reset to true. 
This PR will fix this bug by simply asking the native module if pip mode is true initially on component mount.
Added debug logs for camera disabling

fix: pip race condition

---

packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx

If call settings are changed on the fly when a call is already joined, then incall manager is started and stopped again. 
InCallmanger mode with "audio" is almost never used by our integrators. Speaker is the default preferred output in any scenario. We should not route to earpiece in video disabled calls by default too. I do not know why this was added.
This behaviour also aligns with other SDKs and also fixes the bug on iOS that audio is lost after start->stop->start

fix: do not stop incall manager on change of audio settings

---

packages/react-sdk/src/components/DeviceSettings/DeviceSelector.tsx
packages/react-sdk/src/components/DeviceSettings/useDeviceListWithDefault.tsx
packages/react-sdk/src/hooks/index.ts
packages/react-sdk/src/hooks/useDeviceList.tsx

As far as we know, there's no reliable way to determine the system's default camera and microphone devices without querying them first-and we shouldn't query the user's media devices unless they're enabled. So we have no way of knowing which camera or microphone device is being used by the browser under the following conditions
1. No device has been explicitly selected by the user (or the previously selected device is no longer available).
2. No device was previously enabled by the user
Previously, in this case, we simply rendered a list of devices with no device selected. This was confusing and looked "broken".
Now we add an explicit "Default" option to the list instead. This option is purely cosmetic: if it's present, it's always selected, so selecting it does nothing; and if a …

fix: add explicit default device option to device selectors

---

packages/client/src/Call.ts

Prevent `reconnecting` state flow when the user is `offline`

fix: prevent reconnecting state when offline

---

packages/client/src/Call.ts

currently, two reconnects after going offline->online is performed
1. one after join axios error catch
2. from network.changed event
This PR keeps only the 2nd one

fix: prevent extra unnecessary reconnect after offline to online

---

packages/client/src/StreamVideoClient.ts
packages/client/src/__tests__/StreamVideoClient.test.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/connection.ts
packages/client/src/coordinator/connection/token_manager.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/coordinator/connection/utils.ts
packages/client/src/devices/CameraManager.ts
sample-apps/client/ts-quickstart/src/main.ts

Adds a retry mechanism for the `client.connectUser()` API.
By default, the SDK will now attempt to establish the initial WebSocket connection up to 5 times.
Once all attempts are exhausted, and are unsuccessful, the `connectUser()` will reject with the last captured error as a rejection reason.
Connection flow can happen in the `StreamVideoClient` constructor, but due to its non-async nature, integrators can't catch and handle these errors. This is a flaw that we introduced early in the development of the SDK and fixing it is a huge breaking change. We need to consider fixing this when we start planning for the v2 release of the SDK.
Until then, a new `onUserConnectError` callback can be provided in the constructor's options that will be invoked once the SDK gives up from retrying. This …

fix: retryable client.connectUser()

---

package.json
packages/client/package.json
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx
sample-apps/react/egress-composite/package.json
sample-apps/react/react-dogfood/components/MobileAppBanner.tsx
sample-apps/react/react-dogfood/next-env.d.ts
sample-apps/react/react-dogfood/next.config.mjs
sample-apps/react/react-dogfood/package.json
sample-apps/react/react-dogfood/pages/auth/signin.tsx
sample-apps/react/react-dogfood/pages/index.tsx
sample-apps/react/react-dogfood/pages/join/[callId].tsx
yarn.lock

Upgrades our Pronto/Dogfooding app to Next 15.2
- Upgrade NextJS
- Upgrade Sentry
- Upgrade some other accompanied dependencies
- Remove the now obsolete `?id=` duplication for our native apps on the demo environment

chore: Upgrade to Next 15.2

---

packages/client/src/devices/BrowserPermission.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/__tests__/mocks.ts
packages/client/src/helpers/concurrency.ts
packages/react-bindings/src/hooks/callStateHooks.ts
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx

Previously there was no way to track if the SDK is currently prompting browser for a device permission. For example:
1. Call has camera enabled by default. User visits the call page for the first time. Browser permission prompt is displayed, but in the meanwhile camera toggle is showing that camera is enabled (because `hasBrowserPermission` is true for `prompt` state, and `optimisticStatus` is `enabled`).
2. Permissions have been reset, and user tries to enable camera. Once again, browser permission prompt is displayed, but in the meanwhile camera toggle is showing that camera is enabled.
We now introduce another permission state apart from `prompt`, `granted` and `denied`: **`prompting`**. This state is in effect while browser prompt is visible, i.e. when permission state is `prompt` and …

fix: add pending browser permission state

---

packages/react-sdk/index.ts

🚂 #1701 
This PR exposes `useDeviceList` which we forgot to export.

fix: expose useDeviceList

---

packages/react-native-sdk/src/hooks/push/useInitAndroidTokenAndRest.ts
packages/react-native-sdk/src/hooks/push/useIosCallkeepWithCallingStateEffect.ts
packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts
packages/react-native-sdk/src/utils/StreamVideoRN/types.ts
packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/libs/expoNotifications.ts
packages/react-native-sdk/src/utils/push/libs/firebaseMessaging/index.ts
packages/react-native-sdk/src/utils/push/setupIosCallKeepEvents.ts
packages/react-native-sdk/src/utils/push/setupIosVoipPushEvents.ts

Currently when only non ringing push is configured and ringing is not. We still check for ringing push deps. This is fixed in this PR. 
Also, on expo when only ringing was configured we still checked for expo-notifications presence. This should not be the case. Also fixed in this PR.
Extra: some logs added for debugging purposes

fix: proper non ringing only push support without ringing libs

---

package.json
yarn.lock

Continuation of #1727. Removes the unused `eslint-plugin-prettier` from the dependency list

chore: clean-up deps

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

Device ids reported by browser are not guaranteed to state the same in between browser sessions or device reconnects. Because of that persisting device preferences based on device id is not always reliable.
In this PR we add a fallback mode to `usePeristedDevicePreferences` hook: if persisted device id is not found, it will try to find device by its label.
We also now save up to three latest device preferences. That allows us to prefer devices that were recently used, even if the most recently used device is no longer available.
`usePeristedDevicePreferences` hook is updated to fall back to device labels if device id is not found.
Using labels requires browser permission, so applying and persisting settings is now postponed until permission is granted (or, more precisely, until devices …

feat: persist device label and fallback to it when device id is not found

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/helpers/promise.ts

Previously, only a single attempt to join the call has been made, and the `join()` method threw immediately if it failed.
This PR adds retry logic for call joining. Be default, we retry 3 times, and then throw.
This PR basically moves previous logic from `join` to `doJoin`, and `join` implements retry logic.
We also add some more safeguards around SFU WS handling:
1. SFU WS is not considered healthy unless `joinResponse` has been received from it. That means if `sfuClient.join()` request fails, the whole client will be recreated next time.
2. We close SFU WS client from client if it the `joinResponse` failed. That prevents us from having an open SFU WS after `call.join()` threw and no longer retries.
This PR also fixed a bug in `promiseWithResolver` implementation, where `isResolved` and …

fix: implement retry logic for call joining process

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

🚂 #1736 
I forgot to also apply enabled/disabled state when applying persisted preference. Currently only device selection is applied.

fix: apply muted state from persisted device preferences

---

packages/client/src/events/__tests__/internal.test.ts
packages/client/src/events/internal.ts
packages/client/src/store/CallState.ts

When the user is kicked-out of the call with a `LIVE_ENDED` reason, we now update the `backstage` call state too.
Without this change, the state says that the call is still "live" when that isn't the case.
ref: https://linear.app/stream/issue/REACT-339/

fix: reset the call state value when "live" ends

---

package.json
packages/react-native-sdk/package.json
yarn.lock

Follow-up to #1734. We didn't clean up `eslint` correctly in the RN SDK package. This PR fixes that.

chore: remove react-native/eslint-config from the RN SDK

---

packages/client/src/devices/MicrophoneManager.ts

Incorrect device could sometimes be picked up for "speaking while muted" detection. E.g. you could have built-in mic selected, but external mic was used when muted.
This is follow-up to #1538: since selecting device without `exact` basically means nothing in modern Chrome (always leads to Chrome's default device being used), we must get device with `exact` for "speaking while muted" detection.

fix: pick correct device for speaking while muted detection

---

packages/react-sdk/src/core/components/CallLayout/hooks.ts

Adds to new properties you can filter participants on when using filter object: `hasAudio` and `hasVideo`.

fix: allow filtering participants on hasAudio/hasVideo

---

sample-apps/react/react-dogfood/components/Inspector/Inspector.tsx
sample-apps/react/react-dogfood/components/Inspector/MediaInspectorBookmarkletDash.tsx
sample-apps/react/react-dogfood/style/Inspector.scss

Since monkey-patching `getUserMedia` is out favorite way of debugging anyway, adding a bookmarklet we can share with customers to help them debug why camera or microphone are in use.
Running bookmarklet adds global `_inspectMedia` function, and starts tracking `getUserMedia()` calls.
At any point, call `_inspectMedia()` to get a list of media streams returned by `getUserMedia()`. Each stream is marked live (which means device is in use) or ended.
Every record in `_inspectMedia()` output has a `trace()` method. Call it to get a stack trace showing where the origin `getUserMedia()` call originated.

feat: add media inspector bookmarklet

---

packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts
packages/react-native-sdk/src/utils/push/android.ts

When switching a `user` by reusing the same `client` instance, we should also send the existing device token to our backend as otherwise, the device remains registered to the old `user` until the new one restarts the app.
This PR also fixes another issue - we shouldn't send device tokens to anonymous users.
Ref: https://linear.app/stream/issue/RN-189/video-update-device-token-when-switching-a-user

fix: send device token when switching user

---

packages/react-sdk/src/core/components/CallLayout/index.ts
sample-apps/react/egress-composite/src/components/layouts/DominantSpeaker/DominantSpeaker.tsx
sample-apps/react/egress-composite/src/components/layouts/DominantSpeaker/useSpotlightParticipant.ts

We didn't expect previously that using participant filter with `single-participant` layout would make sense. Turns out, there's a good use case for this: ensuring that RTMP participant always stays visible in the recording, even if somebody else is speaking.
This PR adds support for `participant.filter` configuration option for `single-participant` layout.
Participant list is now filtered before spotlight participant is determined: see the `useSpotlightParticipant` hook.
This change doesn't affect the layout used for calls with ongoing screenshare: the screensharing participant is always in spotlight in this case.

fix: participant filter for `single-participant` layout in egress app

---

packages/react-native-sdk/expo-config-plugin/src/withAppDelegate.ts
sample-apps/react-native/dogfood/ios/StreamReactNativeVideoSDKSample/AppDelegate.mm

Our built-in expo plugin creates a possible race condition that makes some voip notifications on iOS to remain unprocessed.
This PR fixes that and aligns the implementation of that plugin with the implementation we have in our dogfooding app.
🎫 Ticket: https://linear.app/stream/issue/RN-190/
📑 Docs: https://github.com/GetStream/docs-content/pull/287

fix: race condition on Expo iOS when processing incoming voip push notification

---

packages/client/src/Call.ts
packages/client/src/StreamVideoClient.ts

We introduced a bug in #1433 that prevented `call` instances returned by `client.queryCalls` from automatically updating their `state` when the `watch: true` flag is provided.
The event handler for `all` events was moved outside the Call's constructor, causing this bug.
- Marks the `call.setup()` as an `@internal` method
- Every `call` instance is automatically set when `watch` mode is set to `true`
🎫 Ticket: https://linear.app/stream/issue/REACT-358/

fix: watched calls should auto-subscribe for state updates

---

packages/react-bindings/src/hooks/callStateHooks.ts
packages/react-sdk/src/core/components/CallLayout/PipLayout.tsx
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
packages/styling/src/CallLayout/PipLayout-layout.scss
packages/styling/src/CallLayout/PipLayout-theme.scss
packages/styling/src/CallLayout/index.scss

Previously, rendering call state hooks like `useCameraState` and `useMicrophoneState` triggered permission prompt. That happened because these hooks access device list.
Some customers rightly find this confusing: rendering `useCameraState` doesn't necessarily mean you are going to access device list.
Now, device list is accessed only when the `devices` property returned by the hook is really read. If it is not read, no permission prompt will be triggered by the hook.
The `devices` property is now a getter that forces component update when accessed for the first time. Most of the times it will happen during render, which is OK.
> **Note**
> 
> There's one edge case when updating state from getter will not work: that is, if you save hook value to a variable (`const state = …

fix: access device list lazily from call state hook

---

sample-apps/react-native/expo-video-sample/app.json
sample-apps/react-native/expo-video-sample/components/MeetingUI.tsx

This PR fixes pip issues in the expo sample app. when the app goes in pip mode only black screen was presented instead of the participant video.
Adds missing pip configuration in the `app.json` and missing prop in the `CallContent` component 
🎫 Ticket: https://linear.app/stream/issue/RN-193/picture-in-picture-fix-for-expo-sample-app

chore: fix the expo sample app pip mode

---

packages/client/src/devices/BrowserPermission.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/__tests__/mocks.ts
packages/client/src/stats/SfuStatsReporter.ts

Some time ago we introduced device reporting in call stats (https://github.com/GetStream/stream-video-js/pull/1533).
The unexpected side effect of this is that stats reporter now tries to list available devices every time the call is joined, even if camera and mic are off by default, causing permission prompt to appear.
This PR fixes that: stats reporter will never cause a permission prompt to appear.
The condition for listing devices was:
1. User has capability to send audio or video
2. Device permission was not explicitly denied (this condition comes from the `hasBrowserPermission$` observable, which is only false if permission state is `denied`)
This PR adds `browserPermissionState$` observable to input device manager, which provides more granular visibility into current permission …

fix: use more granular permission state for stats reporter

---

packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/utils/push/android.ts

Sometimes this happens
```
when A initiates a call to B and then A cancels the call but the notification has already reached B and the notification is not cleared at B’s side.
```
Technically, this happens when StreamCall is mounted after Foreground service for incoming call. This overwrites the foreground service responsible for listening to call cancellation.
In this PR, we delay the foreground service setting for keep call alive only when call is joined so that we dont overwrite the foreground service.
🎫 Ticket: https://linear.app/stream/issue/RN-198/notification-not-cleared-on-call-cancellation-sometimes-android
📑 Docs: NA

fix: call cancellation not reliably seen on killed state RN-198

---

packages/client/src/Call.ts
packages/client/src/__tests__/Call.autodrop.test.ts
packages/client/src/events/__tests__/call.test.ts
packages/client/src/events/call.ts
packages/client/src/events/internal.ts
packages/client/src/store/stateStore.ts
packages/client/src/types.ts

When auto dropping calls the client sent `decline` instead of `timeout` reason
The `reason` field previously was misused, instead of sending it coordinator, we sent it as a log message to SFU. Now `reason` is sent to coordinator, and a new field is introduced - `message` - to send to SFU.
I checked and all UI SDKs use the `reason` field correctly - so no changes were required there.
🎫 Ticket: https://linear.app/stream/issue/REACT-363/fix-call-rejection-reasons-in-js-client-for-timeout-scenarios
📑 Docs: N/A

fix: use timeout reason when auto-dropping calls (instead of decline)

---

packages/client/src/gen/coordinator/index.ts

Adds the missing 4k enumeration options.
🎫 Ticket: https://linear.app/stream/issue/VID-544/

fix: add options for 4K RTMP and Recording

---

packages/react-native-sdk/package.json
packages/video-filters-react-native/package.json
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/expo-video-sample/package.json
sample-apps/react-native/ringing-tutorial/package.json
yarn.lock

Bumps `@stream-io/react-native-webrtc` to the latest stable version.

chore: update sample apps to webrtc-125.2.0

---

packages/client/src/devices/CameraManager.ts

While optimizing the `camera.flip()` API in #1679, we introduced a regression that led to `camera.flip()` throwing a `NotReadableError` on devices with limited hardware capabilities.
Some devices are unable to provide two `MediaStream` instances at the same time.
We want to preserve the `camera.flip()` optimizations as they allow significantly faster direction change. 
We always attempt to perform a fast direction change, but if it fails, we fall back to:
`stop()` -> `flip()` -> `start()` flow, which is slower, but it works.
🎫 Ticket: https://linear.app/stream/issue/REACT-367/

fix: make camera.flip() work more reliably with older devices

---

sample-apps/react-native/dogfood/src/components/BottomControlsDrawer.tsx

The actions inside of the more actions bottom drawer component were not working as expected. On press event on any of them the drawer was closed without firing the expected action. 
The pan responder is only attached to the drag indicator instead of the entire `Animated.View`. This way, the buttons will receive their own touch events.
🎫 Ticket: https://linear.app/stream/issue/RN-207/fix-dogfood-bottom-drawer-component-issue
📑 Docs: 🚫

fix(rn-dogfood): more actions bottom drawer pressable issues

---

packages/client/src/events/__tests__/call.test.ts
packages/client/src/events/call.ts

When the `callEnded` event was received by the SFU, we weren't properly checking the `reason` field, and we were aggressively leaving the call.
This isn't the expected behavior for hosts who enter backstage and have permission to join the backstage.

fix: graceful handling of LIVE_ENDED CallEnded reason

---

packages/react-native-sdk/ios/StreamVideoReactNative.m

Compiler skips the else clause in the pragma in our dogfood and expo since we use new arch. So we missed this.

fix: ios compilation error on old arch

---

sample-apps/react/react-dogfood/pages/bare/join/[callId].tsx
sample-apps/react/react-dogfood/style/CallControls/CallControls-layout.scss

For testing purposes in a lighter environment, we expose a `/bare/join/<call-id>` route that removes all "nice to have features" and focuses only on SDK components.

feat(pronto): bare-bones SDK integration

---

packages/audio-filters-web/project.json
packages/client/project.json
packages/react-bindings/project.json
packages/react-native-sdk/project.json
packages/react-sdk/project.json
packages/styling/project.json
packages/video-filters-react-native/project.json
packages/video-filters-web/project.json

Allows `chore` releases to perform version bump of the SDK packages.

fix: enable chore releases

---

packages/client/src/devices/InputMediaDeviceManager.ts

It's a possible fix for the issue when there's no audio coming out out from the noise cancellation audio context.
Our filter pipeline setup is async, so we should be careful not to mutate anything filter-related while the pipeline is being set up. Even if it's not a root cause of the problem described above, it can still lead to weird consequences.

fix: do not mutate filters array during pipeline setup

---

packages/client/src/devices/MicrophoneManager.ts

Restores the `echoCancellation` settings introduced in #1794

fix: restore echoCancellation settings

---

sample-apps/react-native/dogfood/App.tsx
sample-apps/react-native/dogfood/src/navigators/Call.tsx

In df app, we watched ringing calls only when the app mode was set to calling. With this change, we also watch whatever mode it is. 
So that even when df app is killed off, it navigates properly even if meeting was used before.

chore(rn-dogfood): watch ringing calls on all screens

---

packages/client/src/rpc/__tests__/createClient.test.ts
packages/client/src/rpc/createClient.ts
packages/client/src/rpc/retryable.ts

When an error happens while processing an RPC, our SFU returns an HTTP 200 status and a response body with an `error` object. This is a bit of non-standard behavior that we can't fix without breaking the existing API.
This means that data errors will never throw an error, and hence, making our try/catch interceptor useless in some circumstances.
In this PR, we unwrap the response in the interceptor (asynchronously) and inspect its content.

fix: rpc error tracing

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

Apply persisted device settings sequentially and one by one, in an attempt to fix a regression/race condition with audio when using noise cancellation.

fix: sequential uPDP

---

sample-apps/react/react-dogfood/helpers/axiosApiTransformers.ts

Allows enabling or disabling location randomization through the `?random_location=true|false` query parameter.

feat: overridable location randomization

---

packages/audio-filters-web/src/NoiseCancellation.ts
packages/audio-filters-web/src/tracer.ts
packages/react-sdk/src/components/NoiseCancellation/NoiseCancellationProvider.tsx

Adds tracing for Noise Cancellation AudioContext state.
Since starting AudioContext requires user interaction, it's possible that some integrations can experience audio issues when using noise cancellation because AudioContext is suspended. This trace should help discover these issues.

fix: add audio context state tracing

---

packages/audio-filters-web/src/NoiseCancellation.ts
packages/client/package.json
packages/client/src/Call.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/helpers/DynascaleManager.ts
packages/client/src/helpers/__tests__/DynascaleManager.test.ts
packages/client/src/rtc/__tests__/mocks/webrtc.mocks.ts
packages/client/src/store/CallState.ts
packages/noise-cancellation-react-native/src/index.ts
packages/noise-cancellation-react-native/src/types.ts
packages/react-bindings/src/hooks/callStateHooks.ts
packages/react-sdk/src/core/components/Audio/Audio.tsx
packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx
packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/PipLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/components/CallLayout/hooks.ts
sample-apps/react/react-dogfood/helpers/logger.ts
yarn.lock

Safari's power-management and autoplay policy do not allow a tab to start playing audio through an `<audio />` element when the user doesn't have the tab in focus. This behavior causes an issue where a remote participant can't be heard until the local participant focuses on the tab that has the ongoing call.
Steps to reproduce:
- The local participant switches to a different tab
- The remote participant mutes and unmutes while the local participant is browsing on a different tab
- The remote participant becomes audible only after the local participant switches back to the call tab
- Uses `AudioContext` for Safari, as it doesn't seem to be restricted by the above-mentioned policies
- The rendered `audio` elements are now muted by default on Safari, as we want to prevent "double audio"
- …

fix: use AudioContext for Safari

---

packages/client/src/coordinator/connection/token_manager.ts

When `loadToken` rejects because of an error originating in `tokenProvider`, the original error is hidden behind this new error. That makes debugging the problem more difficult.
We now attach original error as a `cause` to the rejection error.
Error monitoring services like Sentry will also show show call stack and message from `Error.prototype.cause`.

fix: attach original token provider error as cause to loadToken rejection

---

packages/client/src/StreamSfuClient.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/devices.ts
packages/client/src/rtc/__tests__/videoLayers.test.ts
packages/client/src/rtc/videoLayers.ts
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx

Improves the video quality on low capture resolution.
When capturing with relatively low resolution (640x480), we were too aggressively downscaling the `q` layer to 160x120. 
Although this looks good in a grid layout with small tiles, it creates quite a pixelated video on 1:1 calls.
In this PR, we reduce the aggressiveness and downscale to 320x240 - a resolution that looks sharper on smaller tiles and improves the pixelation.
This PR also fixes an issue with our implicit requirement that `target_resolution` must be in _landscape_ format.
Adds more telemetry data tracing, too.
🎫 Ticket: https://linear.app/stream/issue/RN-224

fix: improved video quality on low capture resolution

---

packages/react-sdk/src/wrappers/LivestreamPlayer/LivestreamPlayer.tsx

Fix a typo that led to a bug with early join flow in `LivestreamPlayer` wrapper.

fix: early join in LivestreamPlayer

---

packages/styling/src/Button/Button-layout.scss

Our call controls was broken for RTL direction locales. This PR fixes it.
Before:
After:
We had some styles using `*-left` and `*-right` properties. They are now replaced with logical `*-inline-start` and `*-inline-end`.
🎫 Ticket: https://linear.app/stream/issue/REACT-425/update-ui-margins-for-better-rtl-ui-experience

fix: RTL layout for call controls

---

packages/react-sdk/src/components/Button/CompositeButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
sample-apps/react/react-dogfood/components/Lobby.tsx

Fixes device selection menu missing by default in `ToggleAudioPreviewButton`.

fix: default menu for ToggleAudioPreviewButton

---

packages/client/src/Call.ts
packages/client/src/devices/CameraManagerState.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/ScreenShareManager.ts
packages/client/src/devices/SpeakerManager.ts

We had a discrepancy in how device managers were created and disposed.
Device manager is created in Call constructor, and is available for the whole lifetime of the call instance.
When created, device manager also sets up some subscriptions. Some of these subscriptions only really work within a fully initialized call (after `call.get()`, `call.join()` etc). Some, like `handleDisconnectedOrReplacedDevices` are nice to have even if the call is not initialized.
When leaving call, all subscriptions are removed in the device manager's `dispose()` method. However, the call can be joined again after leaving, and device manager subscriptions were not set up again in this case.
This PR fixes that by setting up device manager subscriptions again when the call is initialized again after leaving. …

fix: correctly setup and dispose device managers

---

packages/react-native-sdk/src/components/Participant/ParticipantView/ParticipantView.tsx

Before             |  After
:-------------------------:|:-------------------------:
Our SDK by default already treats landscape video as contain, portrait as cover. And that is now applied to callcontent by default
🎫 Ticket: https://getstream.zendesk.com/agent/tickets/67391

fix: do not have a default for objectfit

---

packages/client/src/StreamSfuClient.ts

Follow-up to #1846. `call.leave()` throws an error after unrecoverable FAST reconnect.
Our "leave" flow requires the client to announce its disconnect from the call to the SFU so the SFU can perform certain state cleanups faster. However, in the case described above, this isn't possible because the new SFU client never successfully connected to the SFU, and the signal WS was never established. This makes it impossible to send the announcement.
This PR adds better error handling and doesn't prevent the `call` instance disposal.
🎫 Ticket: https://linear.app/stream/issue/RN-241/refresh-call-state-after-a-failed-reconnect

fix: relax SFU leaveAndClose constraints

---

packages/client/src/coordinator/connection/connection.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/SpeakerManager.ts
packages/client/src/devices/devices.ts
packages/client/src/helpers/lazy.ts
packages/client/src/stats/rtc/Tracer.ts
packages/client/src/stats/rtc/types.ts
packages/react-native-sdk/src/providers/StreamCall/DeviceStats.tsx

Adds the list of available devices to the trace log.

fix: trace available devices and thermal state changes

---

packages/react-native-sdk/expo-config-plugin/src/withMainActivity.ts
sample-apps/react-native/dogfood/android/app/src/main/java/io/getstream/rnvideosample/MainActivity.kt

We have found that in some OEM implementations of Android, they will finish the activity then call onPictureInPictureModeChanged, causing a race condition
This PR adds a way to work around this on the expo plugin level and dogfood 
📑 Docs: https://github.com/GetStream/docs-content/pull/496

fix: android OEM specific pip crash

---

sample-apps/react/react-dogfood/helpers/client.ts
sample-apps/react/react-dogfood/pages/index.tsx
sample-apps/react/react-dogfood/pages/join/[callId].tsx

Allows one to specify `use_local_coordinator` and `coordinator_url` query params in Pronto for easier end-to-end development without running Pronto locally.

chore: support connecting to any coordinator instance

---

packages/react-native-sdk/ios/RTCViewPip.swift
packages/react-native-sdk/ios/RTCViewPipManager.swift
sample-apps/react-native/dogfood/ios/Podfile.lock

* Guarenteed way to cleanup after view is unmounted
* reverts #1854 as now there is a guarenteed and also that PR caused the cached property to hold a strong reference and so deinit was never called. 
uses `didMoveToSuperview` instead of  `didMoveToWindow` to ensure cleanup is always done on unmount
Here is Gemini 2.5 explanation of why to prefer didMoveToSuperView
```
Potential pitfalls for "unmounting" detection via didMoveToWindow in RN:
1. View removed from superview, but parent not in a window: If a view is removed from a superview, and that superview (or its ancestor) was never actually added to a window, didMoveToWindow might not have been called with a nil window because the view never had a non-nil window to begin with.
2. Container view removed: If you have a complex view …
```

fix: iOS PiP cleanup

---

sample-apps/react/react-dogfood/components/Lobby.tsx
sample-apps/react/react-dogfood/lib/getServerSideCredentialsProps.ts

Default to the `user_id` query param value when "Display Name" can't be otherwise determined.

chore: prefill displayName with user_id query param

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
sample-apps/react/react-dogfood/components/Lobby.tsx

When the camera is disabled on a call type level, we should completely discard any previously stored camera preferences.
Also, we shouldn't prompt for permission (caused by the device listing).

fix(uPDP): respect call type camera configuration

---

Dockerfile
docker-compose.yml
packages/react-sdk/src/components/BackgroundFilters/BackgroundFilters.tsx
sample-apps/react/egress-composite/package.json
yarn.lock

Related to: https://github.com/facebook/react/issues/14035
To ensure that CORS headers are properly set, we need to apply the `crossorigin` attribute before we apply the `src` one.

fix: apply the crossorigin attribute before applying src

---

packages/client/src/StreamVideoClient.ts
packages/client/src/__tests__/StreamVideoClient.ringing.test.ts
packages/client/src/__tests__/clientTestUtils.ts
packages/client/src/__tests__/data.ts
packages/client/src/helpers/__tests__/clientUtils.test.ts
packages/client/src/helpers/clientUtils.ts
packages/client/src/store/stateStore.ts
sample-apps/react/react-dogfood/components/Ringing/DialerPage.tsx

The order of `call.created` and `call.ringing` can't be guaranteed. Until now, the SDK assumed that `call.created` would arrive first, but we've seen that's not always the case.
When the order was flipped, the SDK had a race condition that made the `ringing` call be created in `non-ringing` mode, causing unexpected integration issues.
This PR unifies the handling of both events and correctly synchronizes the access to them.
Also, adds a few tests so future regressions are prevented.
This PR also fixes a bug in our Pronto ringing integration. The caller should always be included in the `members` array.
TODO: There is one failing test, which I believe is a backend bug. I'm waiting on our BE team's feedback.
🎫 Ticket: https://linear.app/stream/issue/REACT-528/synchronize-callring-events

fix: synchronize ring events

---

packages/react-sdk/src/components/CallParticipantsList/CallParticipantsList.tsx
packages/react-sdk/src/components/Search/hooks/useSearch.ts

Prevents CallParticipantList results from flickering when the `participants` array dynamically updates while searching

fix(CallParticipantList): prevent search results from flickering

---

packages/styling/src/Button/Button-layout.scss

Fixes layout shift when call control (such as `RecordingButton`) is in loading state.

fix: layout shift when call control is in loading state

---

packages/react-sdk/src/core/components/CallLayout/LivestreamLayout.tsx

Handles the enter/exit full-screen functionality more gracefully. Takes the browser's initial state into consideration, and relies on browser events to maintain the correct state.
Fixes: #1915

fix(LivestreamLayout): handle enter/exit fullscreen gracefully

---

packages/react-sdk/src/components/CallParticipantsList/CallParticipantsList.tsx

Leftover label that couldn't be translated to a different language.

fix: make `mute all` label translatable

---

packages/noise-cancellation-react-native/android/build.gradle

Switches to a "stable" release channel for our `stream-video-android-noise-cancellation` Kotlin 1.9.25 flavor.

fix(nc): switch to a stable version channel

---

packages/react-native-sdk/ios/PictureInPicture/StreamPictureInPictureController.swift
packages/react-native-sdk/ios/RTCViewPip.swift
packages/react-native-sdk/ios/RTCViewPipManager.mm
packages/react-native-sdk/src/components/Call/CallContent/CallContent.tsx
packages/react-native-sdk/src/components/Call/CallContent/RTCViewPipIOS.tsx
packages/react-native-sdk/src/components/Call/CallContent/RTCViewPipNative.tsx
packages/react-native-sdk/src/hooks/useIsInPiPMode.tsx
packages/react-native-sdk/src/providers/StreamCall/AppStateListener.tsx
packages/react-native-sdk/src/utils/internal/rxSubjects.ts
sample-apps/react-native/dogfood/ios/Podfile.lock

useIsInPiPMode only worked for Android. But with this change also works for iOS.  Can be used for analytics in iOS. 
Added an `onPiPStateChange` closure to `StreamPictureInPictureController.swift`, which is called when PiP starts or stops, enabling notification of PiP state changes from native code

fix: add useIsInPiPMode for ios

---

sample-apps/react/react-dogfood/helpers/gong.ts

Fixes an edge case in Gong's integration
```
Could not upload recording for call default:m7mwRh24OfNweGN8G2Lay {
requestId: '1tg8hsly8vytebs7xlw',
errors: [
'parties[4]: non company party must include at least 1 identification information'
]
}
```

fix: fallback to user_id when user.name is missing
