.github/workflows/deploy-sample-apps.yml
sample-apps/react/react-video-demo/src/components/LatencyMap/LatencyMap.tsx

Add secrets and vars that are needed
Update  latency map key, remove old key

feat: update sample app deployment workflow

---

sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.module.css
sample-apps/react/react-video-demo/src/components/Meeting/Meeting.module.css

- set min height of call panel

fix: fix tour place ment to be in the meeting screen

---

packages/react-dogfood/components/Stage.tsx

Fixes a layout issue with Speaker view introduced with #383

fix: revert previous "stage" implementation

---

sample-apps/react/react-video-demo/package.json
sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/utils/useGenerateUser.ts
yarn.lock

- Allow a token and a random user name per user to be generated before user connects to the chat.

feat: generate user tokens

---

packages/client/src/rtc/flows/join.ts

Introduces a feature `cascading` feature flag. 
Once enabled, the backend will receive the `?cascading=true` query parameter in the `call/{type}/{id}/join` endpoint. In addition to `cascading` all remaining query parameters will be forwarded too (if any). This will enable adding more cascading config parameters in a generic way.

feat: cascading feature flag

---

packages/client/src/rtc/flows/join.ts

window.location.search safe check

---

sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/Footer/Footer.module.css
sample-apps/react/react-video-demo/src/components/Footer/Footer.tsx
sample-apps/react/react-video-demo/src/components/Header/Header.tsx
sample-apps/react/react-video-demo/src/components/Layout/MeetingLayout/MeetingLayout.tsx
sample-apps/react/react-video-demo/src/components/Meeting/Meeting.tsx
sample-apps/react/react-video-demo/src/components/Sidebar/Sidebar.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx
sample-apps/react/react-video-demo/src/contexts/PanelContext.tsx

- Move panel toggles to context
- Add breakpoint check to context for mobile view
- Remove all old ways of toggeling the panels

feat: panel context

---

packages/client/docusaurus/docs/client/05-advanced/03-permissions-and-capabilities.mdx
packages/client/src/rtc/Call.ts
packages/client/src/rtc/helpers/tracks.ts

Adds the initial docs for the `Permissions and Capabilities` chapter.

feat: initial docs for permissions and capabilities

---

packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/connection.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/gen/coordinator/index.ts

See the video-push-devices branch on the backend

Adds support for tracking push devices

---

packages/client/src/StreamVideoClient.ts
packages/client/src/rtc/Call.ts
packages/client/src/store/stateStore.ts

Fixes an issue where watched calls stop receiving updates from the backend after a connection drop.
The client now keeps track of "watched" calls and sets up a `connection.changed` event listener. Whenever the client goes "online" again, it checks the tracked calls and re-subscribes new call watchers on the backend.

fix: restore call watchers after a connection drop

---

sample-apps/react/react-video-demo/src/components/Chat/Chat.module.css
sample-apps/react/react-video-demo/src/components/Footer/Footer.module.css
sample-apps/react/react-video-demo/src/components/Footer/Footer.tsx
sample-apps/react/react-video-demo/src/components/Icons/Icons.module.css
sample-apps/react/react-video-demo/src/components/Icons/Like.tsx
sample-apps/react/react-video-demo/src/components/Icons/index.ts
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.module.css
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx
sample-apps/react/react-video-demo/src/components/Panel/Panel.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantsPanel.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantsPanel.tsx
sample-apps/react/react-video-demo/src/components/ReactionsPanel/ReactionsPanel.module.css
sample-apps/react/react-video-demo/src/components/ReactionsPanel/ReactionsPanel.tsx
sample-apps/react/react-video-demo/src/components/ReactionsPanel/index.ts
sample-apps/react/react-video-demo/src/components/TourPanel/TourPanel.module.css

- Add reactions to demo
- Set base of icons to 24px easier on the eye

feat: reactions

---

packages/react-dogfood/next.config.mjs

fix: enable source maps in prod mode

---

packages/client/index.ts
packages/client/package.json
packages/client/src/helpers/platforms.ts
packages/client/src/rtc/Call.ts
packages/client/src/sdk-info.ts
packages/react-native-sdk/index.ts
packages/react-sdk/index.ts
yarn.lock

Provide device + SDK version info to SFU
Device info only set up for web, RN part is TODO, but that can be done later
SDK info is set up for React and RN, it currently sends a dummy version as we have yet to set up proper versioning

feat: Provide device info for web SDKs

---

packages/react-sdk/docusaurus/docs/React/01-basics/02-introduction.mdx
packages/react-sdk/docusaurus/docs/React/01-basics/03-sdk-architecture.mdx
packages/react-sdk/docusaurus/docs/React/01-basics/04-installation.mdx
packages/react-sdk/docusaurus/docs/React/01-basics/07-ui-customization-options.mdx
packages/react-sdk/docusaurus/docs/React/03-ui/01-overview.mdx

- SDK architecture page written
- @DaemonLoki I've changed some of your work around how to use the package, sorry about that, we are still thinking through some questions

docs: SDK architecture + small changes

---

packages/client/docusaurus/docs/client/02-guides/01-authentication.mdx

Adds the missing documentation chapter for #416 
<details><summary>Chapter preview:</summary>
<p>
</p>
</details>

docs: Authentication, Guest and Anonymous Users

---

packages/client/src/StreamVideoClient.ts
packages/client/src/events/reactions.ts
packages/client/src/gen/coordinator/index.ts
packages/react-sdk/src/components/CallControls/ReactionsButton.tsx

Updates the SDK to the newest OpenAPI spec and also fixes an underlying issue in the event handler for call reactions.

fix: update Reactions handling according to the newest OpenAPI spec

---

packages/react-dogfood/components/Countdown.tsx
packages/react-dogfood/pages/index.tsx

Deadline is set to the latest timezone:
```ts
const DEADLINE = new Date(
new Date('2023-06-01T00:00:00Z').getTime() + 12 * 3600 * 1000,
).getTime();
```

feat(react-dogfood): add countdown

---

packages/react-bindings/src/hooks/store.ts
packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx

- PaginatedGridLayout: prevent initial page underflow and overflow
- SpeakerLayout: The `call` can be undefined.

fix: edge cases in default layouts

---

packages/react-dogfood/pages/_app.tsx
packages/react-sdk/docusaurus/docs/React/03-ui/02-video-theme.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/05-participant-list.mdx
packages/react-sdk/src/components/StreamTheme/StreamTheme.tsx
packages/react-sdk/src/components/StreamTheme/index.ts
packages/react-sdk/src/components/index.ts
sample-apps/react/cookbook-participant-list/src/App.tsx
sample-apps/react/egress-composite/index.html
sample-apps/react/egress-composite/src/CompositeApp.tsx

Introduces new `<StreamTheme />` component which "activates" the default UI theme shipped with the React Video SDK.

feat: StreamTheme component and docs

---

.github/workflows/copy-react-demo-s3.yml
package.json
sample-apps/react/react-video-demo/index.html
sample-apps/react/react-video-demo/package.json

Copy react demo build code to an s3 bucket

feat(react-demo): copy code to s3 bucket with git workflow

---

sample-apps/react/react-video-demo/package.json
sample-apps/react/react-video-demo/src/components/Button/Button.tsx
sample-apps/react/react-video-demo/src/components/Feedback/Feedback.tsx
sample-apps/react/react-video-demo/src/components/SettingsPanel/SettingsPanel.tsx
sample-apps/react/react-video-demo/src/components/Views/EndCallView/EndCallView.tsx

- Add feedback form endpoint for each environment
- fix uncontrolled input with default values
- pass along from where the feedback is sent
- fix key error

feat(react-demo): feedback form endpoint

---

packages/client/src/rtc/codecs.ts

###
Overview: a hot fix for a regression introduced with #395

fix: disable sdp munging

---

packages/react-sdk/docusaurus/docs/React/02-guides/05-call-types.mdx

I created the article on call types.
Please thoroughly review and give feedback, since this page will be shared across SDKs. Parts of it are inspired (read: stolen) from the iOS repo (only the descriptions of the call types).
There's a lot left open, but I discussed with Tommaso that the points remain empty for now and will be filled once there's a clear definition.
That's specifically:
- which call types to have which concrete settings (a table)
- what are the default capabilities that each user type has

[docs] wrote the call types article

---

packages/react-bindings/src/hooks/permissions.ts
packages/react-dogfood/components/Lobby.tsx
packages/react-dogfood/components/MeetingUI.tsx
packages/react-dogfood/components/ToggleParticipantListButton.tsx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/13-participant-list.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/06-chat-with-video.mdx
packages/react-sdk/src/components/CallControls/CallControls.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx
packages/react-sdk/src/components/CallControls/index.ts
sample-apps/react/cookbook-participant-list/src/SpeakerView.tsx
sample-apps/react/livestream-app/src/hosts/ui/BackstageControls.tsx
sample-apps/react/livestream-app/src/viewers/Viewers.tsx
sample-apps/react/messenger-clone/src/components/Video/CallPanel.tsx

- renamed `ToggleCameraButton` to `ToggleVideoButton`
- moved `ToggleParticipantListButton` to Pronto
- updated TS definition of `useOwnCapabilities`
- improved the permission flow in the toggle buttons

fix: reorganize call control buttons

---

packages/react-sdk/docusaurus/docs/React/02-guides/06-querying-calls.mdx

A merge of the iOS and Android docs on query calls

docs: Query calls guide

---

packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

docs: rename StreamMeeting to StreamCall

---

packages/react-dogfood/components/MeetingUI.tsx
packages/react-dogfood/pages/join/[callId].tsx
packages/react-sdk/docusaurus/docs/React/02-guides/02-joining-creating-calls.mdx
packages/react-sdk/src/components/StreamCall/StreamCall.tsx
packages/react-sdk/src/core/contexts/MediaDevicesContext.tsx

Adds support for call-type provided defaults for microphone and camera.
The integrators still have the opportunity to override this behavior client-side.

feat: server-side defaults for mic and camera

---

sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx
sample-apps/react/react-video-demo/src/components/Participant/Participant.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsSlider/ParticipantsSlider.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsSlider/ParticipantsSlider.tsx

- update slider layout because partipant changed

feat(react-demo): update slider 

---

packages/client/src/Call.ts
packages/react-sdk/docusaurus/docs/React/02-guides/03-call-and-participant-state.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/08-permissions-and-moderation.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/09-reactions-and-custom-events.mdx

- Reactions and custom events guide
- Extended the permission guide with a short conceptual overview
- Extended the call state guide a section on the participant related hooks

docs: reactions and custom events

---

packages/react-sdk/docusaurus/docs/React/02-guides/10-sorting-api.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/13-participant-list.mdx

Adds docs for the Participant Sorting API.

docs: Participant Sorting API

---

packages/react-native-sdk/src/components/LocalVideoView.tsx

The goal is to have the local video floating view draggable to view partic. when needed.
https://github.com/GetStream/stream-video-js/assets/25864161/ab8cb297-4dd9-4301-bd41-6100f6debfe8
Limitations: no snapping to top right/left, bottom right/left corners

feat: floating local video view is draggable

---

packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/07-video-placeholder.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/10-connection-quality-indicator.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/14-participant-view-customizations.mdx
packages/react-sdk/src/components/CallParticipantsList/CallParticipantListingItem.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/components/ParticipantView/DefaultParticipantViewUI.tsx
packages/react-sdk/src/core/components/ParticipantView/ParticipantView.tsx
packages/react-sdk/src/core/components/Video/BaseVideo.tsx
packages/react-sdk/src/core/components/Video/Video.tsx
packages/react-sdk/src/core/hooks/useTrackElementVisibility.ts
packages/react-sdk/src/utilities/applyElementToRef.ts
packages/react-sdk/src/utilities/index.ts
sample-apps/react/egress-composite/src/layouts/dominant-speaker/DominantSpeaker.tsx
sample-apps/react/egress-composite/src/layouts/dominant-speaker/DominantSpeakerScreenShare.tsx
sample-apps/react/egress-composite/src/layouts/egressReady.ts
sample-apps/react/egress-composite/src/layouts/grid/GridView.tsx

- introduce fullscreen mode, adjust `useTrackElementVisibility` accordingly
- introduce `ParticipantViewContext` to easily pass down `ParticipantView` related data, remove `ParticipantViewUIProps` type
- rename `setVideoElementRef` to ~`setElement`~, `refs.setVideoElement` & `refs.setVideoPlaceholderElement`
- rename `applyElementRef` to `applyElementToRef`

feat(react-sdk): ParticipantViewContext + other changes

---

sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.module.css
sample-apps/react/react-video-demo/src/components/Meeting/Meeting.module.css
sample-apps/react/react-video-demo/src/components/MeetingParticipants/MeetingParticipants.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsSlider/ParticipantsSlider.module.css
sample-apps/react/react-video-demo/src/styles/chat.css

- fix video placeholder
- fix lobby placeholder

feat(video-demo): fix placeholders and chat popups placements

---

sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.module.css
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.tsx

- Add browser settings notification if a user still needs to enable mic an camera settings

feat(react-demo): browser settings notification

---

packages/react-sdk/docusaurus/docs/React/01-basics/03-quickstart.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

- fix `yarn` example
- lazy-load the codesandbox

docs: quickstart tutorial updates

---

sample-apps/react/react-video-demo/package.json
sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.module.css
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.tsx
sample-apps/react/react-video-demo/src/components/Views/LobbyView/LobbyView.tsx
sample-apps/react/react-video-demo/src/utils/useMeasureLatencyReponse.ts
yarn.lock

Check browser permissions to show the proper screen in the lobby for user to enable audio and video settings.

feat(react-demo): browser permissions

---

packages/client/src/rtc/publisher.ts

Adds more structured logging (for test intercepting purposes) of the `rid` parameters when updating the track publishing quality.

chore: improved "rid" logging

---

packages/react-sdk/src/components/Debug/DebugStatsView.tsx
packages/react-sdk/src/core/components/ParticipantView/DefaultParticipantViewUI.tsx

Adds more logging for the consumed/published tracks in debug mode.

chore: more verbose track stats logging in debug mode

---

packages/react-native-sdk/src/components/CallParticipantsInfoView.tsx
packages/react-native-sdk/src/components/CallParticipantsOptions.tsx

Fixes issues raised in the discussion - https://getstream.slack.com/archives/C02EK5GMU8Z/p1685708566588959

fix(react-native): ui issues in participant info view and options modal

---

packages/client/src/events/__tests__/recording.test.ts
packages/client/src/events/recording.ts
packages/client/src/gen/coordinator/index.ts
packages/react-bindings/src/hooks/call.ts
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx
sample-apps/react/livestream-app/src/viewers/HLSLivestream.tsx

Adjusting according to: https://github.com/GetStream/chat/pull/5093

fix: adjustments to the new egress response structure

---

packages/react-dogfood/hooks/useKeyboardShortcuts.ts

This PR introduces push to talk to Pronto application currently bound to Space key.

feat(react-dogfood): add usePushToTalk hook

---

packages/react-dogfood/components/CallLayout/SpeakerOneOnOne.tsx
packages/react-dogfood/style/CallLayout/SpeakerOneOnOne-layout.scss
packages/react-dogfood/style/CallLayout/SpeakerOneOnOne-theme.scss
packages/react-dogfood/style/CallLayout/index.scss
packages/react-dogfood/style/index.scss

- fixes an issue where remote participant in small window during screen sharing session gets muted
- fixes missing opacity/hover styling for the small participant window

fix(react-dogfood):  SpeakerOneOnOne layout audio issue

---

sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/ControlMenu/ControlMenu.tsx
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.module.css
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx
sample-apps/react/react-video-demo/src/styles/chat.css
sample-apps/react/react-video-demo/src/utils/useDeviceStorage.ts

- Save device setting to local storage and load them if present
- aditional minor css tweaks

feat(react-demo): device settings storage

---

sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx
sample-apps/react-native/dogfood/src/screens/Meeting/GuestMeetingScreen.tsx

As per the comment [here](https://github.com/GetStream/stream-video-js/pull/639#discussion_r1230959429)

refactor(react-native): client initiation change in dogfood app

---

sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/ControlMenu/ControlMenu.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx
sample-apps/react/react-video-demo/src/utils/useDeviceStorage.ts

Set default values for the user otherwise the demo won’t load

fix(react-demo): fix device storage

---

packages/client/index.ts
packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/connection.ts
packages/client/src/coordinator/connection/connection_fallback.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/coordinator/connection/utils.ts
packages/client/src/devices/devices.ts
packages/client/src/events/call.ts
packages/client/src/events/sessions.ts
packages/client/src/logger.ts
packages/client/src/rtc/Dispatcher.ts
packages/client/src/rtc/IceTrickleBuffer.ts
packages/client/src/rtc/codecs.ts
packages/client/src/rtc/flows/join.ts
packages/client/src/rtc/publisher.ts
packages/client/src/rtc/signal.ts
packages/client/src/rtc/subscriber.ts
packages/client/src/stats/state-store-stats-reporter.ts
packages/client/src/store/CallState.ts
packages/client/src/types.ts
packages/i18n/src/StreamI18n.ts
packages/react-dogfood/components/CallRecordingsPage/CallRecordingsPage.tsx
packages/react-dogfood/pages/api/call/create.ts
packages/react-dogfood/pages/guest/join/[guestCallId].tsx
packages/react-dogfood/pages/join/[callId].tsx
packages/react-sdk/docusaurus/docs/React/02-guides/01-client-auth.mdx
packages/react-sdk/src/core/components/Audio/Audio.tsx

Based on https://www.notion.so/stream-wiki/SDK-Logging-79238334201b4ca5b1ddcef7acb4abcf

feat: Logging

---

packages/react-native-sdk/src/components/IncomingCallView.tsx
packages/react-native-sdk/src/components/UserInfoView.tsx
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx

` ERROR  Failed to establish connection [Error: The "id" field on the user is missing]`
` WARN  ReactImageView: Image source "null" doesn't exist`

fix(react-native): df app null image warnings and connect on undefined userid

---

packages/react-native-sdk/src/components/ActiveCall.tsx
packages/react-native-sdk/src/components/CallParticipantsGridView.tsx
packages/react-native-sdk/src/components/CallParticipantsSpotlightView.tsx
packages/react-native-sdk/src/components/CallParticipantsView.tsx

Done as a step to remove the ActiveCall component in the future.

refactor(react-native): change CallParticipantsView to CallParticipantsGridView and conditionally render the grid and spotlight component

---

package.json
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx
sample-apps/react/audio-rooms/.env-example
sample-apps/react/livestream-app/.env-example
sample-apps/react/livestream-app/README.md
sample-apps/react/livestream-app/src/LoadingState.tsx
sample-apps/react/livestream-app/src/hooks/useInitVideoClient.ts
sample-apps/react/livestream-app/src/hooks/useSetCall.ts
sample-apps/react/livestream-app/src/hosts/Backstage.tsx
sample-apps/react/livestream-app/src/hosts/Hosts.tsx
sample-apps/react/livestream-app/src/hosts/ui/BackstageControls.tsx
sample-apps/react/livestream-app/src/utils/constants.ts
sample-apps/react/livestream-app/src/utils/getURLCredentials.ts
sample-apps/react/livestream-app/src/utils/getUser.ts
sample-apps/react/livestream-app/src/viewers/HLSLivestream.tsx
sample-apps/react/livestream-app/src/viewers/Viewers.tsx
sample-apps/react/livestream-app/src/viewers/WebRTCLivestream.tsx
sample-apps/react/livestream-app/src/viewers/ui/Lobby.tsx

Prefer credentials from URL search params before the credentials generated by the livestream demo app.

feat(livestream-app): accept credentials from URL

---

packages/client/src/events/callEventHandlers.ts
packages/client/src/gen/coordinator/index.ts

Signed-off-by: Federico Guerinoni <federico.guerinoni@getstream.io>

feat: Add `CallUserMuted` event

---

packages/client/src/gen/coordinator/index.ts

Signed-off-by: Federico Guerinoni <federico.guerinoni@getstream.io>

feat: Add user that mutes others in `CallUserMuted` event

---

sample-apps/react-native/dogfood/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/dogfood/ios/StreamReactNativeVideoSDKSample/Info.plist

This will be reverted back when we pick up the task to work on Landscape mode.

fix(react-native): disable landscape mode on dogfood app

---

sample-apps/react/react-video-demo/data/tour.ts
sample-apps/react/react-video-demo/src/components/ChatInput/ChatInput.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsSlider/ParticipantsSlider.module.css
sample-apps/react/react-video-demo/src/components/Views/EndCallView/EndCallView.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx
sample-apps/react/react-video-demo/src/styles/chat.css

feat(react-demo): ui comments

---

sample-apps/react/audio-rooms/src/components/Error.tsx
sample-apps/react/audio-rooms/src/components/Room/RoomUI.tsx
sample-apps/react/audio-rooms/src/pages/Room.tsx

This fixes an edge case in the tutorial flow that caused audio rooms to be created by a wrong user (buddy user).

fix: option to opt-out from call creation

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/01-introduction.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation.mdx
sample-apps/react-native/dogfood/README.md

Write intro and installation guides
The installation process of peer dependencies can be a bit overwhelming on RN, due to the large number of peer deps. 
Therefore we wrote this guide

docs(react-native): intro and installation guide

---

packages/client/src/rtc/Publisher.ts

Adds one additional mechanism for determining the `mid` property of the media tracks we are announcing to the SFU.
In Firefox, `track.id` and `mid` are not reliable and we can't make a good match when parsing the SDP we are about to exchange.
For that purpose, we maintain an internal ordered index of added tracks (transceivers) and we use it as a third source for extracting the `mid`. Assumption: The ordering of transceivers added to the Peer Connection matches with their `mid` property value in the exchanged SDP.
With this change, the `mid` resolution process is the following one:
1. Try reading the browser-provided `transceiver.mid`
2. Try retrieving the `mid` from the SDP by matching the `track.kind` + `track.id` with `msid`
3. Try retrieving the `mid` based on the internal ordering …

fix: Heuristic announcement of track mid

---

package.json
packages/client/package.json
packages/client/project.json
packages/client/src/StreamVideoClient.ts
packages/client/src/coordinator/connection/client.ts
packages/client/tsconfig.json
packages/client/version.ts
packages/react-native-sdk/package.json
packages/react-native-sdk/project.json
packages/react-native-sdk/src/utils/setClientDetails.ts
packages/react-native-sdk/tsconfig.json
packages/react-native-sdk/version.ts
packages/react-sdk/index.ts
packages/react-sdk/package.json
packages/react-sdk/project.json
packages/react-sdk/tsconfig.json
packages/react-sdk/version.ts

Example values:
- React SDK: stream-video-javascript-client-browser-0.0.43-video-react-sdk-0.0.82
- React Native SDK: stream-video-javascript-client-browser-0.0.43-video-react_native-sdk-0.0.1-alpha126
- JS client: stream-video-javascript-client-browser-0.0.43
- Node client: stream-video-javascript-client-node-0.0.43

feat: SDK version header

---

sample-apps/react/react-video-demo/index.html

Adds the required meta parameters that enable AppClips support.

fix: add AppClips meta tag

---

packages/react-native-sdk/src/components/call/internal/CallParticipantsSpotlightView.tsx

Fixes - https://getstream.slack.com/archives/C02EK5GMU8Z/p1689763681978089

fix(react-native): CallContentView UI when there is no remote participants in spotlight mode

---

sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx

A cherry-pick of the QR code fix done in #832

fix: use valid URL for the invitation QR code

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Based on: https://github.com/GetStream/sdk-template/tree/main

chore: Add issue templates

---

.styles/Vocab/Base/accept.txt
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation.mdx
packages/react-native-sdk/index.ts
packages/react-native-sdk/package.json
sample-apps/react-native/dogfood/index.js
sample-apps/react-native/dogfood/package.json
yarn.lock

Importantly, all polyfills now moved inside the SDK

fix(react-native): reduce installation steps

---

sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/Feedback/Feedback.tsx
sample-apps/react/react-video-demo/src/components/Views/EndCallView/EndCallView.tsx

Ticket: https://stream-io.atlassian.net/browse/WD-742
* Added the `callId` to the feedback form on the end call screen
* Improved logic for feedback form url params
* Improved error handling

[WD-742] Improvements to feedback form

---

sample-apps/react/react-video-demo/src/components/Feedback/Feedback.tsx
sample-apps/react/react-video-demo/src/utils/getCookie.ts

Add csrf to feedback form

---

.github/workflows/version-and-release.yml
.gitignore
packages/client/docusaurus/.env
packages/client/docusaurus/docs/javascript/01-basics/01-introduction.mdx
packages/client/docusaurus/docs/javascript/01-basics/02-installation.mdx
packages/client/docusaurus/docs/javascript/01-basics/03-quickstart.mdx
packages/client/docusaurus/docs/javascript/01-basics/_category_.json
packages/client/docusaurus/docs/javascript/02-guides/01-client-auth.mdx
packages/client/docusaurus/docs/javascript/02-guides/02-joining-creating-calls.mdx
packages/client/docusaurus/docs/javascript/02-guides/03-call-and-participant-state.mdx
packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/client/docusaurus/docs/javascript/02-guides/05-call-types.mdx
packages/client/docusaurus/docs/javascript/02-guides/06-querying-calls.mdx
packages/client/docusaurus/docs/javascript/02-guides/08-permissions-and-moderation.mdx
packages/client/docusaurus/docs/javascript/02-guides/09-reactions-and-custom-events.mdx
packages/client/docusaurus/docs/javascript/02-guides/10-sorting-api.mdx
packages/client/docusaurus/docs/javascript/02-guides/_category_.json
packages/client/docusaurus/docs/javascript/10-advanced/06-apply-video-filters.mdx
packages/client/docusaurus/docs/javascript/10-advanced/06-chat-with-video.mdx
packages/client/docusaurus/docs/javascript/10-advanced/06-events.mdx
packages/client/docusaurus/docs/javascript/10-advanced/07-gdpr-endpoints.mdx
packages/client/docusaurus/docs/javascript/10-advanced/08-recording.mdx
packages/client/docusaurus/docs/javascript/10-advanced/09-broadcasting.mdx
packages/client/docusaurus/docs/javascript/10-advanced/_category_.json
packages/client/project.json
packages/i18n/project.json
packages/react-bindings/project.json
packages/react-native-sdk/project.json
packages/react-sdk/project.json

Currently it's only possible the run the docs locally, use this branch: https://github.com/GetStream/stream-chat-docusaurus-cli/pull/89 (no need to rebuild anything, just pull the branch)
The docs content is just a copy-paste from React, but I removed the unnecessary pages.

docs(client): Create docusaurus folder for client

---

packages/styling/src/Video/Video-layout.scss

Prevent users from opening video controls and similar other actions.

fix(styling): disable video pointer events

---

sample-apps/react/react-video-demo/index.html
sample-apps/react/react-video-demo/src/App.css
sample-apps/react/react-video-demo/src/App.tsx
sample-apps/react/react-video-demo/src/components/Footer/Footer.tsx
sample-apps/react/react-video-demo/src/components/Header/Header.module.css
sample-apps/react/react-video-demo/src/components/Header/Header.tsx
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.module.css
sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx
sample-apps/react/react-video-demo/src/components/Layout/MeetingLayout/MeetingLayout.module.css
sample-apps/react/react-video-demo/src/components/Layout/MeetingLayout/MeetingLayout.tsx
sample-apps/react/react-video-demo/src/components/Meeting/Meeting.module.css
sample-apps/react/react-video-demo/src/components/Meeting/Meeting.tsx
sample-apps/react/react-video-demo/src/components/NewMessageNotification/NewMessageNotification.css
sample-apps/react/react-video-demo/src/components/NewMessageNotification/NewMessageNotification.tsx
sample-apps/react/react-video-demo/src/components/NewMessageNotification/index.ts
sample-apps/react/react-video-demo/src/components/Panel/Panel.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantsPanel.module.css
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantsPanel.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/index.ts
sample-apps/react/react-video-demo/src/components/Sidebar/Sidebar.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx
sample-apps/react/react-video-demo/src/hooks/useEdges.ts
sample-apps/react/react-video-demo/src/styles/chat.css

1. Notification about new chat message, when chat is collapsed or hidden
2. Make the participants panel float above the stage on small screens
3. Provide information that no participant search results were found
4. Cache edges in local storage and retrieve new 24 hours later the earliest

feat(react video demo): show new message chat notifications & float participants list on mobile

---

.github/workflows/copy-react-demo-s3.yml
.github/workflows/deploy-react-sample-apps.yml
.github/workflows/test.yml
.github/workflows/version-and-release.yml

- prevent triggering runs from unrelated directories
- disable Sonar
- remove unnecessary matrix strategy

chore: optimize the Github Actions

---

packages/react-native-sdk/src/components/Participant/LocalParticipantView/index.tsx
packages/react-native-sdk/src/components/Participant/ParticipantView/ParticipantView.tsx
packages/react-native-sdk/src/components/Participant/ParticipantView/VideoRenderer.tsx
sample-apps/react-native/dogfood/src/components/ActiveCall.tsx

otherwise it breaks on android!

fix(react-native): floating video must be one zOrder above the grid 

---

packages/client/src/Call.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/CameraManagerState.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/MicrophoneManagerState.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/devices/__tests__/InputMediaDeviceManager.test.ts
packages/client/src/devices/__tests__/MicrophoneManager.test.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/Publisher.test.ts
packages/react-native-sdk/src/providers/MediaStreamManagement/index.tsx

- `call.microphone.disable()` should only disable tracks, but not stop them
- `call.camera.disable()` is unchanged, it stops the tracks
- `pause` and `resume` methods are removed -> RN fails becuase of that, we should fix that before merge

feat: Disable doesn't stop audio tracks

---

packages/react-native-sdk/project.json

Need to re-enable the release, to be able to test the tutorials.

build: reenable the release

---

sample-apps/react/react-video-demo/src/components/InvitePanel/InvitePanel.tsx

Remove conditional logic for QR code.

chore: Always enable QR code

---

packages/client/src/coordinator/connection/types.ts
sample-apps/react/livestream-app/src/hooks/useInitVideoClient.ts
sample-apps/react/livestream-app/src/hosts/Hosts.tsx
sample-apps/react/livestream-app/src/viewers/Viewers.tsx
sample-apps/react/react-video-demo/src/components/LobbyPanel/LobbyPanel.data.ts
sample-apps/react/react-video-demo/src/components/Views/LobbyView/LobbyView.data.ts

Update user type def for WS auth, based on https://getstream.slack.com/archives/C022N8JNQGZ/p1693212159363949?thread_ts=1693160079.067939&cid=C022N8JNQGZ

fix: type definition of user object for ws auth

---

packages/client/src/Call.ts

fixes this problem: https://getstream.slack.com/archives/C05JEQZ6C4V/p1692981625098239

fix: round non-int video dimension values

---

sample-apps/react/react-video-demo/data/tour.ts
sample-apps/react/react-video-demo/src/main.tsx

chore(react-video-demo): put back gleap

---

packages/client/docusaurus/docs/javascript/01-basics/03-quickstart.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/01-video-calling.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/02-audio-room.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/03-livestream.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/_category_.json

State is draft because:
- Need to test the viewer app some more ✅
- Needs dynascale ✅
But the tutorial content and the codesanbox playground should be ready for review, no major changes expected

docs: JavaScript livestream tutorial

---

packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/client/src/Call.ts
packages/client/src/devices/SpeakerManager.ts
packages/client/src/devices/SpeakerState.ts
packages/client/src/devices/__tests__/SpeakerManager.test.ts
packages/client/src/helpers/DynascaleManager.ts
packages/client/src/helpers/__tests__/DynascaleManager.test.ts
packages/client/src/types.ts
sample-apps/client/ts-quickstart/src/device-selector.ts
sample-apps/client/ts-quickstart/src/main.ts
sample-apps/client/ts-quickstart/src/participant.ts

We should combine this with the dynascale PR to apply device id and volume settings ✅

feat: speaker management

---

packages/client/docusaurus/docs/javascript/01-basics/03-quickstart.mdx
packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/02-audio-room.mdx
packages/client/docusaurus/docs/javascript/10-advanced/06-events.mdx
packages/client/docusaurus/docs/javascript/10-advanced/08-recording.mdx
packages/react-sdk/docusaurus/docs/React/01-basics/03-quickstart.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/01-client-auth.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/06-events.mdx

Accommodates some of the received feedback about our docs.

docs: accommodate various docs feedback

---

packages/client/src/Call.ts
packages/client/src/rtc/Publisher.ts
sample-apps/react/react-video-demo/src/App.tsx

fix: consider prior track publishing state before applying soft mutes

---

sample-apps/react/react-dogfood/components/Lobby.tsx

chore: new arrangement of the lobby buttons

---

packages/client/src/Call.ts
packages/client/src/coordinator/connection/types.ts
packages/client/src/rtc/Publisher.ts

Removes an unused Publisher property. Most likely, a leftover from a past refactoring.

chore: remove dangling preferredVideoCodec option

---

packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/02-setup.mdx

In case other people are lazy and copy from the docs and get confused about why their build fails 🤦

docs: add missing comma in RN setup

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/03-quickstart.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/10-reactions-and-custom-events.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/06-broadcasting.mdx

Small docs fix - searched the RN package for all the places this fix was needed.

docs(react-native): fix broken links

---

packages/client/src/__tests__/server-side/call.test.ts
packages/client/src/gen/coordinator/index.ts
packages/client/src/store/CallState.ts
sample-apps/react/react-dogfood/components/CallRecordings.tsx
sample-apps/react/react-video-demo/src/components/Recordings/Recordings.tsx

Signed-off-by: Federico Guerinoni <federico.guerinoni@getstream.io>

feat: Update with new API spec

---

sample-apps/react/egress-composite/src/ConfigurationContext.tsx
sample-apps/react/egress-composite/src/components/UIDispatcher.tsx
sample-apps/react/egress-composite/src/components/layouts/DominantSpeaker/DominantSpeaker.tsx
sample-apps/react/egress-composite/src/components/layouts/DominantSpeaker/useSpotlightParticipant.ts
sample-apps/react/egress-composite/src/components/layouts/index.ts
sample-apps/react/egress-composite/tests/layouts.spec.ts

Rename `single_participant` to `single-participant` layout type to match specs.

fix(egress-composite): rename "single_participant" to "single-participant"

---

packages/react-sdk/src/components/CallParticipantsList/CallParticipantListHeader.tsx
packages/react-sdk/src/components/CallParticipantsList/EmptyParticipantSearchList.tsx
packages/react-sdk/src/translations/en.json
packages/styling/src/CallParticipantList/CallParticipantList-theme.scss

Displays the number of anonymous users connected to the current call.

feat: show the anonymous user count in the participant list

---

packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx
packages/react-sdk/src/core/components/CallLayout/SpeakerLayout.tsx
packages/react-sdk/src/core/hooks/index.ts
packages/react-sdk/src/core/hooks/useCalculateHardLimit.ts

Adds `participantsBarLimit` property to `SpeakerLayout` component which hard-limits number of rendered participants in the participants bar.

feat(SpeakerLayout): add participantsBarLimit

---

sample-apps/react/react-video-demo/src/components/Header/Header.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsControlModal/ParticipantsControlModal.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantListItem.tsx
sample-apps/react/react-video-demo/src/components/ParticipantsPanel/ParticipantsPanel.tsx
sample-apps/react/react-video-demo/src/hooks/useParticipantNotification.tsx
sample-apps/react/react-video-demo/src/hooks/useScreenShareNotification.tsx

Fallback to `participant.userId` when `participant.name` is not set.

fix: fallback to `userId` when `name` is not set

---

packages/client/docusaurus/docs/javascript/10-advanced/06-events.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/03-events.mdx
packages/react-sdk/docusaurus/docs/React/10-advanced/06-events.mdx

Updates the list of events one can receive.

docs: update list of events

---

packages/react-sdk/docusaurus/docs/React/02-tutorials/01-video-calling.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/02-audio-room.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

docs: React tutorial enhancements

---

packages/react-native-sdk/src/components/Participant/FloatingParticipantView/FloatingView/ReanimatedFloatingView.tsx

The floating view on renimated animation was broken because the initial drag always had start position as 0. 
Upon a lot of research I found that we should not use useRef objects inside gesture callbacks. This is because the JS variable updates are not sent to UI thread. Instead the alternative is to do useSharedValue.. now the value is shared between JS and UI thread! 
probably before we had an older gesture navigator version and it worked. Upon some update this behaviour changed.

fix(react-native): incorrect starting position on reanimated floating animation

---

sample-apps/react/react-dogfood/pages/api/call/create-server.ts
sample-apps/react/react-dogfood/pages/api/call/create.ts

Unblocks the `/pronto` command by removing the Server-Side Video integration until we manage to provide a fix for the NextJS/RxJS issue.

fix(pronto): restore /pronto slack hook

---

.github/actions/rn-bootstrap/action.yml
packages/react-native-sdk/src/components/Call/CallTopView/ParticipantsInfoBadge.tsx
packages/react-native-sdk/src/constants/TestIds.ts
sample-apps/react-native/dogfood/e2e/js/setup.js
sample-apps/react-native/dogfood/e2e/js/sleep.js
sample-apps/react-native/dogfood/e2e/test.yaml

occassionally e2e fails on not finding the button
https://github.com/GetStream/stream-video-js/actions/runs/6587748280/job/17899157544
I think its because sometimes the call takes a while to join..

chore: fix e2e failure on not finding the info button randomly

---

packages/react-native-sdk/README.md
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/04-camera-and-microphone.mdx

The purpose of the PR is to introduce the speaker management docs in the React Native SDK. 
The docs are introduced within the `Camera and Microphone` guide as other SDKs. The [flow of the iOS SDK](https://getstream.io/video/docs/ios/guides/camera-and-microphone/#speaker-manager) is followed here.
Note: Taken as per discussion [here](https://getstream.slack.com/archives/C04SAU8QUS0/p1698063688361139).

docs(react-native): Update Camera and microphone guide with Speaker Management guide

---

packages/client/docusaurus/docs/javascript/02-guides/02-joining-creating-calls.mdx
packages/client/docusaurus/docs/javascript/02-tutorials/03-livestream.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/02-joining-creating-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx
packages/react-sdk/docusaurus/docs/React/03-ui-components/core/call-layout.mdx
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/15-watching-a-livestream.mdx

Accommodates received feedback around React and Plain-JS docs.

docs: accommodate feedback

---

packages/client/docusaurus/docs/javascript/02-guides/02-joining-creating-calls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/02-joining-creating-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/02-joining-creating-calls.mdx

Adds code examples on how ring calls are supposed to be integrated.
For React, two additional CodeSandboxes are added which showcase the integration.

docs(react): Expand on Ring Calls

---

packages/client/src/devices/InputMediaDeviceManager.ts
packages/react-sdk/src/components/CallControls/ScreenShareButton.tsx
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
sample-apps/react/react-dogfood/components/Lobby.tsx
sample-apps/react/react-video-demo/src/components/Views/MeetingView/MeetingView.tsx

- Respect server-side settings for mic and camera on the lobby screen
- Fix ScreenShareButton class names
- Fix ScreenSharing in Video Demo

fix: respect server-side settings in the lobby

---

packages/client/docusaurus/docs/javascript/02-tutorials/03-livestream.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/02-tutorials/03-livestream.mdx
packages/react-sdk/docusaurus/docs/React/02-tutorials/03-livestream.mdx

There was a recent change in backend

docs: update streamKey in livestream tutorials

---

packages/client/src/Call.ts
packages/client/src/devices/InputMediaDeviceManagerState.ts
packages/client/src/devices/__tests__/InputMediaDeviceManagerState.test.ts

[Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) availability needs to be checked before querying as it isn't available on every platform.
Follow-up to #1184

fix(device-api): check for Permissions API availability

---

packages/react-sdk/src/components/CallControls/AcceptCallButton.tsx
packages/react-sdk/src/components/CallControls/CallStatsButton.tsx
packages/react-sdk/src/components/CallControls/CancelCallButton.tsx
packages/react-sdk/src/components/CallControls/ReactionsButton.tsx
packages/react-sdk/src/components/CallControls/RecordCallButton.tsx
packages/react-sdk/src/components/CallControls/ScreenShareButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioButton.tsx
packages/react-sdk/src/components/CallControls/ToggleAudioOutputButton.tsx
packages/react-sdk/src/components/CallControls/ToggleVideoButton.tsx
packages/react-sdk/src/components/Menu/MenuToggle.tsx

Assign `data-testid` attributes to the Call Control Buttons.

chore: testids for call control buttons

---

sample-apps/react/react-dogfood/pages/api/auth/create-token.ts

Updates the API key - environment translation logic.

fix: legacy api key configuration

---

packages/react-sdk/src/components/Search/hooks/useSearch.ts
packages/styling/src/Button/Button-layout.scss
sample-apps/react/react-dogfood/components/DefaultAppHeader.tsx
sample-apps/react/react-dogfood/components/ToggleDocumentationButton.tsx

This PR fixes three issues with react-sdk components (and some in react-dogfood app):
1. Participant counter and warning badges on mic/camera toggles are now positioned correctly (this also fixes horizontal scroll appearing in the window).
2. Tutorial/documentation header menu items are now aligned to the left.
3. Participants list search no longer gets stuck in loading state.

fix(react-sdk): various minor issues in sdk components

---

sample-apps/react/react-dogfood/components/Debug/DebugStatsView.tsx
sample-apps/react/react-dogfood/components/Lobby.tsx
sample-apps/react/react-dogfood/components/MeetingUI.tsx
sample-apps/react/react-dogfood/components/ToggleParticipantListButton.tsx
sample-apps/react/react-dogfood/hooks/useFloatingUIPreset.ts
sample-apps/react/react-dogfood/pages/index.tsx
sample-apps/react/react-dogfood/pages/join/[callId].tsx
sample-apps/react/react-dogfood/style/Button/Button.scss
sample-apps/react/react-dogfood/style/CallControls/CallControls-layout.scss

Adds an experimental waiting room functionality in Pronto built on top of `custom` events.
For more information, check: https://getstream.slack.com/archives/C022N8JNQGZ/p1706886559355909?thread_ts=1706212004.817829&cid=C022N8JNQGZ

feat(pronto): experimental Waiting Room

---

packages/client/README.md
packages/react-native-sdk/README.md
packages/react-sdk/README.md

Updates the top-level SDK links in the Readmes

chore: update SDK links

---

packages/client/docusaurus/docs/javascript/02-guides/06-querying-calls.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/06-querying-calls.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/06-querying-calls.mdx

General updates on the Query Calls page + a snippet for querying ongoing calls.
Camera & Mic: Document `speaker.setVolume()` API.

docs(query-calls): update examples and content

---

sample-apps/react-native/dogfood/e2e/test.yaml

[Green job on CI](https://github.com/GetStream/stream-video-js/actions/runs/8281348898)

chore(react-native): comment out Stream Video Buddy related steps in RN E2E test due to flakiness on GitHub Actions

---

packages/client/src/client-details.ts
packages/client/src/coordinator/connection/location.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/Subscriber.ts

Reduce the log level from `error` to `warn` for errors reported while tricking ICE candidates.
This PR also includes some other small code improvements and bug fixes.

chore: reduced log level for ICE Candidate errors

---

packages/client/src/gen/coordinator/index.ts

Updates to: https://github.com/GetStream/protocol/pull/491

feat(client): update to the latest OpenAPI

---

packages/client/src/Call.ts
packages/client/src/gen/coordinator/index.ts

This reverts commit 45fb9da6eb52e4509c7b45b53cd62b0af6f7ec74.

feat: revert add submit feedback method to Call (#1307)

---

packages/react-native-sdk/android/build.gradle
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/07-keeping-call-alive.mdx
sample-apps/react-native/dogfood/android/build.gradle
sample-apps/react-native/expo-video-sample/app.json

docs: inform about android target sdk 33 requirements

---

packages/client/docusaurus/docs/javascript/02-guides/01-client-auth.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/01-client-auth.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/01-client-auth.mdx

Provide a link to our server-side SDKs docs on token generation.

docs(token): add link towards our server-side SDK docs about token generation

---

packages/client/src/Call.ts

The SDK should ignore all SFU signal WebSocket connection close codes when the user has initiated a `call.leave()` operation.
In some circumstances, the SFU might close the WS connection with code 1001 when the user has requested to leave the call. Our SDK doesn't properly handle this code and enters a reconnection loop. After some discussion with our backend team, we have realized that we shouldn't rely on these codes at all and we should improve our reconnection logic. Until this is implemented, the SDK should ignore all WS close codes after `call.leave()` is invoked.

fix(client): ignore SFU WS status code when the user initiates leaving a call

---

packages/react-sdk/src/components/BackgroundFilters/BackgroundFilters.tsx

Fixes a race condition in loading and unloading of the background effects filter.

fix(filters): Synchronize filter loading and unloading

---

packages/client/docusaurus/docs/javascript/02-guides/15-transcriptions.mdx
packages/client/src/store/CallState.ts
packages/react-native-sdk/README.md
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/16-transcriptions.mdx
packages/react-sdk/README.md
packages/react-sdk/docusaurus/docs/React/06-ui-cookbook/17-transcriptions.mdx

Adds UI cookbooks for enabling and disabling transcriptions.

docs: add Transcription docs

---

sample-apps/react/react-dogfood/pages/guest/join/[guestCallId].tsx

Adds Background filters and Noise Cancellation capabilities for anon and guest user mode of Pronto.

fix(pronto): make anon logins work again

---

packages/client/src/Call.ts
packages/client/src/stats/SfuStatsReporter.ts
packages/client/src/stats/stateStoreStatsReporter.ts
packages/client/src/stats/utils.ts

Anonymous users have no audio, video, or screen share permissions, and as such, there is no need to create a Publisher peer connection for them.

fix: don't create publisher PC for anonymous users

---

packages/react-sdk/src/core/components/CallLayout/PaginatedGridLayout.tsx

fix(grid): guard against zero or negative group size

---

sample-apps/react/livestream-app/README.md
sample-apps/react/livestream-app/src/hooks/useInitVideoClient.ts
sample-apps/react/livestream-app/src/hooks/useSetCall.ts
sample-apps/react/livestream-app/src/hosts/Backstage.tsx
sample-apps/react/livestream-app/src/hosts/ui/BackstageControls.tsx
sample-apps/react/livestream-app/src/utils/getUser.ts
sample-apps/react/livestream-app/src/viewers/WebRTCLivestream.tsx

feat: Livestream app improvements

---

packages/react-sdk/index.ts
packages/react-sdk/src/wrappers/LivestreamPlayer/LivestreamPlayer.tsx
packages/react-sdk/src/wrappers/LivestreamPlayer/index.ts
packages/react-sdk/src/wrappers/index.ts

Provides a new `LivestreamPlayer` wrapper component similar to the one available in iOS.

fix: add LivestreamPlayer wrapper component

---

packages/react-sdk/docusaurus/docs/React/03-ui-components/utility/livestream-player.mdx

Adds a documentation page for #1372

docs: LivestreamPlayer page

---

packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt
packages/react-native-sdk/src/hooks/useIsInPiPMode.tsx
packages/react-native-sdk/src/providers/StreamCall.tsx

instead of holding the state in native layer now we get it from the current activity from android platform

fix(react-native): getting if pip was enabled from native was randomly broken 

---

packages/client/src/Call.ts
packages/client/src/gen/coordinator/index.ts
packages/client/src/store/CallState.ts

- https://github.com/GetStream/chat/pull/6390
- https://github.com/GetStream/chat/pull/6428
- https://github.com/GetStream/stream-video-js/pull/1369

fix: align with the latest openapi

---

packages/react-native-sdk/.prettierrc
packages/react-native-sdk/src/components/Call/CallControls/AcceptCallButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/HangupCallButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/RejectCallButton.tsx
packages/react-native-sdk/src/components/Call/CallControls/internal/ReactionsPicker.tsx
packages/react-native-sdk/src/components/Call/Lobby/JoinCallButton.tsx
packages/react-native-sdk/src/components/Livestream/LivestreamControls/HostStartStreamButton.tsx
packages/react-native-sdk/src/components/Livestream/LivestreamControls/ViewerLeaveStreamButton.tsx
packages/react-native-sdk/src/components/Livestream/LivestreamPlayer/LivestreamPlayer.tsx
packages/react-native-sdk/src/components/Participant/FloatingParticipantView/FloatingView/AnimatedFloatingView.tsx
packages/react-native-sdk/src/contexts/BackgroundFilters.tsx
packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts
packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/hooks/usePermissionRequest.tsx
packages/react-native-sdk/src/providers/StreamVideo.tsx
packages/react-native-sdk/src/utils/getAndroidDefaultRingtoneUrl.ts
packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/ios.ts
packages/react-native-sdk/src/utils/push/libs/firebaseMessaging.ts
packages/react-native-sdk/src/utils/push/utils.ts

A custom logger can be passed to the video client
In RN SDK, we did not use that logger, this PR fixes that

feat: use logger from client for react native sdk

---

sample-apps/react/react-dogfood/components/Feedback/Feedback.tsx

Context: https://getstream.slack.com/archives/C022N8JNQGZ/p1719952680446049

chore: update the feedback fallback e-mail address

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/07-keeping-call-alive.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/common-content/setup/installation/troubleshooting.mdx
packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidPermissions.test.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidManifest.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidPermissions.ts
packages/react-native-sdk/package.json
packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/hooks/useIsInPiPMode.tsx
packages/react-native-sdk/src/utils/StreamVideoRN/index.ts
packages/react-native-sdk/src/utils/StreamVideoRN/types.ts
sample-apps/react-native/dogfood/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/dogfood/android/build.gradle
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/expo-video-sample/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/expo-video-sample/android/gradle.properties
sample-apps/react-native/expo-video-sample/app.json
sample-apps/react-native/expo-video-sample/ios/Podfile.lock
sample-apps/react-native/expo-video-sample/ios/expovideosample.xcodeproj/project.pbxproj
sample-apps/react-native/expo-video-sample/ios/expovideosample/Info.plist
sample-apps/react-native/expo-video-sample/package.json
yarn.lock

* Removed usage of Foreground services infavour of PiP for keeping call alive in the background
* updated installation and push docs
* updated expo plugin

feat(react-native)!: support targetSdk android 14 

---

packages/client/src/Call.ts
packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts

fix: ringing state issues when call was already ended

---

packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/03-quickstart.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/01-client-auth.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/07-keeping-call-alive.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/10-reactions-and-custom-events.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/05-ui-cookbook/09-reactions.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/02-chat-with-video.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/01-overview.mdx

Some typos and small improvements in the React Native docs.

docs: React Native docs updates

---

packages/react-native-sdk/src/providers/StreamCall.tsx
sample-apps/react-native/dogfood/src/navigators/Call.tsx
sample-apps/react-native/expo-video-sample/app/ringing.tsx

another unrelated change: added ringing mode filter for dogfood apps

fix: added workaround for android where video doesn't resume when resuming app from lock screen

---

.github/workflows/test.yml
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/01-setup/02-installation/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/03-core/07-keeping-call-alive.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/04-other-than-ringing-setup/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/04-other-than-ringing-setup/02-expo.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/08-screensharing/02-setup/01-react-native.mdx
packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidManifest.test.ts
packages/react-native-sdk/expo-config-plugin/__tests__/withAndroidPermissions.test.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidManifest.ts
packages/react-native-sdk/expo-config-plugin/src/withAndroidPermissions.ts
packages/react-native-sdk/expo-config-plugin/src/withMainActivity.ts
packages/react-native-sdk/jest-setup.ts
packages/react-native-sdk/package.json
packages/react-native-sdk/src/hooks/useAndroidKeepCallAliveEffect.ts
packages/react-native-sdk/src/utils/StreamVideoRN/types.ts
packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/ios.ts
packages/react-native-sdk/src/utils/push/libs/index.ts
packages/react-native-sdk/src/utils/push/libs/notifee.ts
sample-apps/react-native/dogfood/package.json
yarn.lock

fix(react-native)!: make notifee to be optional

---

packages/client/docusaurus/docs/javascript/02-guides/04-camera-and-microphone.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/04-camera-and-microphone.mdx

Updates the headings to allow better indexing and discoverability of our Filters API.

docs: update headings for AI/ML filters

---

packages/client/package.json
packages/client/src/__tests__/StreamVideoClient.test.ts
sample-apps/react/react-dogfood/helpers/jwt.ts
sample-apps/react/react-dogfood/lib/getServerSideCredentialsProps.ts
sample-apps/react/react-dogfood/package.json
sample-apps/react/react-dogfood/pages/api/auth/create-token.ts
sample-apps/react/react-dogfood/pages/api/call/sample.ts
sample-apps/react/react-dogfood/pages/guest/join/[guestCallId].tsx
yarn.lock

I wanted to do this for a long time now, this way we can catch any issues with token creation in the node-sdk

chore: update node-sdk, add this to pronto for token generation

---

packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/location.ts
packages/client/src/coordinator/connection/types.ts

Sometimes, it may take longer than 2000 ms. to retrieve the approximate location of the user. 
We now try up to three times before we eventually give up.

fix: retryable location hint

---

packages/client/docusaurus/docs/javascript/02-guides/16-closed-captions.mdx
sample-apps/client/ts-quickstart/index.html
sample-apps/client/ts-quickstart/package.json
sample-apps/client/ts-quickstart/src/closed-captions.ts
sample-apps/client/ts-quickstart/src/main.ts

I'll add the docs if the code looks good :)

docs: closed captions

---

packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/01-react-native.mdx
packages/react-native-sdk/docusaurus/docs/reactnative/06-advanced/04-push-notifications/03-ringing-setup/02-expo.mdx
packages/react-native-sdk/expo-config-plugin/src/withAndroidPermissions.ts
sample-apps/react-native/dogfood/android/app/src/main/AndroidManifest.xml
sample-apps/react-native/expo-video-sample/android/app/src/main/AndroidManifest.xml

fix: clarify about USE_FULL_SCREEN_INTENT android permission

---

packages/react-native-sdk/docusaurus/docs/reactnative/03-core/01-client-auth.mdx
packages/react-sdk/docusaurus/docs/React/02-guides/01-client-auth.mdx

Few tickets on support came up, we need to be more clear in the docs.

docs: Added more details for anon users

---

sample-apps/react-native/dogfood/src/components/ParticipantsInfoList.tsx
sample-apps/react-native/dogfood/src/components/ParticipantsLayoutButton.tsx
sample-apps/react-native/dogfood/src/components/VideoEffectsButton/index.tsx
sample-apps/react-native/dogfood/src/screens/AudioRoom/CreateRoomModal.tsx

- Fixes the modals in dogfood app 
- before the fix: when the app in is landscape mode and a modal is being open the app is set to portrait mode
- after the fix: the modals support landscape mode as well and work as expected in landscape mode

fix(rn-dogfood): Fix modals orientation bug

---

packages/client/src/Call.ts
packages/client/src/coordinator/connection/client.ts
packages/client/src/gen/video/sfu/models/models.ts
packages/client/src/gen/video/sfu/signal_rpc/signal.ts
packages/client/src/stats/SfuStatsReporter.ts
packages/client/src/store/rxUtils.ts
sample-apps/react/react-dogfood/components/ActiveCall.tsx
sample-apps/react/react-dogfood/components/ToggleDualCameraButton.tsx
sample-apps/react/react-dogfood/components/ToggleDualMicButton.tsx

Adds input device reporting in the call stats.

feat: report input devices in call stats

---

.github/workflows/react-native-workflow.yml

Adds the `PBE-5855-feat/react-native-video-design-v2` branch to the react native workflow pipeline so that ios builds are created from this branch as well.

chore: add design v2 branch for ios build

---

packages/react-bindings/src/hooks/callUtilHooks.ts

Fix the wrong imports in the `callUtilHooks.ts`

fix: imports for useToggleCallRecording

---

packages/client/src/devices/CameraManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/events/__tests__/mutes.test.ts

fixes regression caused by #1521

fix: camera flip did not work in react-native

---

sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
yarn.lock

Bumps the webrtc version to `125.0.0-alpha.3`

fix: bump webrtc version

---

packages/client/src/gen/video/sfu/event/events.ts
packages/client/src/rtc/Dispatcher.ts
packages/client/src/rtc/Publisher.ts
packages/react-sdk/CHANGELOG.md
packages/react-sdk/package.json
packages/video-filters-web/CHANGELOG.md
packages/video-filters-web/package.json
packages/video-filters-web/src/helpers/webglHelper.ts

feat: Codec Switching

---

sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/src/components/NavigationHeader.tsx
sample-apps/react-native/dogfood/src/components/ParticipantsInfoList.tsx
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx
sample-apps/react-native/dogfood/src/contexts/AppContext.tsx
sample-apps/react-native/dogfood/src/modules/helpers/createToken.ts
sample-apps/react-native/dogfood/src/screens/LoginScreen.tsx
sample-apps/react-native/dogfood/src/screens/Meeting/MeetingScreen.tsx
sample-apps/react-native/dogfood/src/types/env.d.ts

More reliable environment switcher + webrtc 125.0.0-rc.2

feat(rn): environment switcher

---

sample-apps/react-native/dogfood/src/components/BottomControlsDrawer.tsx
sample-apps/react-native/dogfood/src/components/CallControlls/MoreActionsButton.tsx
sample-apps/react-native/dogfood/src/components/CallStats.tsx

Adds the call stats in the dogfood app.

fix: add call stats in dogfood app

---

packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/devices.ts
packages/react-sdk/src/components/DeviceSettings/DeviceSelectorAudio.tsx
packages/react-sdk/src/components/DeviceSettings/DeviceSelectorVideo.tsx
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
packages/react-sdk/src/utilities/callControlHandler.ts

This reverts #1604 after reports about not being able to enable camera/mic.
Also fixes OvercontraintError not being a class on Firefox.

fix: revert #1604

---

sample-apps/react-native/dogfood/src/components/CallControlls/MoreActionsButton.tsx
sample-apps/react-native/dogfood/src/theme.ts

Dogfood app fixes:
- Light theme color fixes
- fixes the feedback modal not opening issue

fix: update light theme colors for dogfood app

---

packages/client/package.json
packages/client/vite.config.ts
yarn.lock

Tweak the code coverage report, and upgrade to the latest `vitest`.

chore: improve test coverage reporting

---

sample-apps/react/egress-composite/src/components/layouts/Spotlight/Spotlight.scss
sample-apps/react/egress-composite/src/main.tsx

Fixes an issue spotted in https://getstream.zendesk.com/agent/tickets/58907
Unsets the `max-width` of the participant view in the `Spotlight` layout.

fix: unset participant max-width in the spotlight

---

packages/client/src/client-details.ts

Fix undefined state of `deviceStats` prop in the clientDetials

fix(client): fix the initial value of deviceState in clientDetails

---

packages/client/src/client-details.ts
packages/react-native-sdk/ios/StreamVideoReactNative.m
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx

Fixes the sendDeviceStats error as the thermalState was sent to the backend in wrong format.

fix: iOS thermal state issue

---

packages/client/src/Call.ts
packages/client/src/StreamSfuClient.ts
packages/client/src/__tests__/Call.publishing.test.ts
packages/client/src/devices/CameraManager.ts
packages/client/src/devices/InputMediaDeviceManager.ts
packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/ScreenShareManager.ts
packages/client/src/devices/__tests__/CameraManager.test.ts
packages/client/src/devices/__tests__/InputMediaDeviceManager.test.ts
packages/client/src/devices/__tests__/MicrophoneManager.test.ts
packages/client/src/devices/__tests__/ScreenShareManager.test.ts
packages/client/src/events/participant.ts
packages/client/src/helpers/array.ts
packages/client/src/rtc/Publisher.ts
packages/client/src/rtc/__tests__/Publisher.test.ts
packages/client/src/rtc/__tests__/mocks/webrtc.mocks.ts

Decouples the participant state management from the WebRTC Publisher. Improves the test coverage.

fix(publisher): Decouple state management and improve test coverage

---

.github/workflows/react-native-workflow.yml
packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt
packages/react-native-sdk/expo-config-plugin/__tests__/withAppDelegate.test.ts
packages/react-native-sdk/expo-config-plugin/src/common/types.ts
packages/react-native-sdk/expo-config-plugin/src/index.ts
packages/react-native-sdk/expo-config-plugin/src/withAppDelegate.ts
packages/react-native-sdk/ios/PictureInPicture/StreamPictureInPictureController.swift
packages/react-native-sdk/ios/RTCViewPip.swift
packages/react-native-sdk/src/components/Call/CallContent/RTCViewPipIOS.tsx
sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/ios/StreamReactNativeVideoSDKSample/AppDelegate.mm
sample-apps/react-native/dogfood/src/components/ActiveCall.tsx

Also new feature: adds camera enabling camera support in PiP for iOS 18  and above
* fixes #1647

fix: ios 18 pip support

---

sample-apps/react/react-dogfood/components/Inspector/InspectorCall.tsx
sample-apps/react/react-dogfood/style/Inspector.scss

fix: restore copy report button on device test page

---

packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/__tests__/MicrophoneManagerRN.test.ts
packages/client/src/helpers/RNSpeechDetector.ts

also checkout our new revamped voice detection algorithm, I added a simpler version of a voice activity algorithm (VAD) seen in an Android open source lib

fix: speech detection and align mic disable with web

---

packages/client/src/Call.ts
packages/client/src/gen/coordinator/index.ts

Relaxes the client-side validations that prevent submitting call feedback in certain scenarios.
Updates to the latest OpenAPI too.

fix: relaxed validation for submitting feedback

---

packages/react-native-sdk/src/hooks/push/useIosCallKeepEventsSetupEffect.ts
packages/react-native-sdk/src/hooks/push/useIosCallkeepWithCallingStateEffect.ts
packages/react-native-sdk/src/hooks/push/useIosVoipPushEventsSetupEffect.ts
packages/react-native-sdk/src/hooks/push/useProcessPushCallEffect.ts
packages/react-native-sdk/src/hooks/push/useProcessPushNonRingingCallEffect.ts
packages/react-native-sdk/src/utils/push/android.ts
packages/react-native-sdk/src/utils/push/internal/utils.ts
packages/react-native-sdk/src/utils/push/ios.ts

**bug**: calling client.connectUser at a later stage after <StreamVideo> mount did not enable voip apns.
**extra**: added many debug logs for push for support help

fix: send voip token also when connectUser is called later

---

sample-apps/react/audio-rooms/package.json
sample-apps/react/cookbook-participant-list/package.json
sample-apps/react/egress-composite/package.json
sample-apps/react/livestream-app/package.json
sample-apps/react/livestream-app/src/hosts/ui/BackstageControls.tsx
sample-apps/react/livestream-app/src/viewers/HLSLivestream.scss
sample-apps/react/livestream-app/src/viewers/HLSLivestream.tsx
sample-apps/react/messenger-clone/package.json
sample-apps/react/zoom-clone/package.json
yarn.lock

Adds HLS.BUFFER_EOS event handling to our live streaming sample app.
ref: https://getstream.slack.com/archives/C040262MY9K/p1739873779558179
ref: https://github.com/GetStream/docs-content/pull/196

feat: add handler for HLS buffer-eos event

---

packages/react-sdk/src/core/components/ParticipantView/ParticipantActionsContextMenu.tsx
sample-apps/react/react-dogfood/components/Debug/DebugParticipantViewUI.tsx

Disables the "Enter full screen" mode on platforms that don't support it.

fix: disable the "Enter full screen" option on unsupported platforms

---

packages/styling/src/CallControls/CallControls-layout.scss

Adds missing styles for #1718.

fix: add missing styles for pending permission badge

---

packages/react-native-sdk/src/contexts/ThemeContext.tsx
packages/react-native-sdk/src/providers/StreamVideo.tsx
sample-apps/react-native/dogfood/App.tsx
sample-apps/react-native/dogfood/src/components/VideoWrapper.tsx

https://linear.app/stream/issue/RN-178/rename-themeprovider-to-streamtheme
Adds `StreamTheme` alias for the `ThemeProvider`.

chore: rn-178 refactor theme provider

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

🚂 #1736 #1741
Muted state was not applied from persisted settings in some cases. This PR fixes that.
When applying muted state from persisted settings, we use the following values (from top priority to lowest priority):
1. Muted state from the first persisted device that is currently available
2. The latest user-selected user state

fix: correctly apply muted state from persisted settings

---

.gitignore
.husky/pre-commit
package.json

The Husky setup didn't automatically run as it used to do in 2016 so we have to set it up manually.

chore: husky setup

---

sample-apps/react/react-dogfood/hooks/usePipWindow.tsx

fix: silence compat errors in non-chromium browsers

---

packages/client/src/devices/MicrophoneManager.ts
packages/client/src/devices/__tests__/MicrophoneManager.test.ts
packages/client/src/devices/__tests__/MicrophoneManagerRN.test.ts
packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts
sample-apps/react/react-dogfood/components/MeetingUI.tsx
sample-apps/react/react-dogfood/components/Settings/DeviceSelection.tsx
sample-apps/react/react-dogfood/components/Settings/SettingsTabModal.tsx
sample-apps/react/react-dogfood/context/SettingsContext.tsx
sample-apps/react/react-dogfood/hooks/useDeviceSelectionPreference.ts
sample-apps/react/react-dogfood/style/SettingsTabModal.scss
sample-apps/react/react-dogfood/translations/en.json

1. Add an opt-out for persisted device preferences
2. Fix a possible race condition in speaking while muted detection

fix: add an opt-out for persisted device preferences

---

packages/client/src/Call.ts
packages/client/src/helpers/DynascaleManager.ts
packages/client/src/rtc/BasePeerConnection.ts

Adds more tracing data:
- client details
- audio output switching
- unique IDs for publisher and subscriber peer connections

fix: enhance tracing data

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

During refactor, `uPDP` hook stopped applying muted state from call settings by default. Restoring this behavior.

fix: apply call default camera/mic on settings

---

packages/client/src/coordinator/connection/client.ts
packages/client/src/coordinator/connection/types.ts

Ref: GetStream/chat#1540
🎫 Ticket: https://linear.app/stream/issue/REACT-302

chore: adjust ErrorFromResponse class

---

sample-apps/react-native/dogfood/ios/Podfile.lock
sample-apps/react-native/dogfood/package.json
sample-apps/react-native/dogfood/src/components/ChatWrapper.tsx
sample-apps/react-native/dogfood/src/hooks/useChatClient.tsx
sample-apps/react-native/dogfood/src/hooks/useUnreadCount.tsx
sample-apps/react-native/dogfood/src/screens/LiveStream/BottomSheetChatWrapper.tsx
sample-apps/react-native/dogfood/src/screens/Meeting/ChatScreen.tsx
sample-apps/react-native/dogfood/types.ts
sample-apps/react/messenger-clone/package.json
sample-apps/react/messenger-clone/src/components/ChannelHeader/ChannelHeader.tsx
sample-apps/react/messenger-clone/src/components/ChannelPreview/ChannelPreview.tsx
sample-apps/react/messenger-clone/src/components/CreateCallButton/CreateCallButton.tsx
sample-apps/react/messenger-clone/src/components/QuickDial/QuickDial.tsx
sample-apps/react/messenger-clone/src/components/Sidebar/Sidebar.tsx
sample-apps/react/messenger-clone/src/contexts/ClientProviders.tsx
sample-apps/react/messenger-clone/src/types/chat.ts
sample-apps/react/messenger-clone/src/utils/userFromToken.ts
sample-apps/react/react-dogfood/components/ChatUI.tsx
sample-apps/react/react-dogfood/hooks/useChatClient.ts
sample-apps/react/react-dogfood/package.json
sample-apps/react/zoom-clone/package.json
yarn.lock

Upgrades to `stream-chat@9`, `stream-chat-react@13`, and `stream-chat-react-native@7`.

chore: upgrade chat dependencies

---

packages/react-sdk/src/hooks/usePersistedDevicePreferences.ts

We want to avoid `usePersistedDevicePreferences` from overriding manually set mute status. Previously with this code the call ended up with whatever settings were persisted:
```jsx
function App() {
// ...
useEffect(() => {
// ...
await call.camera.disable();
await call.microphone.disable();
await call.getOrCreate();
// ...
}, [call]);
return <StreamCall call={call}><CallUI /></StreamCall>;
}
function CallUI() {
usePersistedDevicePreferences();
// ...
}
```
Now camera and mic will remain disabled (but preferred devices will sill be selected, if there was some preference persisted previously).

fix: prevent usePersistedDevicePreferences from overriding manually set status

---

packages/client/src/StreamSfuClient.ts
packages/client/src/rtc/signal.ts

Adds more telemetry data collection for the signal web socket.

fix: extended telemetry data for the signal websocket

---

sample-apps/react/react-dogfood/helpers/gong.ts

When Gong upload fails (for whatever reason), it's tedious to then manually compile the request to upload it manually.
Adding a log that includes the whole failed request, so that it can be easily retried manually.

chore: log request to retry failed gong upload

---

sample-apps/react/react-dogfood/components/Lobby.tsx
sample-apps/react/react-dogfood/components/ToggleHiFiButton.tsx

🎫 Ticket: https://linear.app/stream/issue/XYZ-123
📑 Docs: https://github.com/GetStream/docs-content/pull/<id>

chore: added hifi audio toggle in lobby

---

packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt
packages/react-native-sdk/ios/StreamVideoReactNative.m
packages/react-native-sdk/src/providers/StreamCall/DeviceStats.tsx
sample-apps/react-native/dogfood/ios/Podfile.lock

Adds additional tracing for battery level and battery charging state.
This data should allow us to calculate battery drain over time, and also check the impact of battery charging to the general device thermal state.

chore: trace charging and battery level

---

packages/client/src/coordinator/connection/client.ts

Fixes the broken axios request config merging logic.
🎫 Ticket: https://linear.app/stream/issue/REACT-569/

fix: graceful Axios request config overrides

---

packages/noise-cancellation-react-native/android/build.gradle

Update to the new snapshot url, the old one is dead

fix: noise cancellation snapshot url

---

packages/react-native-sdk/android/src/main/java/com/streamvideo/reactnative/StreamVideoReactNativeModule.kt

We cannot use Context constants from ReactApplicationContext from 0.81 due to this [PR](https://github.com/facebook/react-native/pull/52208) in RN
Changed to using constant from Context directly
fixes: #1921

fix: android RN module compilation error on RN 0.81

---

sample-apps/react-native/dogfood/src/components/CallStats.tsx

Fixes a bug where the publish resolution was used instead of the subscribed one.

fix: use subscriberStats for receiving bitrate

---

sample-apps/react/react-dogfood/pages/livestream/index.tsx

Make sure the demo user can join the livestream by verifying that they are part of the members and that the backstage is off.

chore: improve /livestream setup UX

---

AGENTS.md

Instructions for various coding agents.

chore: agent instructions
